<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>OPC Security (IOPCSecurityNT + IOPCSecurityPrivate) managed API.</Description>
    <RootNamespace>OpcClassic.Security</RootNamespace>
    <AssemblyName>OpcClassic.Security</AssemblyName>
    <PackageId>OpcClassic.Security</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpcClassic.Core\OpcClassic.Core.csproj" />
  </ItemGroup>

</Project>
