<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <RootNamespace>OpcClassic.AotCanary</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OpcClassic.Core\OpcClassic.Core.csproj" />
    <ProjectReference Include="..\..\src\OpcClassic.Da\OpcClassic.Da.csproj" />
  </ItemGroup>
</Project>
