/* Auto-generated by build scripts. Do not edit manually.
   This placeholder provides defaults for IDE/IntelliSense when
   the build script has not yet been run. */

#define xstr(s) str(s)
#define str(s) #s

#define MAJOR_VERSION 3
#define MINOR_VERSION 1
#define REVISION_VERSION 1
#define BUILD_VERSION 88

#define COPYRIGHT_DATE "2026"
#define FILE_VERSION_TEXT xstr(MAJOR_VERSION) "." xstr(MINOR_VERSION) "." xstr(REVISION_VERSION) "." xstr(BUILD_VERSION)
#define PRODUCT_VERSION_TEXT xstr(MAJOR_VERSION) "." xstr(MINOR_VERSION) "." xstr(REVISION_VERSION) ".0"
