<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>TUnit tests for OpcClassic.Cpx.</Description>
    <RootNamespace>OpcClassic.Cpx.Tests</RootNamespace>
    <AssemblyName>OpcClassic.Cpx.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpcClassic.Cpx\OpcClassic.Cpx.csproj" />
  </ItemGroup>

</Project>
