<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>.net Core DCOM tests</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests\Driver.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpInterop\SharpInterop.csproj" />
  </ItemGroup>
</Project>