<#
.SYNOPSIS
    OPC Core Components - Build Script

.DESCRIPTION
    Builds the 8 OPC COM proxy/stub DLLs, OpcEnum/CategoryManager, and
    optional native test applications. MSI packaging was removed from the
    vendored tree; this script now runs the native CMake build/install only.

.PARAMETER Platform
    Target platform: x86, x64, or both (default: both)

.PARAMETER Clean
    Remove build directory before building.

.PARAMETER SkipTests
    Do not build the OPC DA test server and client applications.

.PARAMETER BuildRoot
    Override build directory (default: .\build).
    Also settable via BUILD_ROOT environment variable.

.PARAMETER OutDir
    Override output directory (default: .\out).
    Also settable via OUT_DIR environment variable.

.EXAMPLE
    .\build.ps1                    # both platforms (default)
    .\build.ps1 -Platform x86     # x86 only
    .\build.ps1 -Platform x64     # x64 only
    .\build.ps1 -Clean            # clean rebuild
    . .\signing-key.ps1; .\build.ps1   # with code signing

.NOTES
    Prerequisites:
      - Visual Studio 2022+ with C++ desktop workload
      - CMake 3.20+ (included with Visual Studio or install separately)
      - AzureSignTool (for code signing): dotnet tool install --global AzureSignTool
#>

[CmdletBinding()]
param(
    [ValidateSet('x86', 'x64', 'both')]
    [string]$Platform = 'both',

    [switch]$Clean,

    [switch]$SkipTests,

    [string]$BuildRoot,
    [string]$OutDir
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

if (-not $BuildRoot) {
    $BuildRoot = if ($env:BUILD_ROOT) { $env:BUILD_ROOT } else { Join-Path $ScriptDir 'build' }
}
if (-not $OutDir) {
    $OutDir = if ($env:OUT_DIR) { $env:OUT_DIR } else { Join-Path $ScriptDir 'out' }
}
# ---------------------------------------------------------------------------
# Code signing detection
# ---------------------------------------------------------------------------
$SigningEnabled = -not [string]::IsNullOrWhiteSpace($env:SigningClientSecret)
if ($SigningEnabled) {
    # Verify AzureSignTool is available
    try {
        & AzureSignTool --version 2>$null | Out-Null
        if ($LASTEXITCODE -ne 0) { throw }
    }
    catch {
        throw "Code signing is enabled but AzureSignTool was not found. Install with: dotnet tool install --global AzureSignTool"
    }
    Write-Host 'Code signing: ENABLED'
} else {
    Write-Host 'Code signing: DISABLED (SigningClientSecret not set)'
}

# ---------------------------------------------------------------------------
# Version: read version.txt + auto-increment build.txt
# ---------------------------------------------------------------------------
$VersionFile = Join-Path $ScriptDir 'version.txt'
$BuildFile   = Join-Path $ScriptDir 'build.txt'

if (-not (Test-Path $VersionFile)) {
    throw "Version file not found: $VersionFile"
}
if (-not (Test-Path $BuildFile)) {
    throw "Build file not found: $BuildFile"
}

# Parse MAJOR, MINOR, REVISION from version.txt
$Major    = $null
$Minor    = $null
$Revision = $null
foreach ($line in (Get-Content $VersionFile)) {
    if ($line -match '^\s*MAJOR\s*=\s*(\d+)')    { $Major    = [int]$Matches[1] }
    if ($line -match '^\s*MINOR\s*=\s*(\d+)')    { $Minor    = [int]$Matches[1] }
    if ($line -match '^\s*REVISION\s*=\s*(\d+)') { $Revision = [int]$Matches[1] }
}
if ($null -eq $Major -or $null -eq $Minor -or $null -eq $Revision) {
    throw "Could not parse MAJOR, MINOR, and REVISION from $VersionFile"
}

# Read, increment, and write back build number
$Build = [int](Get-Content $BuildFile -Raw).Trim() + 1
Set-Content -Path $BuildFile -Value $Build -NoNewline

$Version     = "$Major.$Minor.$Revision.$Build"
$FileVersion = "$Major.$Minor.$Revision"
$CopyrightYear = (Get-Date).Year

# Generate version.h
$VersionH = Join-Path $ScriptDir 'src\Include\version.h'
$VersionHContent = @"
/* Auto-generated by build scripts. Do not edit manually.
   This placeholder provides defaults for IDE/IntelliSense when
   the build script has not yet been run. */

#define xstr(s) str(s)
#define str(s) #s

#define MAJOR_VERSION $Major
#define MINOR_VERSION $Minor
#define REVISION_VERSION $Revision
#define BUILD_VERSION $Build

#define COPYRIGHT_DATE "$CopyrightYear"
#define FILE_VERSION_TEXT xstr(MAJOR_VERSION) "." xstr(MINOR_VERSION) "." xstr(REVISION_VERSION) "." xstr(BUILD_VERSION)
#define PRODUCT_VERSION_TEXT xstr(MAJOR_VERSION) "." xstr(MINOR_VERSION) "." xstr(REVISION_VERSION) ".0"
"@
Set-Content -Path $VersionH -Value $VersionHContent

Write-Host ''
Write-Host "Building version $Version"
Write-Host ''

# ---------------------------------------------------------------------------
# Helper: build proxy/stub DLLs for one platform
# ---------------------------------------------------------------------------
function Build-Platform {
    param([string]$Arch)

    $BuildDir = Join-Path $BuildRoot $Arch
    $CmakeArch = if ($Arch -eq 'x86') { 'Win32' } else { 'x64' }

    Write-Host ''
    Write-Host '============================================================'
    Write-Host "  Building OPC Proxy/Stub DLLs ($Arch)"
    Write-Host '============================================================'
    Write-Host ''

    # Clean if requested
    if ($Clean -and (Test-Path $BuildDir)) {
        Write-Host "Cleaning $BuildDir..."
        Remove-Item $BuildDir -Recurse -Force
    }

    # Create directories
    New-Item -ItemType Directory -Path $BuildDir -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $OutDir "$Arch\bin") -Force | Out-Null

    # Configure (use v143 toolset = VS 2022 for Windows 7 SP1 CRT compatibility)
    Write-Host "Configuring CMake for $Arch..."
    $cmakeArgs = @('-S', $ScriptDir, '-B', $BuildDir, '-A', $CmakeArch, '-T', 'v143', "-DCMAKE_INSTALL_PREFIX=$OutDir\$Arch")
    if ($SkipTests) {
        $cmakeArgs += '-DOPC_BUILD_TESTS=OFF'
    }
    & cmake @cmakeArgs
    if ($LASTEXITCODE -ne 0) { throw "CMake configuration failed for $Arch." }

    # Build
    Write-Host 'Building...'
    & cmake --build $BuildDir --config Release
    if ($LASTEXITCODE -ne 0) { throw "Build failed for $Arch." }

    # Install
    Write-Host "Installing to $OutDir\$Arch..."
    & cmake --install $BuildDir --config Release
    if ($LASTEXITCODE -ne 0) { throw "Install failed for $Arch." }

    # Sign binaries after install
    if ($SigningEnabled) {
        Write-Host "Signing $Arch binaries..."
        $binFiles = @(Get-ChildItem (Join-Path $OutDir "$Arch\bin") -Include '*.dll','*.exe' -Recurse | Select-Object -ExpandProperty FullName)
        $sdkDlls  = @(Get-ChildItem (Join-Path $OutDir "$Arch\include") -Filter '*.dll' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)
        Sign-Files ($binFiles + $sdkDlls)
    }

    Write-Host ''
    Write-Host "  $Arch build complete. DLLs in: $OutDir\$Arch\bin"
    Write-Host ''
}

# ---------------------------------------------------------------------------
# Helper: sign files with AzureSignTool
# ---------------------------------------------------------------------------
function Sign-Files {
    param([string[]]$Files)
    if (-not $SigningEnabled) { return }
    $existing = @($Files | Where-Object { Test-Path $_ })
    if ($existing.Count -eq 0) { return }
    Write-Host "  Signing $($existing.Count) file(s)..."
    & AzureSignTool sign `
        -kvu $env:SigningVaultURL `
        -kvi $env:SigningClientId `
        -kvs $env:SigningClientSecret `
        -kvt $env:SigningTenantId `
        -kvc $env:SigningCertName `
        -tr  $env:SigningURL `
        -td  sha256 `
        @existing
    if ($LASTEXITCODE -ne 0) { throw "Code signing failed." }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
try {
    # Create top-level output directories
    New-Item -ItemType Directory -Path $BuildRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null

    # Build DLLs
    $platforms = if ($Platform -eq 'both') { @('x86', 'x64') } else { @($Platform) }

    foreach ($arch in $platforms) {
        Build-Platform $arch
    }

    Write-Host ''
    Write-Host '============================================================'
    Write-Host '  BUILD COMPLETE'
    Write-Host '============================================================'
    Write-Host ''
    Write-Host "  Output files in: $OutDir"
    Write-Host ''
}
catch {
    Write-Host "ERROR: $_" -ForegroundColor Red
    exit 1
}
