//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpInterop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpInterop.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect function..
        /// </summary>
        internal static string _0x00000001 {
            get {
                return ResourceManager.GetString("0x00000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the file specified. Please check the path provided as parameter. If this exception is being thrown from the WinReg package, please check if the library is registered properly or do so using regsvr32..
        /// </summary>
        internal static string _0x00000002 {
            get {
                return ResourceManager.GetString("0x00000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the path specified. .
        /// </summary>
        internal static string _0x00000003 {
            get {
                return ResourceManager.GetString("0x00000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied, please check whether the [domain-username-password] are correct. Also, if not already done please check the GETTING STARTED and FAQ sections in readme.htm. They provide information on how to correctly configure the Windows machine for DCOM access, so as to avoid such exceptions. .
        /// </summary>
        internal static string _0x00000005 {
            get {
                return ResourceManager.GetString("0x00000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filename, directory name, or volume label syntax is incorrect..
        /// </summary>
        internal static string _0x0000007B {
            get {
                return ResourceManager.GetString("0x0000007B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.  .
        /// </summary>
        internal static string _0x000000B7 {
            get {
                return ResourceManager.GetString("0x000000B7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more data is available..
        /// </summary>
        internal static string _0x00000103 {
            get {
                return ResourceManager.GetString("0x00000103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is already instantiated..
        /// </summary>
        internal static string _0x00001001 {
            get {
                return ResourceManager.GetString("0x00001001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This API cannot be invoked, further data preparation is required..
        /// </summary>
        internal static string _0x00001002 {
            get {
                return ResourceManager.GetString("0x00001002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is already established, please initiate a new session for new Stub..
        /// </summary>
        internal static string _0x00001003 {
            get {
                return ResourceManager.GetString("0x00001003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminant cannot be null..
        /// </summary>
        internal static string _0x00001004 {
            get {
                return ResourceManager.GetString("0x00001004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminant class type mismatch, please provide object of the same class as discriminant..
        /// </summary>
        internal static string _0x00001005 {
            get {
                return ResourceManager.GetString("0x00001005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 discriminant allowed for serialization, please remove the rest or no discriminant has been added at all..
        /// </summary>
        internal static string _0x00001006 {
            get {
                return ResourceManager.GetString("0x00001006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No discriminant value has been added at all..
        /// </summary>
        internal static string _0x00001007 {
            get {
                return ResourceManager.GetString("0x00001007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Value of FLAG sent for this API. This FLAG is not valid here..
        /// </summary>
        internal static string _0x00001008 {
            get {
                return ResourceManager.GetString("0x00001008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Library Error. This method should not have been called. Please check the parameters which you have passed to JICallBuilder. They have been sent incorrectly..
        /// </summary>
        internal static string _0x00001009 {
            get {
                return ResourceManager.GetString("0x00001009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outparams cannot have more than 1 parameter here. It should be a JIVariant class parameter..
        /// </summary>
        internal static string _0x0000100A {
            get {
                return ResourceManager.GetString("0x0000100A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters inparams and dispId\paramNames arrays should have same length..
        /// </summary>
        internal static string _0x0000100B {
            get {
                return ResourceManager.GetString("0x0000100B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This in parameter cannot have null or \&quot;\&quot; values..
        /// </summary>
        internal static string _0x0000100C {
            get {
                return ResourceManager.GetString("0x0000100C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameters can be empty or null. Please provide valid parameters..
        /// </summary>
        internal static string _0x0000100D {
            get {
                return ResourceManager.GetString("0x0000100D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve CLSID from PROGID via Windows Remote Registry Service..
        /// </summary>
        internal static string _0x0000100E {
            get {
                return ResourceManager.GetString("0x0000100E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Library Error, the serializer\deserializer was not found for {0}.  Please check the parameters passed to JICallBuilder..
        /// </summary>
        internal static string _0x0000100F {
            get {
                return ResourceManager.GetString("0x0000100F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication information was not supplied..
        /// </summary>
        internal static string _0x00001010 {
            get {
                return ResourceManager.GetString("0x00001010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect or Invalid Parameter(s) specified..
        /// </summary>
        internal static string _0x00001011 {
            get {
                return ResourceManager.GetString("0x00001011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template cannot be null. .
        /// </summary>
        internal static string _0x00001012 {
            get {
                return ResourceManager.GetString("0x00001012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Arrays Accepted as parameter..
        /// </summary>
        internal static string _0x00001013 {
            get {
                return ResourceManager.GetString("0x00001013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrays of Primitive Data Types are not accepted..
        /// </summary>
        internal static string _0x00001014 {
            get {
                return ResourceManager.GetString("0x00001014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only accept JIStruct, JIUnion, JIPointer and JIString as parameters for template..
        /// </summary>
        internal static string _0x00001015 {
            get {
                return ResourceManager.GetString("0x00001015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPID cannot be null..
        /// </summary>
        internal static string _0x00001016 {
            get {
                return ResourceManager.GetString("0x00001016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discriminant can only be of the type Integer,Short,Boolean or Character..
        /// </summary>
        internal static string _0x00001017 {
            get {
                return ResourceManager.GetString("0x00001017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _0x00001018 {
            get {
                return ResourceManager.GetString("0x00001018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a programming error, this API should not be called..
        /// </summary>
        internal static string _0x00001019 {
            get {
                return ResourceManager.GetString("0x00001019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters cannot be null..
        /// </summary>
        internal static string _0x0000101A {
            get {
                return ResourceManager.GetString("0x0000101A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An array has already been added as member and it has to be the last member of this Struct. Please insert this member elsewhere..
        /// </summary>
        internal static string _0x0000101B {
            get {
                return ResourceManager.GetString("0x0000101B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An array can be added only as a last member in a structure and not in between..
        /// </summary>
        internal static string _0x0000101C {
            get {
                return ResourceManager.GetString("0x0000101C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Struct already has an array and the member (which also happens to be a Struct) has an array too. This member can only be present in the second last position of this new Struct..
        /// </summary>
        internal static string _0x0000101D {
            get {
                return ResourceManager.GetString("0x0000101D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member(which happens to be a Struct) has an array and hence can only be added to the end of this Struct, not in between..
        /// </summary>
        internal static string _0x0000101E {
            get {
                return ResourceManager.GetString("0x0000101E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failure for the credentials sent by the COM server for performing call back. The identity is checked via a call back to the source COM server using SMB..
        /// </summary>
        internal static string _0x0000101F {
            get {
                return ResourceManager.GetString("0x0000101F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMB connection failure, please check whether SERVER service is running on Target machine (where COM server) is hosted..
        /// </summary>
        internal static string _0x00001020 {
            get {
                return ResourceManager.GetString("0x00001020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal here to invoke this API..
        /// </summary>
        internal static string _0x00001021 {
            get {
                return ResourceManager.GetString("0x00001021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants can only take BSTR Strings and no other String Type..
        /// </summary>
        internal static string _0x00001022 {
            get {
                return ResourceManager.GetString("0x00001022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overloaded APIs are not allowed..
        /// </summary>
        internal static string _0x00001023 {
            get {
                return ResourceManager.GetString("0x00001023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variants cannot take object[] having Variants themselves as indices..
        /// </summary>
        internal static string _0x00001024 {
            get {
                return ResourceManager.GetString("0x00001024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fractionalUnits cannot be negative..
        /// </summary>
        internal static string _0x00001025 {
            get {
                return ResourceManager.GetString("0x00001025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant is null..
        /// </summary>
        internal static string _0x00001026 {
            get {
                return ResourceManager.GetString("0x00001026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library currently accepts only up to 2 dimension for the JIVariant..
        /// </summary>
        internal static string _0x00001027 {
            get {
                return ResourceManager.GetString("0x00001027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bounds is to be specified for all dimensions or not specified at all..
        /// </summary>
        internal static string _0x00001028 {
            get {
                return ResourceManager.GetString("0x00001028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the JIArray to pass arrays..
        /// </summary>
        internal static string _0x00001029 {
            get {
                return ResourceManager.GetString("0x00001029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type for VARIANT. .
        /// </summary>
        internal static string _0x00001030 {
            get {
                return ResourceManager.GetString("0x00001030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access Windows Registry, please check whether the SERVER service is running on the Target Workstation..
        /// </summary>
        internal static string _0x00001031 {
            get {
                return ResourceManager.GetString("0x00001031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Identifier, or there is no Connection Info associated with this identifier on this comObject..
        /// </summary>
        internal static string _0x00001032 {
            get {
                return ResourceManager.GetString("0x00001032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set the correct encoding for password field..
        /// </summary>
        internal static string _0x00001033 {
            get {
                return ResourceManager.GetString("0x00001033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown hostname\ip was supplied for obtaining handle to WinReg..
        /// </summary>
        internal static string _0x00001034 {
            get {
                return ResourceManager.GetString("0x00001034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not supported for setting\getting value in\from registry..
        /// </summary>
        internal static string _0x00001035 {
            get {
                return ResourceManager.GetString("0x00001035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal values sent as parameters, please check &quot;data&quot;..
        /// </summary>
        internal static string _0x00001036 {
            get {
                return ResourceManager.GetString("0x00001036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIMethodDescriptor is being added to a JIInterfaceDefinition supporting dispInterface, but it itself does not have a dispId..
        /// </summary>
        internal static string _0x00001037 {
            get {
                return ResourceManager.GetString("0x00001037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameters can be null or &quot;&quot;..
        /// </summary>
        internal static string _0x00001038 {
            get {
                return ResourceManager.GetString("0x00001038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported charset supplied while encoding or decoding String..
        /// </summary>
        internal static string _0x00001039 {
            get {
                return ResourceManager.GetString("0x00001039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned numbers cannot be negative or null..
        /// </summary>
        internal static string _0x00001040 {
            get {
                return ResourceManager.GetString("0x00001040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not supported for unsigned operations. Only Long,Short,Integer allowed..
        /// </summary>
        internal static string _0x00001041 {
            get {
                return ResourceManager.GetString("0x00001041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Object.class&quot; arrays are not accepted. Only properly typed arrays accepted..
        /// </summary>
        internal static string _0x00001042 {
            get {
                return ResourceManager.GetString("0x00001042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This JILocalCoClass has already been exported with one COM object, please use a new instance of this class to get a new reference to a local COM object..
        /// </summary>
        internal static string _0x00001043 {
            get {
                return ResourceManager.GetString("0x00001043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIInterfacePointer is not a valid parameter, please use JIVariant(IJIComObject,...)..
        /// </summary>
        internal static string _0x00001044 {
            get {
                return ResourceManager.GetString("0x00001044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Marshalling, UnMarshalling of Strings are not allowed, please use JIString instead..
        /// </summary>
        internal static string _0x00001045 {
            get {
                return ResourceManager.GetString("0x00001045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createInstance() cannot be called since the JIComServer(JISession, JIInterfacePointer, String) ctor was used to create this COM server instance, please use getInstance() instead..
        /// </summary>
        internal static string _0x00001046 {
            get {
                return ResourceManager.GetString("0x00001046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getInstance() cannot be called since the JIComServer(JISession, JIInterfacePointer, String) ctor was NOT used to create this COM server instance, please use createInstance() instead..
        /// </summary>
        internal static string _0x00001047 {
            get {
                return ResourceManager.GetString("0x00001047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session is already attached with this COM object..
        /// </summary>
        internal static string _0x00001048 {
            get {
                return ResourceManager.GetString("0x00001048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This API cannot be invoked on local references..
        /// </summary>
        internal static string _0x00001049 {
            get {
                return ResourceManager.GetString("0x00001049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session is not attached with this object, use JIObjectFactory.buildObject(JISession, IJIComObject) to attach a session with this object..
        /// </summary>
        internal static string _0x00001050 {
            get {
                return ResourceManager.GetString("0x00001050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The associated session is being destroyed. Current call to COM server has been terminated..
        /// </summary>
        internal static string _0x00001051 {
            get {
                return ResourceManager.GetString("0x00001051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is available only under &quot;Microsoft Windows&quot; line of Operating systems. .
        /// </summary>
        internal static string _0x00001052 {
            get {
                return ResourceManager.GetString("0x00001052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.S.O cannot be used with ProgId based ctors..
        /// </summary>
        internal static string _0x00001053 {
            get {
                return ResourceManager.GetString("0x00001053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented..
        /// </summary>
        internal static string _0x80004001 {
            get {
                return ResourceManager.GetString("0x80004001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such interface supported..
        /// </summary>
        internal static string _0x80004002 {
            get {
                return ResourceManager.GetString("0x80004002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error..
        /// </summary>
        internal static string _0x80004005 {
            get {
                return ResourceManager.GetString("0x80004005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Remote activation was necessary but the server name provided was invalid..
        /// </summary>
        internal static string _0x80004014 {
            get {
                return ResourceManager.GetString("0x80004014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server process could not be started, the pathname may be incorrect. .
        /// </summary>
        internal static string _0x80004018 {
            get {
                return ResourceManager.GetString("0x80004018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server process could not be started as the configured identity, the pathname may be incorrect or unavailable. .
        /// </summary>
        internal static string _0x80004019 {
            get {
                return ResourceManager.GetString("0x80004019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server process could not be started because the configured identity is incorrect.  Check the username and password..
        /// </summary>
        internal static string _0x8000401A {
            get {
                return ResourceManager.GetString("0x8000401A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is not allowed to launch this server. .
        /// </summary>
        internal static string _0x8000401B {
            get {
                return ResourceManager.GetString("0x8000401B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catastrophic failure..
        /// </summary>
        internal static string _0x8000FFFF {
            get {
                return ResourceManager.GetString("0x8000FFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call was rejected by callee..
        /// </summary>
        internal static string _0x80010001 {
            get {
                return ResourceManager.GetString("0x80010001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System call failed. You might need to restart the server. .
        /// </summary>
        internal static string _0x80010100 {
            get {
                return ResourceManager.GetString("0x80010100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server threw an exception..
        /// </summary>
        internal static string _0x80010105 {
            get {
                return ResourceManager.GetString("0x80010105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object invoked has disconnected from its clients..
        /// </summary>
        internal static string _0x80010108 {
            get {
                return ResourceManager.GetString("0x80010108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of OLE on the client and server machines does not match.  .
        /// </summary>
        internal static string _0x80010110 {
            get {
                return ResourceManager.GetString("0x80010110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested object or interface does not exist..
        /// </summary>
        internal static string _0x80010113 {
            get {
                return ResourceManager.GetString("0x80010113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested object does not exist. .
        /// </summary>
        internal static string _0x80010114 {
            get {
                return ResourceManager.GetString("0x80010114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The marshaled interface data packet (OBJREF) has an invalid or unknown format..
        /// </summary>
        internal static string _0x8001011D {
            get {
                return ResourceManager.GetString("0x8001011D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred..
        /// </summary>
        internal static string _0x8001FFFF {
            get {
                return ResourceManager.GetString("0x8001FFFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown interface. .
        /// </summary>
        internal static string _0x80020001 {
            get {
                return ResourceManager.GetString("0x80020001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found. .
        /// </summary>
        internal static string _0x80020003 {
            get {
                return ResourceManager.GetString("0x80020003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not found. .
        /// </summary>
        internal static string _0x80020004 {
            get {
                return ResourceManager.GetString("0x80020004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch. .
        /// </summary>
        internal static string _0x80020005 {
            get {
                return ResourceManager.GetString("0x80020005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown name..
        /// </summary>
        internal static string _0x80020006 {
            get {
                return ResourceManager.GetString("0x80020006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No named arguments. .
        /// </summary>
        internal static string _0x80020007 {
            get {
                return ResourceManager.GetString("0x80020007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad variable type. .
        /// </summary>
        internal static string _0x80020008 {
            get {
                return ResourceManager.GetString("0x80020008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred. .
        /// </summary>
        internal static string _0x80020009 {
            get {
                return ResourceManager.GetString("0x80020009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index. .
        /// </summary>
        internal static string _0x8002000B {
            get {
                return ResourceManager.GetString("0x8002000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of parameters. .
        /// </summary>
        internal static string _0x8002000E {
            get {
                return ResourceManager.GetString("0x8002000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not optional. .
        /// </summary>
        internal static string _0x8002000F {
            get {
                return ResourceManager.GetString("0x8002000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid callee..
        /// </summary>
        internal static string _0x80020010 {
            get {
                return ResourceManager.GetString("0x80020010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element not found..
        /// </summary>
        internal static string _0x8002802B {
            get {
                return ResourceManager.GetString("0x8002802B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong module kind for the operation..
        /// </summary>
        internal static string _0x800288BD {
            get {
                return ResourceManager.GetString("0x800288BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not registered. If you are using a DLL/OCX, please make sure it has &quot;DllSurrogate&quot; flag set. Faq A(6) in readme.html..
        /// </summary>
        internal static string _0x80040154 {
            get {
                return ResourceManager.GetString("0x80040154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface not registered..
        /// </summary>
        internal static string _0x80040155 {
            get {
                return ResourceManager.GetString("0x80040155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space for tools is not available..
        /// </summary>
        internal static string _0x800401A1 {
            get {
                return ResourceManager.GetString("0x800401A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM server could not establish call back connection..
        /// </summary>
        internal static string _0x80040202 {
            get {
                return ResourceManager.GetString("0x80040202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the file specified. Is the COM Server present ? Please check DCOMCNFG for it&apos;s listing..
        /// </summary>
        internal static string _0x80070002 {
            get {
                return ResourceManager.GetString("0x80070002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot find the path specified. .
        /// </summary>
        internal static string _0x80070003 {
            get {
                return ResourceManager.GetString("0x80070003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. .
        /// </summary>
        internal static string _0x80070005 {
            get {
                return ResourceManager.GetString("0x80070005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough storage is available to complete this operation. .
        /// </summary>
        internal static string _0x8007000E {
            get {
                return ResourceManager.GetString("0x8007000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is incorrect..
        /// </summary>
        internal static string _0x80070057 {
            get {
                return ResourceManager.GetString("0x80070057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified module could not be found. Please check if the COM server is present at it&apos;s location..
        /// </summary>
        internal static string _0x8007007E {
            get {
                return ResourceManager.GetString("0x8007007E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RPC server is unavailable. Please check if the COM server is up and running and that route to the COM Server is accessible (A simple &quot;Ping&quot; to the Server machine would do). Also please confirm if the Windows Firewall is not blocking DCOM access..
        /// </summary>
        internal static string _0x800706BA {
            get {
                return ResourceManager.GetString("0x800706BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote procedure call failed. This could be an internal library error or the COM server simply declined the request. Please contact library development team. .
        /// </summary>
        internal static string _0x800706BE {
            get {
                return ResourceManager.GetString("0x800706BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A remote procedure call (RPC) protocol error occurred. .
        /// </summary>
        internal static string _0x800706C0 {
            get {
                return ResourceManager.GetString("0x800706C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure number is out of range..
        /// </summary>
        internal static string _0x800706D1 {
            get {
                return ResourceManager.GetString("0x800706D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stub received bad data. Please check whether the API has been called in the right way, with correct parameter formation..
        /// </summary>
        internal static string _0x800706F7 {
            get {
                return ResourceManager.GetString("0x800706F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object exporter was not found..
        /// </summary>
        internal static string _0x80070776 {
            get {
                return ResourceManager.GetString("0x80070776", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server execution failed..
        /// </summary>
        internal static string _0x80080005 {
            get {
                return ResourceManager.GetString("0x80080005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch..
        /// </summary>
        internal static string _0x800A000D {
            get {
                return ResourceManager.GetString("0x800A000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Violation..
        /// </summary>
        internal static string _0xC0000005 {
            get {
                return ResourceManager.GetString("0xC0000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempted logon is invalid. This is either due to a bad username or authentication information..
        /// </summary>
        internal static string _0xC000006D {
            get {
                return ResourceManager.GetString("0xC000006D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure number is out of range..
        /// </summary>
        internal static string _0xC002002E {
            get {
                return ResourceManager.GetString("0xC002002E", resourceCulture);
            }
        }
    }
}
