//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Opc.Classic .NET Contributors
//
// Smoke-test marker generator — proves the source-generator toolchain works end-to-end.
// Sibling generators (DispatchGenerator, MarshallerGenerator, GuidTableGenerator,
// JsonContextGenerator) live under this same assembly.
//

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Opc.Classic.Generators;

/// <summary>
/// Emits <c>Opc.Classic.Generators.ClassicGeneratorMarker</c> into every
/// consuming project as a smoke-test that the generator pipeline is alive.
/// Future per-feature generators are sibling <see cref="IIncrementalGenerator"/>
/// implementations in this same assembly.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ClassicMarkerGenerator : IIncrementalGenerator
{
    private const string GeneratedSource = @"// <auto-generated by Opc.Classic.Generators />
#nullable enable

namespace Opc.Classic.Generators
{
    /// <summary>
    /// Smoke-test marker emitted into every project that references
    /// <c>Opc.Classic.Generators</c> as an analyzer. Confirms the source-generator
    /// pipeline is wired correctly end-to-end.
    /// </summary>
    /// <remarks>
    /// Emitted <c>internal</c> so each consuming project carries its own
    /// private copy and downstream consumers don't see type-conflict
    /// diagnostics (CS0436) when they also reference the generator.
    /// </remarks>
    internal static class ClassicGeneratorMarker
    {
        /// <summary>
        /// Tracks the generator surface as it evolves. Bumped per phase.
        /// </summary>
        public const string Version = ""0.2.0-dev"";

        /// <summary>
        /// Human-readable description of the current generator surface.
        /// </summary>
        public const string Description = ""Marker + OpcInterface generators"";
    }
}
";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // RegisterPostInitializationOutput emits unconditional source — runs once
        // per compilation, before any syntax/symbol-driven generators see input.
        // Perfect for emitting marker types that future generators will reference.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: "ClassicGeneratorMarker.g.cs",
                sourceText: SourceText.From(GeneratedSource, Encoding.UTF8)));
    }
}
