// Copyright (c) 2026 Opc.Classic Contributors. Licensed under the MIT License.
// The first functional source generator.
//
// Consumer pattern:
//
//     [OpcInterface("39C13A4D-011E-11D0-9675-0020AFD8ADB3")]
//     public partial interface IOPCServer { ... }
//
// Generator emits a partial interface declaration that adds a
// compile-time-known InterfaceId:
//
//     partial interface IOPCServer
//     {
//         public static System.Guid InterfaceId { get; } = new("39C13A4D-...");
//     }
//
// AOT-safe by construction: the Guid is a static field initialized from a
// constant string, no reflection, no [DynamicallyAccessedMembers] required.
//
// Future expansion lives here: per-method [OpcMethod(opnum)] on members of
// the partial interface will drive emission of CallBuilder-based shims.
//

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Opc.Classic.Generators;

/// <summary>
/// Source generator that handles <c>[OpcInterface(iid)]</c>-annotated
/// partial interfaces. Emits a sibling partial declaration carrying a
/// strongly-typed <c>InterfaceId</c> static property.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OpcInterfaceGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "Opc.Classic.Generators";
    private const string AttributeName = "OpcInterfaceAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;
    private const string MethodAttributeName = "OpcMethodAttribute";
    private const string MethodAttributeFullName = AttributeNamespace + "." + MethodAttributeName;

    private const string AttributeSource = @"// <auto-generated by Opc.Classic.Generators.OpcInterfaceGenerator />
#nullable enable

namespace Opc.Classic.Generators
{
    /// <summary>
    /// Marks a partial interface as the managed projection of a DCOM
    /// interface. The generator emits a sibling partial declaration with
    /// a strongly-typed <c>InterfaceId</c> static property.
    /// </summary>
    /// <remarks>
    /// The constructor argument must be a valid GUID string in any
    /// format accepted by <see cref=""global::System.Guid.Parse(string)"" />.
    /// Validation occurs at generator-time; an invalid GUID produces a
    /// diagnostic and no <c>InterfaceId</c> is emitted.
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcInterfaceAttribute : global::System.Attribute
    {
        public OpcInterfaceAttribute(string iid) { Iid = iid; }
        public string Iid { get; }
    }

    /// <summary>
    /// Marks a method on an <c>[OpcInterface]</c>-decorated partial interface
    /// as the managed projection of a DCOM call. The generator emits the
    /// method's opnum as a public const in a nested <c>Opnums</c> static
    /// class on the interface, ready for downstream call-shim generators.
    /// </summary>
    /// <remarks>
    /// Opnum values follow the DCE/RPC convention: 0/1/2 are reserved for
    /// QueryInterface/AddRef/Release (or their IDispatch equivalents), so
    /// the first IDL-declared method on a typical IUnknown-derived
    /// interface starts at opnum 3.
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcMethodAttribute : global::System.Attribute
    {
        public OpcMethodAttribute(int opnum) { Opnum = opnum; }
        public int Opnum { get; }
    }

    /// <summary>
    /// Requests a generated result record for DCOM methods whose response
    /// payload contains multiple out values.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcGenerateMultiOutRecordAttribute : global::System.Attribute
    {
        public OpcGenerateMultiOutRecordAttribute() { }
        public OpcGenerateMultiOutRecordAttribute(string recordName) { RecordName = recordName; }
        public string? RecordName { get; }
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.ReturnValue, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcIidIsAttribute : global::System.Attribute
    {
        public OpcIidIsAttribute(string parameterName) { ParameterName = parameterName; }
        public string ParameterName { get; }
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.ReturnValue, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcArrayCountAttribute : global::System.Attribute
    {
        public OpcArrayCountAttribute(string parameterName) { ParameterName = parameterName; }
        public string ParameterName { get; }
    }
}
";

    private const string DiagnosticCategory = "Opc.Classic.Generators";
    private const string DiagnosticsHelpLinkUri = "docs/generators/diagnostics.md";

    private static readonly DiagnosticDescriptor InvalidGuidDescriptor = new(
        id: "OPCGEN001",
        title: "OpcInterface attribute carries an invalid GUID",
        messageFormat: "OpcInterface attribute on '{0}' has an invalid GUID literal '{1}'",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor NotPartialDescriptor = new(
        id: "OPCGEN002",
        title: "OpcInterface target must be partial",
        messageFormat: "Interface '{0}' is decorated with [OpcInterface] but is not declared partial",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor DuplicateOpnumDescriptor = new(
        id: "OPCGEN003",
        title: "Duplicate OpcMethod opnum",
        messageFormat: "Interface '{0}' has multiple methods sharing opnum {1}: '{2}' and '{3}'",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: "OpcInterfaceAttribute.g.cs",
                sourceText: SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: AttributeFullName,
            predicate: static (node, _) => node is InterfaceDeclarationSyntax,
            transform: static (ctx, _) => Transform(ctx));

        context.RegisterSourceOutput(candidates, Emit);
    }

    private static InterfaceModel? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (ctx.TargetNode is not InterfaceDeclarationSyntax syntax)
        {
            return null;
        }

        var attribute = ctx.Attributes[0];
        string? iid = attribute.ConstructorArguments.Length == 1
            ? attribute.ConstructorArguments[0].Value as string
            : null;

        bool isPartial = false;
        foreach (var modifier in syntax.Modifiers)
        {
            if (modifier.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword))
            {
                isPartial = true;
                break;
            }
        }

        var methods = CollectOpcMethods(symbol);

        return new InterfaceModel(
            fullyQualifiedName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            @namespace: symbol.ContainingNamespace?.IsGlobalNamespace == false
                ? symbol.ContainingNamespace!.ToDisplayString()
                : null,
            name: symbol.Name,
            accessibility: symbol.DeclaredAccessibility,
            iid: iid,
            isPartial: isPartial,
            location: syntax.Identifier.GetLocation(),
            methods: methods);
    }

    private static System.Collections.Immutable.ImmutableArray<OpcMethodInfo> CollectOpcMethods(INamedTypeSymbol interfaceSymbol)
    {
        var builder = System.Collections.Immutable.ImmutableArray.CreateBuilder<OpcMethodInfo>();
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method)
            {
                continue;
            }

            foreach (var attr in method.GetAttributes())
            {
                string? fullName = attr.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    ?.Replace("global::", string.Empty);
                if (!string.Equals(fullName, MethodAttributeFullName, System.StringComparison.Ordinal))
                {
                    continue;
                }

                if (attr.ConstructorArguments.Length != 1 ||
                    attr.ConstructorArguments[0].Value is not int opnum)
                {
                    continue;
                }

                builder.Add(new OpcMethodInfo(method.Name, opnum));
                break;
            }
        }
        return builder.ToImmutable();
    }

    private static void Emit(SourceProductionContext spc, InterfaceModel? maybeModel)
    {
        if (maybeModel is null)
        {
            return;
        }

        InterfaceModel model = maybeModel;

        if (!model.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(NotPartialDescriptor, model.Location, model.FullyQualifiedName));
            return;
        }

        if (string.IsNullOrWhiteSpace(model.Iid) || !System.Guid.TryParse(model.Iid, out _))
        {
            spc.ReportDiagnostic(Diagnostic.Create(InvalidGuidDescriptor, model.Location, model.FullyQualifiedName, model.Iid ?? "<null>"));
            return;
        }

        var sb = new StringBuilder(512);
        sb.AppendLine("// <auto-generated by Opc.Classic.Generators.OpcInterfaceGenerator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string accessibility = AccessibilityKeyword(model.Accessibility);
        sb.Append("    ").Append(accessibility).Append(" partial interface ").AppendLine(model.Name);
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>The DCOM interface identifier for this OPC interface.</summary>");
        sb.Append("        public static global::System.Guid InterfaceId { get; } = new global::System.Guid(\"")
          .Append(model.Iid)
          .AppendLine("\");");

        if (!EmitOpnums(spc, model, sb))
        {
            return;
        }

        sb.AppendLine("    }");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        string hint = model.FullyQualifiedName.Replace("global::", "").Replace("<", "_").Replace(">", "_") + ".OpcInterface.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool EmitOpnums(SourceProductionContext spc, InterfaceModel model, StringBuilder sb)
    {
        if (model.Methods.IsDefaultOrEmpty)
        {
            return true;
        }

        // Detect duplicate opnum values — DCE/RPC requires per-interface uniqueness.
        var seen = new System.Collections.Generic.Dictionary<int, string>();
        foreach (var m in model.Methods)
        {
            if (seen.TryGetValue(m.Opnum, out var firstName))
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    DuplicateOpnumDescriptor, model.Location,
                    model.FullyQualifiedName, m.Opnum, firstName, m.Name));
                return false;
            }
            seen[m.Opnum] = m.Name;
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>DCE/RPC opnums for the methods on this interface.</summary>");
        sb.AppendLine("        public static class Opnums");
        sb.AppendLine("        {");
        foreach (var m in model.Methods)
        {
            sb.Append("            public const int ").Append(m.Name).Append(" = ").Append(m.Opnum).AppendLine(";");
        }
        sb.AppendLine("        }");
        return true;
    }

    private static string AccessibilityKeyword(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.NotApplicable => "internal",
        _ => "internal",
    };

    private sealed class OpcMethodInfo
    {
        public OpcMethodInfo(string name, int opnum)
        {
            Name = name;
            Opnum = opnum;
        }

        public string Name { get; }
        public int Opnum { get; }
    }

    private sealed class InterfaceModel
    {
        public InterfaceModel(string fullyQualifiedName, string? @namespace, string name, Accessibility accessibility, string? iid, bool isPartial, Location location, System.Collections.Immutable.ImmutableArray<OpcMethodInfo> methods)
        {
            FullyQualifiedName = fullyQualifiedName;
            Namespace = @namespace;
            Name = name;
            Accessibility = accessibility;
            Iid = iid;
            IsPartial = isPartial;
            Location = location;
            Methods = methods;
        }

        public string FullyQualifiedName { get; }
        public string? Namespace { get; }
        public string Name { get; }
        public Accessibility Accessibility { get; }
        public string? Iid { get; }
        public bool IsPartial { get; }
        public Location Location { get; }
        public System.Collections.Immutable.ImmutableArray<OpcMethodInfo> Methods { get; }
    }
}
