//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Opc.Classic .NET Contributors
//
// Phase 4A.6b — call-shim emission scaffold.
//

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Opc.Classic.Generators;

/// <summary>
/// Source generator that handles <c>[GenerateOpcProxy]</c>-annotated partial
/// OPC interface projections. Emits a sibling client proxy scaffold whose
/// method bodies are filled in by later NDR marshaling phases.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OpcProxyGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "Opc.Classic.Generators";
    private const string AttributeName = "GenerateOpcProxyAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;
    private const string OpcInterfaceAttributeFullName = AttributeNamespace + ".OpcInterfaceAttribute";
    private const string OpcMethodAttributeFullName = AttributeNamespace + ".OpcMethodAttribute";
    private const string OpcGenerateMultiOutRecordAttributeFullName = AttributeNamespace + ".OpcGenerateMultiOutRecordAttribute";
    private const string OpcUniquePointerAttributeFullName = AttributeNamespace + ".OpcUniquePointerAttribute";
    private const string OpcEmitArrayCountAttributeFullName = AttributeNamespace + ".OpcEmitArrayCountAttribute";
    private const string OpcDeferredElementsAttributeFullName = AttributeNamespace + ".OpcDeferredElementsAttribute";

    private const string AttributeSource = @"// <auto-generated by Opc.Classic.Generators.OpcProxyGenerator />
#nullable enable

namespace Opc.Classic.Generators
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class GenerateOpcProxyAttribute : global::System.Attribute { }

    /// <summary>
    /// Marks a method parameter as an NDR unique pointer (per DCE 1.1 NDR /
    /// MS-RPCE §2.2.5). The generator emits a 4-byte referent ID before the
    /// value on the wire: 0 for null/absent, 0x00020000 for present. This is
    /// the NDR shape for IDL [unique, in] T* parameters. Apply explicitly when
    /// the C# parameter type cannot carry the unique-pointer hint via
    /// nullability (e.g. when the parameter is a non-nullable struct, or a
    /// string with no null-distinguishing convention).
    ///
    /// Nullable value types (int?, float?, Guid?) imply this automatically.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.ReturnValue, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcUniquePointerAttribute : global::System.Attribute { }

    /// <summary>
    /// Marks an [in] array parameter as carrying a separate explicit
    /// <c>[in] DWORD N</c> sibling count field that the generator must emit
    /// before the array. The wire layout becomes <c>[count (4 bytes)] [array
    /// max_count (4 bytes)] [elements]</c> — the count appears twice (once as
    /// the standalone field, once as the array's NDR conformance header),
    /// matching IDL signatures like
    /// <c>[in] DWORD dwCount, [in, size_is(dwCount)] T* arr</c> (used by
    /// IOPCItemIO::Read, IOPCSyncIO::Read, IOPCItemMgt::AddItems, etc.).
    /// Apply to the FIRST array among siblings that share the same dwCount;
    /// subsequent siblings encode normally with just their max_count prefix.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcEmitArrayCountAttribute : global::System.Attribute { }

    /// <summary>
    /// Marks an array parameter whose ELEMENTS are themselves unique pointers
    /// (e.g. <c>LPCWSTR* pszItems</c> under <c>pointer_default(unique)</c>) as
    /// requiring the DCE 1.1 §14.3.12.3 deferred-pointer-pile layout:
    /// the array's max_count is followed by a per-element referent ID for
    /// each element, then (in deferred pre-order) the pointed-to bodies for
    /// each non-null element. The current generator implements this for
    /// <c>string[]</c> only — bodies use the conformant-varying LPWSTR layout
    /// (no NDR referent prefix since the referent was already written in the
    /// inline pass).
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcDeferredElementsAttribute : global::System.Attribute { }
}
";

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly SymbolDisplayFormat CodecTypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            (SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
             SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier) &
            ~SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly CodecEmitter AeServerStatusCodec = StaticCodec(
        "global::Opc.Classic.Ae.Ndr.NdrOpcEventServerStatusCodec");

    private static readonly CodecEmitter HdaServerStatusCodec = StaticCodec(
        "global::Opc.Classic.Hda.Ndr.NdrOpcHdaServerStatusCodec");

    private static readonly Dictionary<string, CodecEmitter> Codecs =
        new(System.StringComparer.Ordinal)
        {
            { "global::System.Int32", new CodecEmitter("{Writer}.WriteInt32({Param})", "{Reader}.ReadInt32()") },
            { "global::System.UInt32", new CodecEmitter("{Writer}.WriteUInt32({Param})", "{Reader}.ReadUInt32()") },
            { "global::System.Int16", new CodecEmitter("{Writer}.WriteInt16({Param})", "{Reader}.ReadInt16()") },
            { "global::System.UInt16", new CodecEmitter("{Writer}.WriteUInt16({Param})", "{Reader}.ReadUInt16()") },
            { "global::System.Int64", new CodecEmitter("{Writer}.WriteInt64({Param})", "{Reader}.ReadInt64()") },
            { "global::System.UInt64", new CodecEmitter("{Writer}.WriteUInt64({Param})", "{Reader}.ReadUInt64()") },
            { "global::System.Single", new CodecEmitter("{Writer}.WriteSingle({Param})", "{Reader}.ReadSingle()") },
            { "global::System.Double", new CodecEmitter("{Writer}.WriteDouble({Param})", "{Reader}.ReadDouble()") },
            { "global::System.Boolean", new CodecEmitter("{Writer}.WriteInt32({Param} ? -1 : 0)", "({Reader}.ReadInt32() != 0)") },
            { "global::System.Guid", new CodecEmitter("{Writer}.WriteGuid({Param})", "{Reader}.ReadGuid()") },
            { "global::Opc.Classic.Dcom.IOpcInterfaceRef", new CodecEmitter("global::Opc.Classic.Dcom.OpcInterfaceRefCodec.Write(ref {Writer}, {Param})", "global::Opc.Classic.Dcom.OpcInterfaceRefCodec.Read(ref {Reader})") },
            { "global::Opc.Classic.Dcom.OpcRemQIResult", StaticCodec("global::Opc.Classic.Dcom.NdrRemQIResultCodec") },
            { "global::System.String", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "global::System.String?", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "string", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "string?", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "global::Opc.Classic.OpcVariant", new CodecEmitter("global::Opc.Classic.Ndr.NdrVariantExtensions.WriteVariant(ref {Writer}, {Param})", "global::Opc.Classic.Ndr.NdrVariantExtensions.ReadVariant(ref {Reader})") },
            { "global::Opc.Classic.OpcSafeArray", new CodecEmitter("global::Opc.Classic.Ndr.NdrSafeArrayExtensions.WriteSafeArray(ref {Writer}, {Param})", "global::Opc.Classic.Ndr.NdrSafeArrayExtensions.ReadSafeArray(ref {Reader})") },
            { "global::Opc.Classic.OpcServerStatus", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcServerStatusCodec") },
            { "global::Opc.Classic.Da.OpcBrowseElementResult", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcBrowseElementCodec") },
            { "global::Opc.Classic.Da.OpcItemAttributes", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemAttributesCodec") },
            { "global::Opc.Classic.Da.OpcItemDef", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemDefCodec") },
            { "global::Opc.Classic.Da.OpcGroupState", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcGroupStateCodec") },
            { "global::Opc.Classic.Da.OpcItemProperties", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemPropertiesCodec") },
            { "global::Opc.Classic.Da.OpcItemPropertyResult", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemPropertyCodec") },
            { "global::Opc.Classic.Da.OpcItemResult", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemResultCodec") },
            { "global::Opc.Classic.Da.OpcItemState", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemStateCodec") },
            { "global::Opc.Classic.Da.OpcItemVqt", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemVqtCodec") },
            { "global::Opc.Classic.Ae.OpcConditionState", StaticCodec("global::Opc.Classic.Ae.Ndr.NdrOpcConditionStateCodec") },
            { "global::Opc.Classic.Ae.OpcEventNotification", StaticCodec("global::Opc.Classic.Ae.Ndr.NdrOpcEventNotificationCodec") },
            { "global::Opc.Classic.Batch.OpcBatchSummary", StaticCodec("global::Opc.Classic.Batch.Ndr.NdrOpcBatchSummaryCodec") },
            { "global::Opc.Classic.Batch.OpcBatchSummaryFilter", StaticCodec("global::Opc.Classic.Batch.Ndr.NdrOpcBatchSummaryFilterCodec") },
            { "global::Opc.Classic.Hda.OpcHdaAnnotation", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaAnnotationCodec") },
            { "global::Opc.Classic.Hda.OpcHdaAttribute", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaAttributeCodec") },
            { "global::Opc.Classic.Hda.OpcHdaItem", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaItemCodec") },
            { "global::Opc.Classic.Hda.OpcHdaModifiedItem", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaModifiedItemCodec") },
            { "global::Opc.Classic.Hda.OpcHdaTime", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaTimeCodec") },
        };

    private const string DiagnosticCategory = "Opc.Classic.Generators";
    private const string DiagnosticsHelpLinkUri = "docs/generators/diagnostics.md";

    private static readonly DiagnosticDescriptor NotPartialDescriptor = new(
        id: "OPCGEN004",
        title: "OpcProxy target must be partial",
        messageFormat: "Interface '{0}' is decorated with [GenerateOpcProxy] but is not declared partial",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor MissingOpcInterfaceDescriptor = new(
        id: "OPCGEN005",
        title: "OpcProxy target should be decorated with OpcInterface",
        messageFormat: "Interface '{0}' is decorated with [GenerateOpcProxy] but is not decorated with [OpcInterface]",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor OpcMethodRefOutDescriptor = new(
        id: "OPCGEN006",
        title: "OpcMethod has unsupported ref/out parameter type",
        messageFormat: "Method '{0}' has ref/out OPC method type '{1}' without a registered request/response codec",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor UnsupportedSignatureDescriptor = new(
        id: "OPCGEN007",
        title: "OpcMethod has unsupported method signature",
        messageFormat: "Method '{0}' is marked [OpcMethod] but has an unsupported signature: {1}",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor UnsupportedMarshallingDescriptor = new(
        id: "OPCGEN008",
        title: "OpcMethod has unsupported parameter or return type",
        messageFormat: "Method '{0}' uses unsupported OPC method type '{1}'; emitting empty-payload placeholder body",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor MissingCodecDescriptor = new(
        id: "OPCGEN009",
        title: "OPC method type is missing a codec",
        messageFormat: "Method '{0}' uses OPC method type '{1}' but no codec is registered in the generator codec registry",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor UnsupportedParameterDescriptor = new(
        id: "OPCGEN010",
        title: "OpcMethod has unsupported parameter type",
        messageFormat: "Method '{0}' has unsupported parameter '{1}' of OPC method type '{2}'",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: "GenerateOpcProxyAttribute.g.cs",
                sourceText: SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: AttributeFullName,
            predicate: static (node, _) => node is InterfaceDeclarationSyntax,
            transform: static (ctx, _) => Transform(ctx));

        context.RegisterSourceOutput(candidates, Emit);
    }

    private static InterfaceModel? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (ctx.TargetNode is not InterfaceDeclarationSyntax syntax)
        {
            return null;
        }

        bool isPartial = false;
        foreach (var modifier in syntax.Modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword))
            {
                isPartial = true;
                break;
            }
        }

        return new InterfaceModel(
            fullyQualifiedName: symbol.ToDisplayString(TypeDisplayFormat),
            @namespace: symbol.ContainingNamespace?.IsGlobalNamespace == false
                ? symbol.ContainingNamespace!.ToDisplayString()
                : null,
            name: symbol.Name,
            accessibility: symbol.DeclaredAccessibility,
            typeParameterList: TypeParameterList(symbol.TypeParameters),
            typeParameterConstraints: ConstraintClauses(symbol.TypeParameters),
            isPartial: isPartial,
            hasOpcInterfaceAttribute: HasOpcInterfaceAttribute(symbol),
            location: syntax.Identifier.GetLocation(),
            methods: CollectMethods(symbol));
    }

    private static ImmutableArray<MethodModel> CollectMethods(INamedTypeSymbol interfaceSymbol)
    {
        var builder = ImmutableArray.CreateBuilder<MethodModel>();
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol { MethodKind: MethodKind.Ordinary } method)
            {
                builder.Add(CreateMethodModel(method));
            }
        }

        return builder.ToImmutable();
    }

    private static MethodModel CreateMethodModel(IMethodSymbol method)
    {
        var outParameters = ImmutableArray.CreateBuilder<string>();
        var parameterNames = ImmutableArray.CreateBuilder<string>();
        var parameters = ImmutableArray.CreateBuilder<ParameterModel>();
        string? cancellationTokenParameterName = null;
        bool hasRefOrOutParameter = false;
        int outParameterCount = 0;
        foreach (var parameter in method.Parameters)
        {
            parameterNames.Add(parameter.Name);
            if (parameter.RefKind == RefKind.Out || parameter.RefKind == RefKind.Ref)
            {
                outParameters.Add(EscapeIdentifier(parameter.Name));
                hasRefOrOutParameter = true;
                if (parameter.RefKind == RefKind.Out) { outParameterCount++; }
            }
            bool isCancellationToken = string.Equals(parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::System.Threading.CancellationToken", System.StringComparison.Ordinal);
            if (cancellationTokenParameterName is null && isCancellationToken) { cancellationTokenParameterName = EscapeIdentifier(parameter.Name); }

            // Detect NDR unique-pointer shape per DCE 1.1 §14.3.10.
            DetectUniquePointer(parameter, out bool isUniquePointer, out string? underlyingValueType);
            bool emitArrayCount = HasEmitArrayCountAttribute(parameter);
            bool deferredElements = HasDeferredElementsAttribute(parameter);

            parameters.Add(new ParameterModel(
                EscapeIdentifier(parameter.Name),
                ToPascalCase(parameter.Name),
                parameter.Type.ToDisplayString(TypeDisplayFormat),
                parameter.Type.ToDisplayString(CodecTypeDisplayFormat),
                isCancellationToken,
                parameter.RefKind,
                IsOpcInterfaceType(parameter.Type),
                isUniquePointer,
                underlyingValueType,
                emitArrayCount,
                deferredElements));
        }
        var taskReturnKind = ClassifyTaskReturn(method.ReturnType, out string? taskResultType, out string? taskResultMarshallingType);
        bool taskResultIsOpcInterface = TryGetTaskResultSymbol(method.ReturnType, out var taskResultSymbol) && IsOpcInterfaceType(taskResultSymbol);
        bool taskResultIsUniquePointer = HasReturnUniquePointerAttribute(method);
        string? declaringNamespace = ContainingNamespace(method.ContainingType);
        string? unsupportedSignatureReason = UnsupportedSignatureReason(method, taskReturnKind);
        string? unsupportedMarshallingType = FindUnsupportedMarshallingType(parameters, taskReturnKind, taskResultMarshallingType, taskResultIsOpcInterface, declaringNamespace, out string? unsupportedRefOutMarshallingType, out UnsupportedMarshallingKind unsupportedMarshallingKind, out string? unsupportedParameterName);
        return new MethodModel(method.Name, method.ReturnType.ToDisplayString(TypeDisplayFormat), TypeParameterList(method.TypeParameters), ParameterList(method.Parameters), ConstraintClauses(method.TypeParameters), outParameters.ToImmutable(), parameterNames.ToImmutable(), parameters.ToImmutable(), HasOpcMethodAttribute(method), hasRefOrOutParameter, HasGenerateMultiOutRecordAttribute(method) || outParameterCount >= 2, taskReturnKind, taskResultType, taskResultMarshallingType, taskResultIsOpcInterface, taskResultIsUniquePointer, unsupportedMarshallingType, unsupportedRefOutMarshallingType, unsupportedMarshallingKind, unsupportedParameterName, unsupportedSignatureReason, cancellationTokenParameterName, declaringNamespace, method.Locations.IsDefaultOrEmpty ? Location.None : method.Locations[0]);
    }

    private static bool HasReturnUniquePointerAttribute(IMethodSymbol method)
    {
        foreach (var attr in method.GetReturnTypeAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcUniquePointerAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static void DetectUniquePointer(IParameterSymbol parameter, out bool isUniquePointer, out string? underlyingValueType)
    {
        isUniquePointer = false;
        underlyingValueType = null;
        if (parameter.Type is INamedTypeSymbol namedType
            && namedType.IsGenericType
            && namedType.OriginalDefinition is { } orig
            && string.Equals(orig.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::System.Nullable<T>", System.StringComparison.Ordinal)
            && namedType.TypeArguments.Length == 1)
        {
            isUniquePointer = true;
            underlyingValueType = namedType.TypeArguments[0].ToDisplayString(CodecTypeDisplayFormat);
        }
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcUniquePointerAttributeFullName, System.StringComparison.Ordinal))
            {
                isUniquePointer = true;
            }
        }
    }

    private static bool HasEmitArrayCountAttribute(IParameterSymbol parameter)
    {
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcEmitArrayCountAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasDeferredElementsAttribute(IParameterSymbol parameter)
    {
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcDeferredElementsAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static string? ContainingNamespace(INamedTypeSymbol symbol) =>
        symbol.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingNamespace!.ToDisplayString()
            : null;

    private static void Emit(SourceProductionContext spc, InterfaceModel? maybeModel)
    {
        if (maybeModel is null)
        {
            return;
        }

        InterfaceModel model = maybeModel;

        if (!model.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(NotPartialDescriptor, model.Location, model.FullyQualifiedName));
            return;
        }

        if (!model.HasOpcInterfaceAttribute)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingOpcInterfaceDescriptor, model.Location, model.FullyQualifiedName));
        }

        var sb = new StringBuilder(1024);
        sb.AppendLine("// <auto-generated by Opc.Classic.Generators.OpcProxyGenerator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0414 // _channel is captured now and read by later call-shim phases.");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        string indent = hasNamespace ? "    " : string.Empty;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string accessibility = AccessibilityKeyword(model.Accessibility);
        EmitMultiOutRecordTypes(sb, indent, model);

        string proxyName = model.Name + "ClientProxy";
        sb.Append(indent).Append(accessibility).Append(" partial class ").Append(proxyName).Append(model.TypeParameterList)
            .Append(" : ").Append(model.Name).Append(model.TypeParameterList).Append(model.TypeParameterConstraints).AppendLine();
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    private readonly global::Opc.Classic.ICallChannel _channel;");
        sb.AppendLine();
        sb.Append(indent).Append("    public ").Append(proxyName).Append("(global::Opc.Classic.ICallChannel channel)").AppendLine();
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        _channel = channel ?? throw new global::System.ArgumentNullException(nameof(channel));");
        sb.Append(indent).AppendLine("    }");

        EmitMethods(spc, sb, indent, model);

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        string hint = model.FullyQualifiedName.Replace("global::", string.Empty).Replace("<", "_").Replace(">", "_") + ".OpcProxy.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMultiOutRecordTypes(StringBuilder sb, string indent, InterfaceModel model)
    {
        var emitted = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var method in model.Methods)
        {
            if (!method.GenerateMultiOutRecord || !emitted.Add(method.MultiOutRecordName))
            {
                continue;
            }

            sb.Append(indent).Append("public sealed record ").Append(method.MultiOutRecordName).Append('(');
            bool first = true;
            if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
            {
                AppendRecordParameter(sb, ref first, method.TaskResultType!, "ReturnValue");
            }

            foreach (var parameter in method.Parameters)
            {
                if (parameter.IsResponseValue)
                {
                    AppendRecordParameter(sb, ref first, parameter.DeclaredType, parameter.ResultMemberName);
                }
            }

            sb.AppendLine(");");
            sb.AppendLine();
        }
    }

    private static void AppendRecordParameter(StringBuilder sb, ref bool first, string typeName, string memberName)
    {
        if (!first)
        {
            sb.Append(", ");
        }

        sb.Append(typeName).Append(' ').Append(memberName);
        first = false;
    }

    private static void EmitMethods(SourceProductionContext spc, StringBuilder sb, string indent, InterfaceModel model)
    {
        foreach (var method in model.Methods)
        {
            if (method.HasOpcMethodAttribute)
            {
                if (method.UnsupportedSignatureReason is not null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedSignatureDescriptor,
                        method.Location,
                        method.Name,
                        method.UnsupportedSignatureReason));
                }

                if (method.UnsupportedRefOutMarshallingType is not null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        OpcMethodRefOutDescriptor,
                        method.Location,
                        method.Name,
                        method.UnsupportedRefOutMarshallingType));
                }
                else if (method.UnsupportedSignatureReason is null &&
                    method.TaskReturnKind != TaskReturnKind.Unsupported &&
                    !method.IsFullyMarshallable)
                {
                    if (method.UnsupportedMarshallingKind == UnsupportedMarshallingKind.Parameter &&
                        method.UnsupportedParameterName is not null)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            UnsupportedParameterDescriptor,
                            method.Location,
                            method.Name,
                            method.UnsupportedParameterName,
                            method.UnsupportedMarshallingType ?? "<unknown>"));
                    }
                    else if (method.UnsupportedMarshallingKind == UnsupportedMarshallingKind.Return)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            MissingCodecDescriptor,
                            method.Location,
                            method.Name,
                            method.UnsupportedMarshallingType ?? "<unknown>"));
                    }

                    spc.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedMarshallingDescriptor,
                        method.Location,
                        method.Name,
                        method.UnsupportedMarshallingType ?? "<unknown>"));
                }
            }

            EmitMethod(sb, indent, model.Name, model.FullyQualifiedName, method);
        }
    }

    private static void EmitMethod(StringBuilder sb, string indent, string interfaceName, string fullyQualifiedInterfaceName, MethodModel method)
    {
        bool emitInvokeBody = method.HasOpcMethodAttribute &&
            method.TaskReturnKind != TaskReturnKind.Unsupported &&
            method.UnsupportedSignatureReason is null;

        sb.AppendLine();
        sb.Append(indent).Append("    public ");
        if (emitInvokeBody && !method.IsFullyMarshallable && !method.HasRefOrOutParameter)
        {
            sb.Append("async ");
        }

        sb.Append(method.ReturnType).Append(' ').Append(method.Name)
            .Append(method.TypeParameterList).Append('(').Append(method.ParameterList).Append(')')
            .Append(method.ConstraintClauses).AppendLine();
        sb.Append(indent).AppendLine("    {");

        if (!emitInvokeBody)
        {
            EmitNotImplementedBody(sb, indent, interfaceName, method);
            sb.Append(indent).AppendLine("    }");
            return;
        }

        EmitInvokeAsyncBody(sb, indent, fullyQualifiedInterfaceName, method);
        sb.Append(indent).AppendLine("    }");
    }

    private static void EmitNotImplementedBody(StringBuilder sb, string indent, string interfaceName, MethodModel method)
    {
        foreach (var parameter in method.Parameters)
        {
            if (parameter.RefKind == RefKind.Out)
            {
                sb.Append(indent).Append("        ").Append(parameter.Name).AppendLine(" = default!;");
            }
        }

        sb.Append(indent).Append("        throw new global::System.NotImplementedException(")
            .Append("\"Phase 6B/7B/8B - per-method shim for '").Append(interfaceName).Append('.')
            .Append(method.Name).Append("' TBD\");").AppendLine();
    }

    private static void EmitInvokeAsyncBody(StringBuilder sb, string indent, string fullyQualifiedInterfaceName, MethodModel method)
    {
        if (method.IsFullyMarshallable)
        {
            EmitMarshalledInvokeAsyncBody(sb, indent, fullyQualifiedInterfaceName, method);
            return;
        }

        if (method.HasRefOrOutParameter)
        {
            EmitUnsupportedRefOutBody(sb, indent, method);
            return;
        }

        if (method.HasRefOrOutParameter)
        {
            EmitUnsupportedRefOutBody(sb, indent, method);
            return;
        }
        EmitEmptyPayloadInvokeAsyncBody(sb, indent, fullyQualifiedInterfaceName, method);
    }

    private static void EmitEmptyPayloadInvokeAsyncBody(StringBuilder sb, string indent, string fullyQualifiedInterfaceName, MethodModel method)
    {
        string cancellationTokenLocal = UniqueLocalName(method.ParameterNames, "__opcCancellationToken");
        string resultLocal = UniqueLocalName(method.ParameterNames, "__opcResult", cancellationTokenLocal);
        string cancellationTokenValue = method.CancellationTokenParameterName ?? "global::System.Threading.CancellationToken.None";

        sb.Append(indent).Append("        var ").Append(cancellationTokenLocal).Append(" = ").Append(cancellationTokenValue).AppendLine(";");
        sb.Append(indent).Append("        var ").Append(resultLocal).AppendLine(" = await _channel.InvokeAsync(");
        sb.Append(indent).Append("            ").Append(fullyQualifiedInterfaceName).AppendLine(".InterfaceId,");
        sb.Append(indent).Append("            ").Append(fullyQualifiedInterfaceName).Append(".Opnums.").Append(method.Name).AppendLine(",");
        sb.Append(indent).AppendLine("            global::System.ReadOnlyMemory<byte>.Empty,");
        sb.Append(indent).Append("            ").Append(cancellationTokenLocal).AppendLine(").ConfigureAwait(false);");
        EmitFailureCheck(sb, indent, resultLocal);

        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            sb.Append(indent).Append("        // Unsupported OPC method type '").Append(method.UnsupportedMarshallingType ?? "<unknown>")
                .AppendLine("'; Phase 6B emits the empty-payload placeholder.");
            sb.Append(indent).AppendLine("        return default!;");
        }
        else
        {
            sb.Append(indent).Append("        // Unsupported OPC method type '").Append(method.UnsupportedMarshallingType ?? "<unknown>")
                .AppendLine("'; Phase 6B emits the empty-payload placeholder.");
        }
    }

    private static void EmitUnsupportedRefOutBody(StringBuilder sb, string indent, MethodModel method)
    {
        foreach (var parameter in method.Parameters)
        {
            if (parameter.RefKind == RefKind.Out)
            {
                sb.Append(indent).Append("        ").Append(parameter.Name).AppendLine(" = default!;");
            }
        }

        sb.Append(indent).Append("        // Unsupported OPC ref/out method type '").Append(method.UnsupportedRefOutMarshallingType ?? "<unknown>")
            .AppendLine("'; emitting a completed placeholder task.");
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            sb.Append(indent).AppendLine("        return global::System.Threading.Tasks.Task.FromResult(default!);");
        }
        else
        {
            sb.Append(indent).AppendLine("        return global::System.Threading.Tasks.Task.CompletedTask;");
        }
    }

    private static void EmitMarshalledInvokeAsyncBody(StringBuilder sb, string indent, string fullyQualifiedInterfaceName, MethodModel method)
    {
        string cancellationTokenLocal = UniqueLocalName(method.ParameterNames, "__opcCancellationToken");
        string bufferLocal = UniqueLocalName(method.ParameterNames, "__opcBuffer", cancellationTokenLocal);
        string payloadLocal = UniqueLocalName(method.ParameterNames, "__opcPayload", cancellationTokenLocal, bufferLocal);
        string writerLocal = UniqueLocalName(method.ParameterNames, "__opcWriter", cancellationTokenLocal, bufferLocal, payloadLocal);
        string channelLocal = UniqueLocalName(method.ParameterNames, "__opcChannel", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal);
        string resultLocal = UniqueLocalName(method.ParameterNames, "__opcResult", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal);
        string responsePayloadLocal = UniqueLocalName(method.ParameterNames, "__opcResponsePayload", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal, resultLocal);
        string responseSpanLocal = UniqueLocalName(method.ParameterNames, "__opcResponseSpan", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal, resultLocal, responsePayloadLocal);
        string readerLocal = UniqueLocalName(method.ParameterNames, "__opcReader", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal, resultLocal, responsePayloadLocal, responseSpanLocal);
        string decodedLocal = UniqueLocalName(method.ParameterNames, "__opcDecoded", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal, resultLocal, responsePayloadLocal, responseSpanLocal, readerLocal);
        string cancellationTokenValue = method.CancellationTokenParameterName ?? "global::System.Threading.CancellationToken.None";

        EmitEncodeAndInvokeReturn(sb, indent, method, cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, cancellationTokenValue, decodedLocal);
        sb.AppendLine();
        EmitInvokeCoreLocalFunction(sb, indent, fullyQualifiedInterfaceName, method, channelLocal, payloadLocal, bufferLocal, cancellationTokenLocal, resultLocal);
        if (ResponseItemCount(method) > 0)
        {
            sb.AppendLine();
            EmitDecodeResponseLocalFunction(sb, indent, method, responsePayloadLocal, responseSpanLocal, readerLocal);
        }
    }

    private static void EmitEncodeAndInvokeReturn(StringBuilder sb, string indent, MethodModel method, string cancellationTokenLocal, string bufferLocal, string payloadLocal, string writerLocal, string cancellationTokenValue, string decodedLocal)
    {
        string coreStartedLocal = UniqueLocalName(method.ParameterNames, "__opcCoreStarted", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, decodedLocal);
        sb.Append(indent).Append("        var ").Append(cancellationTokenLocal).Append(" = ").Append(cancellationTokenValue).AppendLine(";");
        sb.Append(indent).Append("        var ").Append(bufferLocal).AppendLine(" = global::System.Buffers.ArrayPool<byte>.Shared.Rent(1024);");
        if (method.HasRefOrOutParameter) { sb.Append(indent).Append("        var ").Append(coreStartedLocal).AppendLine(" = false;"); }
        sb.Append(indent).AppendLine("        try"); sb.Append(indent).AppendLine("        {"); sb.Append(indent).Append("            global::System.ReadOnlyMemory<byte> ").Append(payloadLocal).AppendLine(";"); sb.Append(indent).AppendLine("            {");
        sb.Append(indent).Append("                var ").Append(writerLocal).Append(" = new global::Opc.Classic.Ndr.NdrWriter(new global::System.Span<byte>(").Append(bufferLocal).AppendLine(", 0, 1024));");
        foreach (var parameter in method.Parameters) { if (parameter.IsRequestValue) { EmitCodecWrite(sb, indent, writerLocal, parameter, method); } }
        sb.Append(indent).Append("                ").Append(payloadLocal).Append(" = new global::System.ReadOnlyMemory<byte>(").Append(bufferLocal).Append(", 0, ").Append(writerLocal).AppendLine(".Position);"); sb.Append(indent).AppendLine("            }");
        if (method.HasRefOrOutParameter) { sb.Append(indent).Append("            ").Append(coreStartedLocal).AppendLine(" = true;"); sb.Append(indent).Append("            var ").Append(decodedLocal).Append(" = ").Append(InvokeCoreName(method)).Append("(_channel, ").Append(payloadLocal).Append(", ").Append(bufferLocal).Append(", ").Append(cancellationTokenLocal).AppendLine(").GetAwaiter().GetResult();"); EmitResponseParameterAssignments(sb, indent, method, decodedLocal); EmitPublicTaskReturn(sb, indent, method, decodedLocal); }
        else { sb.Append(indent).Append("            return ").Append(InvokeCoreName(method)).Append("(_channel, ").Append(payloadLocal).Append(", ").Append(bufferLocal).Append(", ").Append(cancellationTokenLocal).AppendLine(");"); }
        sb.Append(indent).AppendLine("        }"); sb.Append(indent).AppendLine("        catch"); sb.Append(indent).AppendLine("        {");
        if (method.HasRefOrOutParameter) { sb.Append(indent).Append("            if (!").Append(coreStartedLocal).AppendLine(")"); sb.Append(indent).AppendLine("            {"); sb.Append(indent).Append("                global::System.Buffers.ArrayPool<byte>.Shared.Return(").Append(bufferLocal).AppendLine(");"); sb.Append(indent).AppendLine("            }"); } else { sb.Append(indent).Append("            global::System.Buffers.ArrayPool<byte>.Shared.Return(").Append(bufferLocal).AppendLine(");"); }
        sb.Append(indent).AppendLine("            throw;"); sb.Append(indent).AppendLine("        }");
    }

    private static void EmitInvokeCoreLocalFunction(
        StringBuilder sb,
        string indent,
        string fullyQualifiedInterfaceName,
        MethodModel method,
        string channelLocal,
        string payloadLocal,
        string bufferLocal,
        string cancellationTokenLocal,
        string resultLocal)
    {
        EmitInvokeCoreSignature(sb, indent, method);
        sb.Append(indent).Append("            global::Opc.Classic.ICallChannel ").Append(channelLocal).AppendLine(",");
        sb.Append(indent).Append("            global::System.ReadOnlyMemory<byte> ").Append(payloadLocal).AppendLine(",");
        sb.Append(indent).Append("            byte[] ").Append(bufferLocal).AppendLine(",");
        sb.Append(indent).Append("            global::System.Threading.CancellationToken ").Append(cancellationTokenLocal).AppendLine(")");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            try");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).Append("                var ").Append(resultLocal).Append(" = await ").Append(channelLocal).AppendLine(".InvokeAsync(");
        sb.Append(indent).Append("                    ").Append(fullyQualifiedInterfaceName).AppendLine(".InterfaceId,");
        sb.Append(indent).Append("                    ").Append(fullyQualifiedInterfaceName).Append(".Opnums.").Append(method.Name).AppendLine(",");
        sb.Append(indent).Append("                    ").Append(payloadLocal).AppendLine(",");
        sb.Append(indent).Append("                    ").Append(cancellationTokenLocal).AppendLine(").ConfigureAwait(false);");
        EmitFailureCheck(sb, indent + "        ", resultLocal);
        if (ResponseItemCount(method) > 0)
        {
            sb.Append(indent).Append("                return ").Append(DecodeResponseName(method)).Append('(').Append(resultLocal).AppendLine(".ResponsePayload);");
        }

        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("            finally");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).Append("                global::System.Buffers.ArrayPool<byte>.Shared.Return(").Append(bufferLocal).AppendLine(");");
        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("        }");
    }

    private static void EmitInvokeCoreSignature(StringBuilder sb, string indent, MethodModel method)
    {
        sb.Append(indent).Append("        static async "); if (ResponseItemCount(method) > 0) { sb.Append("global::System.Threading.Tasks.Task<").Append(ResponseValueType(method)).Append('>'); } else { sb.Append("global::System.Threading.Tasks.Task"); } sb.Append(' ').Append(InvokeCoreName(method)).AppendLine("(");
    }
    private static void EmitDecodeResponseLocalFunction(StringBuilder sb, string indent, MethodModel method, string responsePayloadLocal, string responseSpanLocal, string readerLocal)
    {
        sb.Append(indent).Append("        static ").Append(ResponseValueType(method)).Append(' ').Append(DecodeResponseName(method)).Append("(global::System.ReadOnlyMemory<byte> ").Append(responsePayloadLocal).AppendLine(")"); sb.Append(indent).AppendLine("        {"); sb.Append(indent).Append("            var ").Append(responseSpanLocal).Append(" = ").Append(responsePayloadLocal).AppendLine(".Span;"); sb.Append(indent).Append("            var ").Append(readerLocal).Append(" = new global::Opc.Classic.Ndr.NdrReader(").Append(responseSpanLocal).AppendLine(");"); EmitCodecReadResponse(sb, indent, readerLocal, method, responsePayloadLocal, responseSpanLocal); sb.Append(indent).AppendLine("        }");
    }
    private static string InvokeCoreName(MethodModel method) => "__opcInvoke" + method.Name + "CoreAsync";

    private static string DecodeResponseName(MethodModel method) => "__opcDecode" + method.Name + "Response";

    private static void EmitFailureCheck(StringBuilder sb, string indent, string resultLocal)
    {
        sb.Append(indent).Append("        if (").Append(resultLocal).AppendLine(".IsFailure)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            throw new global::Opc.Classic.OpcException(new global::Opc.Classic.OpcResultId(")
            .Append(resultLocal).AppendLine(".Hresult, null));");
        sb.Append(indent).AppendLine("        }");
    }

    private static string? FindUnsupportedMarshallingType(
        IEnumerable<ParameterModel> parameters,
        TaskReturnKind taskReturnKind,
        string? taskResultMarshallingType,
        bool taskResultIsOpcInterface,
        string? declaringNamespace,
        out string? unsupportedRefOutMarshallingType,
        out UnsupportedMarshallingKind unsupportedMarshallingKind,
        out string? unsupportedParameterName)
    {
        unsupportedRefOutMarshallingType = null;
        unsupportedMarshallingKind = UnsupportedMarshallingKind.None;
        unsupportedParameterName = null;
        foreach (var parameter in parameters)
        {
            if (parameter.IsCancellationToken)
            {
                continue;
            }

            if (parameter.IsRequestValue && !CanWriteType(parameter.MarshallingType, parameter.IsOpcInterface, declaringNamespace))
            {
                // Unique-pointer parameters (Nullable<T> or [OpcUniquePointer]) are
                // accepted as long as the underlying value type has a codec; the
                // pointer wrapping is handled by the emitter.
                if (parameter.IsUniquePointer
                    && parameter.UnderlyingValueType is { } underlying
                    && CanWriteType(underlying, isOpcInterface: false, declaringNamespace))
                {
                    continue;
                }

                if (parameter.RefKind == RefKind.Ref || parameter.RefKind == RefKind.Out)
                {
                    unsupportedRefOutMarshallingType = parameter.MarshallingType;
                    return null;
                }

                unsupportedMarshallingKind = UnsupportedMarshallingKind.Parameter;
                unsupportedParameterName = parameter.Name;
                return parameter.MarshallingType;
            }

            if (parameter.IsResponseValue && !CanReadType(parameter.MarshallingType, parameter.IsOpcInterface, declaringNamespace))
            {
                unsupportedRefOutMarshallingType = parameter.MarshallingType;
                return null;
            }
        }

        if (taskReturnKind == TaskReturnKind.TaskOfT &&
            (taskResultMarshallingType is null || !CanReadType(taskResultMarshallingType, taskResultIsOpcInterface, declaringNamespace)))
        {
            unsupportedMarshallingKind = UnsupportedMarshallingKind.Return;
            return taskResultMarshallingType ?? "<unknown>";
        }

        return null;
    }
    private static void EmitCodecWrite(
        StringBuilder sb,
        string indent,
        string writerLocal,
        ParameterModel parameter,
        MethodModel method)
    {
        string statementIndent = indent + "                ";

        if (parameter.IsUniquePointer && TryEmitUniquePointerWrite(sb, statementIndent, writerLocal, parameter, method))
        {
            return;
        }

        if (TryGetCodec(parameter.MarshallingType, method.DeclaringNamespace, out var codec))
        {
            if (codec.IsArray)
            {
                // [in] DWORD N + [in, size_is(N)] T* arr — emit the standalone
                // count field BEFORE the array's own NDR max_count prefix.
                if (parameter.EmitArrayCount)
                {
                    sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32((uint)(").Append(parameter.Name).AppendLine("?.Length ?? 0));");
                }

                if (parameter.IsUniquePointer)
                {
                    sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32(").Append(parameter.Name).AppendLine(" is null ? 0u : 0x00020000u);");
                    sb.Append(statementIndent).Append("if (").Append(parameter.Name).AppendLine(" is not null)");
                    sb.Append(statementIndent).AppendLine("{");
                    EmitArrayCodecWrite(sb, statementIndent + "    ", writerLocal, parameter.Name, codec, method.ParameterNames, parameter.DeferredElements);
                    sb.Append(statementIndent).AppendLine("}");
                    return;
                }
                EmitArrayCodecWrite(sb, statementIndent, writerLocal, parameter.Name, codec, method.ParameterNames, parameter.DeferredElements);
                return;
            }

            sb.Append(statementIndent).Append(FormatWriteExpression(codec, writerLocal, parameter.Name)).AppendLine(";");
            return;
        }

        sb.Append(statementIndent).Append(writerLocal).AppendLine(".WriteRawBytes(global::System.ReadOnlySpan<byte>.Empty);");
    }

    /// <summary>
    /// Emits the NDR unique-pointer wire prefix + value for a parameter tagged
    /// with [OpcUniquePointer] (per DCE 1.1 §14.3.10). Handles three shapes:
    ///   - IOpcInterfaceRef → MInterfacePointer wrapping (MS-DCOM §2.2.1.10).
    ///   - Nullable&lt;T&gt; → HasValue gates the value write.
    ///   - non-nullable scalar with explicit [OpcUniquePointer] → always present.
    /// Returns true if it handled the parameter; false if no matching codec
    /// shape was found (caller falls back to the array/inline path).
    /// </summary>
    private static bool TryEmitUniquePointerWrite(
        StringBuilder sb,
        string statementIndent,
        string writerLocal,
        ParameterModel parameter,
        MethodModel method)
    {
        if (string.Equals(parameter.MarshallingType, "global::Opc.Classic.Dcom.IOpcInterfaceRef", System.StringComparison.Ordinal))
        {
            sb.Append(statementIndent).Append("global::Opc.Classic.Dcom.OpcMInterfacePointerCodec.Write(ref ").Append(writerLocal).Append(", ").Append(parameter.Name).AppendLine(");");
            return true;
        }

        string codecKey = parameter.UnderlyingValueType ?? parameter.MarshallingType;
        if (!TryGetCodec(codecKey, method.DeclaringNamespace, out var underlyingCodec) || underlyingCodec.IsArray)
        {
            return false;
        }

        if (parameter.UnderlyingValueType is not null)
        {
            sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32(").Append(parameter.Name).AppendLine(".HasValue ? 0x00020000u : 0u);");
            sb.Append(statementIndent).Append("if (").Append(parameter.Name).AppendLine(".HasValue)");
            sb.Append(statementIndent).AppendLine("{");
            sb.Append(statementIndent).Append("    ").Append(FormatWriteExpression(underlyingCodec, writerLocal, parameter.Name + ".Value")).AppendLine(";");
            sb.Append(statementIndent).AppendLine("}");
        }
        else
        {
            sb.Append(statementIndent).Append(writerLocal).AppendLine(".WriteUInt32(0x00020000u);");
            sb.Append(statementIndent).Append(FormatWriteExpression(underlyingCodec, writerLocal, parameter.Name)).AppendLine(";");
        }
        return true;
    }

    private static void EmitArrayCodecWrite(
        StringBuilder sb,
        string statementIndent,
        string writerLocal,
        string parameterName,
        CodecEmitter codec,
        ImmutableArray<string> parameterNames,
        bool deferredElements = false)
    {
        // [OpcDeferredElements] on a string[] parameter switches to the
        // C706 §14.3.12.3 two-pass layout: max_count + per-element referent
        // (no body), then per-element conformant-varying string body. This
        // is the wire shape real Windows DCOM peers expect for IDL
        // [in, size_is(N)] LPCWSTR* arrays under pointer_default(unique).
        if (deferredElements && IsStringElementCodec(codec))
        {
            string idxLocal = UniqueLocalName(parameterNames, "__opcIdx", writerLocal, parameterName);
            sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32((uint)(").Append(parameterName).AppendLine("?.Length ?? 0));");
            sb.Append(statementIndent).Append("if (").Append(parameterName).AppendLine(" is not null)");
            sb.Append(statementIndent).AppendLine("{");
            sb.Append(statementIndent).Append("    for (int ").Append(idxLocal).Append(" = 0; ").Append(idxLocal).Append(" < ").Append(parameterName).Append(".Length; ").Append(idxLocal).AppendLine("++)");
            sb.Append(statementIndent).AppendLine("    {");
            sb.Append(statementIndent).Append("        ").Append(writerLocal).Append(".WriteUInt32(").Append(parameterName).Append('[').Append(idxLocal).AppendLine("] is null ? 0u : 0x00020000u);");
            sb.Append(statementIndent).AppendLine("    }");
            sb.Append(statementIndent).Append("    for (int ").Append(idxLocal).Append(" = 0; ").Append(idxLocal).Append(" < ").Append(parameterName).Append(".Length; ").Append(idxLocal).AppendLine("++)");
            sb.Append(statementIndent).AppendLine("    {");
            sb.Append(statementIndent).Append("        if (").Append(parameterName).Append('[').Append(idxLocal).Append("] is string ").Append(idxLocal).AppendLine("Str)");
            sb.Append(statementIndent).AppendLine("        {");
            sb.Append(statementIndent).Append("            ").Append(writerLocal).Append(".WriteUnicodeString(").Append(idxLocal).AppendLine("Str);");
            sb.Append(statementIndent).AppendLine("        }");
            sb.Append(statementIndent).AppendLine("    }");
            sb.Append(statementIndent).AppendLine("}");
            return;
        }

        string itemLocal = UniqueLocalName(parameterNames, "__opcItem", writerLocal, parameterName);
        sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32((uint)(").Append(parameterName).AppendLine("?.Length ?? 0));");
        sb.Append(statementIndent).Append("if (").Append(parameterName).AppendLine(" != null)");
        sb.Append(statementIndent).AppendLine("{");
        sb.Append(statementIndent).Append("    foreach (var ").Append(itemLocal).Append(" in ").Append(parameterName).AppendLine(")");
        sb.Append(statementIndent).AppendLine("    {");
        sb.Append(statementIndent).Append("        ").Append(FormatWriteExpression(codec, writerLocal, itemLocal)).AppendLine(";");
        sb.Append(statementIndent).AppendLine("    }");
        sb.Append(statementIndent).AppendLine("}");
    }

    /// <summary>Detects the string-array codec by inspecting its element-write expression for the WriteUnicodeStringPtr inline-pointer pattern.</summary>
    private static bool IsStringElementCodec(CodecEmitter codec) =>
        codec.WriteExpression.Contains("WriteUnicodeStringPtr", System.StringComparison.Ordinal);

    private static void EmitCodecReadResponse(
        StringBuilder sb,
        string indent,
        string readerLocal,
        MethodModel method,
        string responsePayloadLocal,
        string responseSpanLocal)
    {
        string statementIndent = indent + "            ";
        int itemIndex = 0;
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            EmitCodecReadLocal(
                sb,
                statementIndent,
                readerLocal,
                method,
                method.TaskResultType!,
                method.TaskResultMarshallingType!,
                method.TaskResultIsOpcInterface,
                method.TaskResultIsUniquePointer,
                ResponseValueLocalName(itemIndex),
                responsePayloadLocal,
                responseSpanLocal);
            itemIndex++;
        }

        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsResponseValue)
            {
                continue;
            }

            EmitCodecReadLocal(
                sb,
                statementIndent,
                readerLocal,
                method,
                parameter.DeclaredType,
                parameter.MarshallingType,
                parameter.IsOpcInterface,
                parameter.IsUniquePointer,
                ResponseValueLocalName(itemIndex),
                responsePayloadLocal,
                responseSpanLocal);
            itemIndex++;
        }

        EmitDecodedResponseReturn(sb, statementIndent, method);
    }

    private static void EmitCodecReadLocal(
        StringBuilder sb,
        string statementIndent,
        string readerLocal,
        MethodModel method,
        string declaredType,
        string marshallingType,
        bool isOpcInterface,
        bool isUniquePointer,
        string targetLocal,
        string responsePayloadLocal,
        string responseSpanLocal)
    {
        if (isOpcInterface || IsOpcInterfaceRefType(marshallingType))
        {
            // [out, iid_is(riid)] LPUNKNOWN *ppUnk: a unique pointer to an
            // MInterfacePointer wrapper (MS-DCOM §2.2.1.10) containing an
            // OBJREF. Opt-in via [OpcUniquePointer] on the out/return symbol so
            // legacy "raw OBJREF on the wire" call paths (e.g. inside our
            // loopback path which doesn't yet round-trip the wrapper) continue
            // to use the unwrapped codec.
            string interfaceRead = isUniquePointer
                ? FormatMInterfacePointerReadExpression(readerLocal, declaredType)
                : FormatInterfaceReadExpression(readerLocal, declaredType);
            sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ").Append(interfaceRead).AppendLine(";");
            return;
        }

        if (TryGetCodec(marshallingType, method.DeclaringNamespace, out var codec))
        {
            if (codec.IsArray)
            {
                // [out] T** with size_is(,cIids) — unique pointer to a conformant
                // array. Wire is [referent][max_count][elements...]. The array
                // helper handles max_count + elements; emit the referent skip
                // here when the parameter/return carries [OpcUniquePointer].
                if (isUniquePointer)
                {
                    sb.Append(statementIndent).Append(readerLocal).AppendLine(".TryReadReferentId(out _);");
                }
                EmitArrayCodecReadLocal(
                    sb,
                    statementIndent,
                    readerLocal,
                    codec,
                    method.ParameterNames,
                    targetLocal,
                    responsePayloadLocal,
                    responseSpanLocal);
                return;
            }

            // Per MS-RPCE NDR §14.3.10, an [out] pointer-to-struct on the response
            // wire is prefixed by a 4-byte unique-pointer referent ID when declared
            // as [out] T** in IDL (e.g. IOPCServer::GetStatus's ppServerStatus).
            // Methods opt-in via [return: OpcUniquePointer] or per-out-parameter
            // [OpcUniquePointer]. Plain [out] T* reference pointers (the default for
            // scalar/struct out args) have no referent prefix.
            if (isUniquePointer)
            {
                sb.Append(statementIndent).Append(readerLocal).AppendLine(".TryReadReferentId(out _);");
            }
            sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ")
                .Append(FormatReadExpression(codec, readerLocal)).AppendLine(";");
            return;
        }

        sb.Append(statementIndent).Append(declaredType).Append(' ').Append(targetLocal).AppendLine(" = default!;");
    }

    private static void EmitArrayCodecReadLocal(
        StringBuilder sb,
        string statementIndent,
        string readerLocal,
        CodecEmitter codec,
        ImmutableArray<string> parameterNames,
        string targetLocal,
        string responsePayloadLocal,
        string responseSpanLocal)
    {
        string countLocal = UniqueLocalName(parameterNames, targetLocal + "Count", readerLocal, responsePayloadLocal, responseSpanLocal, targetLocal);
        string arrayLocal = UniqueLocalName(parameterNames, targetLocal + "Array", readerLocal, responsePayloadLocal, responseSpanLocal, targetLocal, countLocal);
        string indexLocal = UniqueLocalName(parameterNames, targetLocal + "Index", readerLocal, responsePayloadLocal, responseSpanLocal, targetLocal, countLocal, arrayLocal);

        sb.Append(statementIndent).Append("var ").Append(countLocal).Append(" = (int)").Append(readerLocal).AppendLine(".ReadUInt32();");
        sb.Append(statementIndent).Append("var ").Append(arrayLocal).Append(" = new ").Append(codec.ArrayElementType!).Append('[').Append(countLocal).AppendLine("];");
        sb.Append(statementIndent).Append("for (int ").Append(indexLocal).Append(" = 0; ").Append(indexLocal).Append(" < ").Append(countLocal).Append("; ").Append(indexLocal).AppendLine("++)");
        sb.Append(statementIndent).AppendLine("{");
        sb.Append(statementIndent).Append("    ").Append(arrayLocal).Append('[').Append(indexLocal).Append("] = ").Append(FormatReadExpression(codec, readerLocal)).AppendLine(";");
        sb.Append(statementIndent).AppendLine("}");
        sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ").Append(arrayLocal).AppendLine(";");
    }

    private static bool CanReadType(string typeName, bool isOpcInterface, string? declaringNamespace) =>
        isOpcInterface || IsOpcInterfaceRefType(typeName) || TryGetCodec(typeName, declaringNamespace, out _);

    private static bool CanWriteType(string typeName, bool isOpcInterface, string? declaringNamespace) =>
        !isOpcInterface && TryGetCodec(typeName, declaringNamespace, out _);

    private static int ResponseItemCount(MethodModel method)
    {
        int count = method.TaskReturnKind == TaskReturnKind.TaskOfT ? 1 : 0;
        foreach (var parameter in method.Parameters)
        {
            if (parameter.IsResponseValue)
            {
                count++;
            }
        }

        return count;
    }

    private static string ResponseValueType(MethodModel method)
    {
        if (method.GenerateMultiOutRecord)
        {
            return method.MultiOutRecordName;
        }

        if (ResponseItemCount(method) == 1)
        {
            if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
            {
                return method.TaskResultType!;
            }

            foreach (var parameter in method.Parameters)
            {
                if (parameter.IsResponseValue)
                {
                    return parameter.DeclaredType;
                }
            }
        }

        var sb = new StringBuilder();
        sb.Append('(');
        bool first = true;
        AppendResponseTupleItem(sb, ref first, method.TaskReturnKind == TaskReturnKind.TaskOfT, method.TaskResultType, "ReturnValue");
        foreach (var parameter in method.Parameters)
        {
            if (parameter.IsResponseValue)
            {
                AppendResponseTupleItem(sb, ref first, true, parameter.DeclaredType, parameter.ResultMemberName);
            }
        }

        sb.Append(')');
        return sb.ToString();
    }

    private static void AppendResponseTupleItem(StringBuilder sb, ref bool first, bool include, string? typeName, string memberName)
    {
        if (!include)
        {
            return;
        }

        if (!first)
        {
            sb.Append(", ");
        }

        sb.Append(typeName).Append(' ').Append(memberName);
        first = false;
    }

    private static string ResponseValueLocalName(int itemIndex) =>
        "__opcResponseValue" + itemIndex.ToString(CultureInfo.InvariantCulture);

    private static void EmitDecodedResponseReturn(StringBuilder sb, string statementIndent, MethodModel method)
    {
        int count = ResponseItemCount(method);
        if (count == 1 && !method.GenerateMultiOutRecord)
        {
            sb.Append(statementIndent).Append("return ").Append(ResponseValueLocalName(0)).AppendLine(";");
            return;
        }

        sb.Append(statementIndent).Append("return ");
        if (method.GenerateMultiOutRecord)
        {
            sb.Append("new ").Append(method.MultiOutRecordName).Append('(');
            for (int i = 0; i < count; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                sb.Append(ResponseValueLocalName(i));
            }

            sb.AppendLine(");");
            return;
        }

        sb.Append('(');
        int itemIndex = 0;
        bool first = true;
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            AppendResponseTupleValue(sb, ref first, "ReturnValue", ResponseValueLocalName(itemIndex));
            itemIndex++;
        }

        foreach (var parameter in method.Parameters)
        {
            if (parameter.IsResponseValue)
            {
                AppendResponseTupleValue(sb, ref first, parameter.ResultMemberName, ResponseValueLocalName(itemIndex));
                itemIndex++;
            }
        }

        sb.AppendLine(");");
    }

    private static void AppendResponseTupleValue(StringBuilder sb, ref bool first, string memberName, string localName)
    {
        if (!first)
        {
            sb.Append(", ");
        }

        sb.Append(memberName).Append(": ").Append(localName);
        first = false;
    }

    private static void EmitResponseParameterAssignments(StringBuilder sb, string indent, MethodModel method, string decodedLocal)
    {
        int itemIndex = method.TaskReturnKind == TaskReturnKind.TaskOfT ? 1 : 0;
        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsResponseValue)
            {
                continue;
            }

            sb.Append(indent).Append("            ").Append(parameter.Name).Append(" = ")
                .Append(DecodedMemberExpression(method, decodedLocal, itemIndex, parameter.ResultMemberName)).AppendLine(";");
            itemIndex++;
        }
    }

    private static void EmitPublicTaskReturn(StringBuilder sb, string indent, MethodModel method, string decodedLocal)
    {
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            sb.Append(indent).Append("            return global::System.Threading.Tasks.Task.FromResult(")
                .Append(DecodedMemberExpression(method, decodedLocal, 0, "ReturnValue")).AppendLine(");");
            return;
        }

        sb.Append(indent).AppendLine("            return global::System.Threading.Tasks.Task.CompletedTask;");
    }

    private static string DecodedMemberExpression(MethodModel method, string decodedLocal, int itemIndex, string memberName)
    {
        _ = itemIndex;
        if (ResponseItemCount(method) == 1 && !method.GenerateMultiOutRecord)
        {
            return decodedLocal;
        }

        return decodedLocal + "." + memberName;
    }

    private static string FormatInterfaceReadExpression(string readerLocal, string declaredType)
    {
        string readExpression = "global::Opc.Classic.Dcom.OpcInterfaceRefCodec.Read(ref " + readerLocal + ")";
        if (IsOpcInterfaceRefType(declaredType))
        {
            return readExpression;
        }

        return "(" + declaredType + ")(object)" + readExpression;
    }

    private static string FormatMInterfacePointerReadExpression(string readerLocal, string declaredType)
    {
        // OpcMInterfacePointerCodec.Read returns IOpcInterfaceRef? (null when the
        // server emits a NULL pointer). The generated proxy assigns it into an
        // IOpcInterfaceRef-typed local; the bang preserves the existing non-null
        // contract for callers (the runtime will surface a NullReferenceException
        // for NULL pointers, matching pre-Y9 behavior for IOpcInterfaceRef out
        // parameters).
        string readExpression = "global::Opc.Classic.Dcom.OpcMInterfacePointerCodec.Read(ref " + readerLocal + ")!";
        if (IsOpcInterfaceRefType(declaredType))
        {
            return readExpression;
        }

        return "(" + declaredType + ")(object)" + readExpression;
    }

    private static bool IsOpcInterfaceRefType(string typeName) =>
        string.Equals(typeName, "global::Opc.Classic.Dcom.IOpcInterfaceRef", System.StringComparison.Ordinal) ||
        string.Equals(typeName, "global::Opc.Classic.Dcom.IOpcInterfaceRef?", System.StringComparison.Ordinal);

    private static bool TryGetCodec(string typeName, string? declaringNamespace, out CodecEmitter codec)
    {
        if (TryGetArrayElementTypeName(typeName, out string elementTypeName) &&
            !TryGetArrayElementTypeName(elementTypeName, out _) &&
            TryGetCodec(elementTypeName, declaringNamespace, out var elementCodec) &&
            !elementCodec.IsArray)
        {
            codec = CodecEmitter.Array(elementTypeName, elementCodec);
            return true;
        }

        if (string.Equals(typeName, "global::Opc.Classic.OpcServerStatus", System.StringComparison.Ordinal))
        {
            if (IsAeNamespace(declaringNamespace))
            {
                codec = AeServerStatusCodec;
                return true;
            }

            if (IsHdaNamespace(declaringNamespace))
            {
                codec = HdaServerStatusCodec;
                return true;
            }
        }

        return Codecs.TryGetValue(typeName, out codec);
    }

    private static bool TryGetArrayElementTypeName(string typeName, out string elementTypeName)
    {
        if (typeName.EndsWith("[]", System.StringComparison.Ordinal))
        {
            elementTypeName = typeName.Substring(0, typeName.Length - 2);
            return true;
        }

        elementTypeName = string.Empty;
        return false;
    }

    private static CodecEmitter StaticCodec(string codecClassName) =>
        new CodecEmitter(codecClassName + ".Write(ref {Writer}, {Param})", codecClassName + ".Read(ref {Reader})");

    private static string FormatWriteExpression(CodecEmitter codec, string writerLocal, string parameterName) =>
        codec.WriteExpression.Replace("{Writer}", writerLocal).Replace("{Param}", parameterName);

    private static string FormatReadExpression(CodecEmitter codec, string readerLocal) =>
        codec.ReadExpression.Replace("{Reader}", readerLocal);

    private static bool IsAeNamespace(string? declaringNamespace) =>
        string.Equals(declaringNamespace, "Opc.Classic.Ae", System.StringComparison.Ordinal) ||
        (declaringNamespace is not null && declaringNamespace.StartsWith("Opc.Classic.Ae.", System.StringComparison.Ordinal));

    private static bool IsHdaNamespace(string? declaringNamespace) =>
        string.Equals(declaringNamespace, "Opc.Classic.Hda", System.StringComparison.Ordinal) ||
        (declaringNamespace is not null && declaringNamespace.StartsWith("Opc.Classic.Hda.", System.StringComparison.Ordinal));

    private static string ParameterList(ImmutableArray<IParameterSymbol> parameters)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            IParameterSymbol parameter = parameters[i];
            if (parameter.IsParams)
            {
                sb.Append("params ");
            }

            sb.Append(parameter.RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => string.Empty,
            });

            sb.Append(parameter.Type.ToDisplayString(TypeDisplayFormat)).Append(' ').Append(EscapeIdentifier(parameter.Name));

            if (parameter.HasExplicitDefaultValue)
            {
                sb.Append(" = ").Append(FormatDefaultValue(parameter));
            }
        }

        return sb.ToString();
    }

    private static string TypeParameterList(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.Append('<');
        for (int i = 0; i < typeParameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(typeParameters[i].Name);
        }

        sb.Append('>');
        return sb.ToString();
    }

    private static string ConstraintClauses(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var typeParameter in typeParameters)
        {
            string constraints = Constraints(typeParameter);
            if (constraints.Length > 0)
            {
                sb.Append(" where ").Append(typeParameter.Name).Append(" : ").Append(constraints);
            }
        }

        return sb.ToString();
    }

    private static string Constraints(ITypeParameterSymbol typeParameter)
    {
        var constraints = new List<string>();
        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("unmanaged");
        }
        else if (typeParameter.HasValueTypeConstraint)
        {
            constraints.Add("struct");
        }
        else if (typeParameter.HasReferenceTypeConstraint)
        {
            constraints.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
        }
        else if (typeParameter.HasNotNullConstraint)
        {
            constraints.Add("notnull");
        }

        foreach (var constraintType in typeParameter.ConstraintTypes)
        {
            constraints.Add(constraintType.ToDisplayString(TypeDisplayFormat));
        }

        if (typeParameter.HasConstructorConstraint && !typeParameter.HasValueTypeConstraint && !typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("new()");
        }

        return string.Join(", ", constraints);
    }

    private static string FormatDefaultValue(IParameterSymbol parameter)
    {
        object? value = parameter.ExplicitDefaultValue;
        if (value is null)
        {
            return parameter.Type.IsValueType && parameter.NullableAnnotation != NullableAnnotation.Annotated ? "default" : "null";
        }

        if (parameter.Type.TypeKind == TypeKind.Enum)
        {
            return "(" + parameter.Type.ToDisplayString(TypeDisplayFormat) + ")" +
                System.Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
        }

        return value switch
        {
            string text => SymbolDisplay.FormatLiteral(text, quote: true),
            char ch => SymbolDisplay.FormatLiteral(ch, quote: true),
            bool flag => flag ? "true" : "false",
            sbyte number => number.ToString(CultureInfo.InvariantCulture),
            byte number => number.ToString(CultureInfo.InvariantCulture),
            short number => number.ToString(CultureInfo.InvariantCulture),
            ushort number => number.ToString(CultureInfo.InvariantCulture),
            int number => number.ToString(CultureInfo.InvariantCulture),
            uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number => number.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            _ => "default",
        };
    }

    private static TaskReturnKind ClassifyTaskReturn(
        ITypeSymbol returnType,
        out string? taskResultType,
        out string? taskResultMarshallingType)
    {
        taskResultType = null;
        taskResultMarshallingType = null;
        if (returnType is not INamedTypeSymbol namedType ||
            !string.Equals(namedType.Name, "Task", System.StringComparison.Ordinal) ||
            !string.Equals(namedType.ContainingNamespace.ToDisplayString(), "System.Threading.Tasks", System.StringComparison.Ordinal))
        {
            return TaskReturnKind.Unsupported;
        }

        if (namedType.Arity == 0)
        {
            return TaskReturnKind.Task;
        }

        if (namedType.Arity == 1)
        {
            taskResultType = namedType.TypeArguments[0].ToDisplayString(TypeDisplayFormat);
            taskResultMarshallingType = namedType.TypeArguments[0].ToDisplayString(CodecTypeDisplayFormat);
            return TaskReturnKind.TaskOfT;
        }

        return TaskReturnKind.Unsupported;
    }

    private static string? UnsupportedSignatureReason(IMethodSymbol method, TaskReturnKind taskReturnKind)
    {
        if (method.TypeParameters.Length > 0)
        {
            return "generic methods are not supported";
        }

        if (taskReturnKind == TaskReturnKind.Unsupported)
        {
            return "method must return System.Threading.Tasks.Task or System.Threading.Tasks.Task<T>";
        }

        return null;
    }

    private static bool HasOpcInterfaceAttribute(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (string.Equals(fullName, OpcInterfaceAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasOpcMethodAttribute(IMethodSymbol method)
    {
        foreach (var attr in method.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (string.Equals(fullName, OpcMethodAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasGenerateMultiOutRecordAttribute(IMethodSymbol method)
    {
        foreach (var attr in method.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (string.Equals(fullName, OpcGenerateMultiOutRecordAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsOpcInterfaceType(ITypeSymbol symbol) =>
        symbol is INamedTypeSymbol { TypeKind: TypeKind.Interface } namedType && HasOpcInterfaceAttribute(namedType);

    private static bool TryGetTaskResultSymbol(ITypeSymbol returnType, out ITypeSymbol resultType)
    {
        if (returnType is INamedTypeSymbol { Name: "Task", Arity: 1 } namedType &&
            string.Equals(namedType.ContainingNamespace.ToDisplayString(), "System.Threading.Tasks", System.StringComparison.Ordinal))
        {
            resultType = namedType.TypeArguments[0];
            return true;
        }

        resultType = returnType;
        return false;
    }

    private static string ToPascalCase(string name)
    {
        string unescaped = name.StartsWith("@", System.StringComparison.Ordinal) ? name.Substring(1) : name;
        if (unescaped.Length == 0)
        {
            return "Value";
        }

        return char.ToUpperInvariant(unescaped[0]) + unescaped.Substring(1);
    }

    private static string UniqueLocalName(ImmutableArray<string> parameterNames, string preferredName, params string[] additionalNames)
    {
        string candidate = preferredName;
        int suffix = 0;
        while (NameMatches(parameterNames, candidate) || NameMatches(additionalNames, candidate))
        {
            suffix++;
            candidate = preferredName + suffix.ToString(CultureInfo.InvariantCulture);
        }

        return candidate;
    }

    private static bool NameMatches(IEnumerable<string> names, string candidate)
    {
        foreach (var name in names)
        {
            if (string.Equals(name, candidate, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string AccessibilityKeyword(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.NotApplicable => "internal",
        _ => "internal",
    };

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    private enum UnsupportedMarshallingKind
    {
        None,
        Parameter,
        Return,
    }

    private enum TaskReturnKind
    {
        Unsupported,
        Task,
        TaskOfT,
    }

    private readonly struct CodecEmitter
    {
        public CodecEmitter(string writeExpression, string readExpression)
            : this(writeExpression, readExpression, arrayElementType: null)
        {
        }

        private CodecEmitter(string writeExpression, string readExpression, string? arrayElementType)
        {
            WriteExpression = writeExpression;
            ReadExpression = readExpression;
            ArrayElementType = arrayElementType;
        }

        public string WriteExpression { get; }
        public string ReadExpression { get; }
        public string? ArrayElementType { get; }
        public bool IsArray => ArrayElementType is not null;

        public static CodecEmitter Array(string elementTypeName, CodecEmitter elementCodec) =>
            new(elementCodec.WriteExpression, elementCodec.ReadExpression, elementTypeName);
    }

    private sealed class ParameterModel
    {
        public ParameterModel(string name, string resultMemberName, string declaredType, string marshallingType, bool isCancellationToken, RefKind refKind, bool isOpcInterface, bool isUniquePointer = false, string? underlyingValueType = null, bool emitArrayCount = false, bool deferredElements = false) { Name = name; ResultMemberName = resultMemberName; DeclaredType = declaredType; MarshallingType = marshallingType; IsCancellationToken = isCancellationToken; RefKind = refKind; IsOpcInterface = isOpcInterface; IsUniquePointer = isUniquePointer; UnderlyingValueType = underlyingValueType; EmitArrayCount = emitArrayCount; DeferredElements = deferredElements; }
        public string Name { get; }
        public string ResultMemberName { get; }
        public string DeclaredType { get; }
        public string MarshallingType { get; }
        public bool IsCancellationToken { get; }
        public RefKind RefKind { get; }
        public bool IsOpcInterface { get; }

        /// <summary>
        /// True when this parameter is an NDR unique pointer (per DCE 1.1 §14.3.10):
        /// 4-byte referent ID on the wire, followed by the value when non-null.
        /// Inferred from nullable-value-type C# annotation (int?, float?, etc.) or
        /// from an explicit [OpcUniquePointer] attribute.
        /// </summary>
        public bool IsUniquePointer { get; }

        /// <summary>
        /// For nullable-value-type unique pointers (int? / float? / etc.), the
        /// underlying non-nullable value type's fully-qualified name. Used by the
        /// emitter to read/write the inner scalar via the matching codec lookup.
        /// Null when this parameter is not a nullable-value-type unique pointer.
        /// </summary>
        public string? UnderlyingValueType { get; }

        /// <summary>
        /// True when this array parameter carries an [OpcEmitArrayCount]
        /// attribute, instructing the request encoder to emit the array
        /// length as a standalone 4-byte field BEFORE the array (in addition
        /// to the array's own NDR max_count). Matches the IDL pattern
        /// <c>[in] DWORD N, [in, size_is(N)] T* arr</c>.
        /// </summary>
        public bool EmitArrayCount { get; }

        /// <summary>
        /// True when [OpcDeferredElements] is present: the array writer/reader
        /// uses the C706 §14.3.12.3 two-pass layout (per-element referents
        /// first, then per-element bodies). Currently implemented for
        /// <c>string[]</c> only.
        /// </summary>
        public bool DeferredElements { get; }

        public bool IsRequestValue => !IsCancellationToken && RefKind != RefKind.Out;
        public bool IsResponseValue => !IsCancellationToken && (RefKind == RefKind.Out || RefKind == RefKind.Ref);
    }
    private sealed class MethodModel
    {
        public MethodModel(
            string name,
            string returnType,
            string typeParameterList,
            string parameterList,
            string constraintClauses,
            ImmutableArray<string> outParameters,
            ImmutableArray<string> parameterNames,
            ImmutableArray<ParameterModel> parameters,
            bool hasOpcMethodAttribute,
            bool hasRefOrOutParameter,
            bool generateMultiOutRecord,
            TaskReturnKind taskReturnKind,
            string? taskResultType,
            string? taskResultMarshallingType,
            bool taskResultIsOpcInterface,
            bool taskResultIsUniquePointer,
            string? unsupportedMarshallingType,
            string? unsupportedRefOutMarshallingType,
            UnsupportedMarshallingKind unsupportedMarshallingKind,
            string? unsupportedParameterName,
            string? unsupportedSignatureReason,
            string? cancellationTokenParameterName,
            string? declaringNamespace,
            Location location)
        {
            Name = name;
            ReturnType = returnType;
            TypeParameterList = typeParameterList;
            ParameterList = parameterList;
            ConstraintClauses = constraintClauses;
            OutParameters = outParameters;
            ParameterNames = parameterNames;
            Parameters = parameters;
            HasOpcMethodAttribute = hasOpcMethodAttribute;
            HasRefOrOutParameter = hasRefOrOutParameter;
            GenerateMultiOutRecord = generateMultiOutRecord;
            TaskReturnKind = taskReturnKind;
            TaskResultType = taskResultType;
            TaskResultMarshallingType = taskResultMarshallingType;
            TaskResultIsOpcInterface = taskResultIsOpcInterface;
            TaskResultIsUniquePointer = taskResultIsUniquePointer;
            UnsupportedMarshallingType = unsupportedMarshallingType;
            UnsupportedRefOutMarshallingType = unsupportedRefOutMarshallingType;
            UnsupportedMarshallingKind = unsupportedMarshallingKind;
            UnsupportedParameterName = unsupportedParameterName;
            UnsupportedSignatureReason = unsupportedSignatureReason;
            IsFullyMarshallable = taskReturnKind != TaskReturnKind.Unsupported && unsupportedMarshallingType is null && unsupportedRefOutMarshallingType is null;
            CancellationTokenParameterName = cancellationTokenParameterName;
            DeclaringNamespace = declaringNamespace;
            Location = location;
        }

        public string Name { get; }
        public string ReturnType { get; }
        public string TypeParameterList { get; }
        public string ParameterList { get; }
        public string ConstraintClauses { get; }
        public ImmutableArray<string> OutParameters { get; }
        public ImmutableArray<string> ParameterNames { get; }
        public ImmutableArray<ParameterModel> Parameters { get; }
        public bool HasOpcMethodAttribute { get; }
        public bool HasRefOrOutParameter { get; }
        public bool GenerateMultiOutRecord { get; }
        public string MultiOutRecordName => Name + "Result";
        public TaskReturnKind TaskReturnKind { get; }
        public string? TaskResultType { get; }
        public string? TaskResultMarshallingType { get; }
        public bool TaskResultIsOpcInterface { get; }
        /// <summary>
        /// True when the Task&lt;T&gt; result is wire-encoded as a unique pointer to
        /// the value (MS-RPCE NDR §14.3.10): 4-byte referent ID followed by the
        /// value bytes. Set by [return: OpcUniquePointer] for methods whose IDL
        /// signature declares the output as [out] T** (e.g. IOPCServer::GetStatus's
        /// ppServerStatus). Default false matches the more common [out] T*
        /// reference-pointer shape where the value is inline with no prefix.
        /// </summary>
        public bool TaskResultIsUniquePointer { get; }
        public string? UnsupportedMarshallingType { get; }
        public string? UnsupportedRefOutMarshallingType { get; }
        public UnsupportedMarshallingKind UnsupportedMarshallingKind { get; }
        public string? UnsupportedParameterName { get; }
        public string? UnsupportedSignatureReason { get; }
        public bool IsFullyMarshallable { get; }
        public string? CancellationTokenParameterName { get; }
        public string? DeclaringNamespace { get; }
        public Location Location { get; }
    }
    private sealed class InterfaceModel
    {
        public InterfaceModel(string fullyQualifiedName, string? @namespace, string name, Accessibility accessibility, string typeParameterList, string typeParameterConstraints, bool isPartial, bool hasOpcInterfaceAttribute, Location location, ImmutableArray<MethodModel> methods)
        {
            FullyQualifiedName = fullyQualifiedName;
            Namespace = @namespace;
            Name = name;
            Accessibility = accessibility;
            TypeParameterList = typeParameterList;
            TypeParameterConstraints = typeParameterConstraints;
            IsPartial = isPartial;
            HasOpcInterfaceAttribute = hasOpcInterfaceAttribute;
            Location = location;
            Methods = methods;
        }

        public string FullyQualifiedName { get; }
        public string? Namespace { get; }
        public string Name { get; }
        public Accessibility Accessibility { get; }
        public string TypeParameterList { get; }
        public string TypeParameterConstraints { get; }
        public bool IsPartial { get; }
        public bool HasOpcInterfaceAttribute { get; }
        public Location Location { get; }
        public ImmutableArray<MethodModel> Methods { get; }
    }
}
