// Copyright (c) 2026 Opc.Classic Contributors. Licensed under the MIT License.

#pragma warning disable MA0051 // Source-emission helpers are easier to audit when grouped by generated member.

using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Opc.Classic.Generators;

/// <summary>
/// Emits AOT-safe server-side NDR dispatchers for OPC interface projections.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OpcServerDispatchGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "Opc.Classic.Generators";
    private const string AttributeName = "OpcGenerateServerDispatchAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;
    private const string OpcInterfaceAttributeFullName = AttributeNamespace + ".OpcInterfaceAttribute";
    private const string OpcMethodAttributeFullName = AttributeNamespace + ".OpcMethodAttribute";
    private const string OpcUniquePointerAttributeFullName = AttributeNamespace + ".OpcUniquePointerAttribute";
    private const string OpcEmitArrayCountAttributeFullName = AttributeNamespace + ".OpcEmitArrayCountAttribute";
    private const string OpcDeferredElementsAttributeFullName = AttributeNamespace + ".OpcDeferredElementsAttribute";
    private const string OpcFileTimeElementsAttributeFullName = AttributeNamespace + ".OpcFileTimeElementsAttribute";
    private const string OpcVariantElementsAttributeFullName = AttributeNamespace + ".OpcVariantElementsAttribute";
    private const string OpcRefStringAttributeFullName = AttributeNamespace + ".OpcRefStringAttribute";

    private const string AttributeSource = @"// <auto-generated by Opc.Classic.Generators.OpcServerDispatchGenerator />
#nullable enable

namespace Opc.Classic.Generators
{
    /// <summary>
    /// Requests an AOT-safe server-side dispatcher for an OPC interface projection.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class OpcGenerateServerDispatchAttribute : global::System.Attribute { }
}
";

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly SymbolDisplayFormat CodecTypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            (SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
             SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier) &
            ~SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly CodecEmitter AeServerStatusCodec = StaticCodec(
        "global::Opc.Classic.Ae.Ndr.NdrOpcEventServerStatusCodec");

    private static readonly CodecEmitter HdaServerStatusCodec = StaticCodec(
        "global::Opc.Classic.Hda.Ndr.NdrOpcHdaServerStatusCodec");

    private static readonly Dictionary<string, CodecEmitter> Codecs =
        new Dictionary<string, CodecEmitter>(System.StringComparer.Ordinal)
        {
            { "global::System.Int32", new CodecEmitter("{Writer}.WriteInt32({Param})", "{Reader}.ReadInt32()") },
            { "global::System.UInt32", new CodecEmitter("{Writer}.WriteUInt32({Param})", "{Reader}.ReadUInt32()") },
            { "global::System.Int16", new CodecEmitter("{Writer}.WriteInt16({Param})", "{Reader}.ReadInt16()") },
            { "global::System.UInt16", new CodecEmitter("{Writer}.WriteUInt16({Param})", "{Reader}.ReadUInt16()") },
            { "global::System.Int64", new CodecEmitter("{Writer}.WriteInt64({Param})", "{Reader}.ReadInt64()") },
            { "global::System.UInt64", new CodecEmitter("{Writer}.WriteUInt64({Param})", "{Reader}.ReadUInt64()") },
            { "global::System.Single", new CodecEmitter("{Writer}.WriteSingle({Param})", "{Reader}.ReadSingle()") },
            { "global::System.Double", new CodecEmitter("{Writer}.WriteDouble({Param})", "{Reader}.ReadDouble()") },
            { "global::System.Boolean", new CodecEmitter("{Writer}.WriteInt32({Param} ? -1 : 0)", "({Reader}.ReadInt32() != 0)") },
            { "global::System.Guid", new CodecEmitter("{Writer}.WriteGuid({Param})", "{Reader}.ReadGuid()") },
            { "global::Opc.Classic.Dcom.IOpcInterfaceRef", new CodecEmitter("global::Opc.Classic.Dcom.OpcInterfaceRefCodec.Write(ref {Writer}, {Param})", "global::Opc.Classic.Dcom.OpcInterfaceRefCodec.Read(ref {Reader})") },
            { "global::Opc.Classic.Dcom.OpcRemQIResult", StaticCodec("global::Opc.Classic.Dcom.NdrRemQIResultCodec") },
            { "global::System.String", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "global::System.String?", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()") },
            { "string", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "string?", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()") },
            { "global::Opc.Classic.OpcVariant", new CodecEmitter("global::Opc.Classic.Ndr.NdrVariantExtensions.WriteVariant(ref {Writer}, {Param})", "global::Opc.Classic.Ndr.NdrVariantExtensions.ReadVariant(ref {Reader})") },
            { "global::Opc.Classic.OpcSafeArray", new CodecEmitter("global::Opc.Classic.Ndr.NdrSafeArrayExtensions.WriteSafeArray(ref {Writer}, {Param})", "global::Opc.Classic.Ndr.NdrSafeArrayExtensions.ReadSafeArray(ref {Reader})") },
            { "global::Opc.Classic.OpcServerStatus", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcServerStatusCodec") },
            { "global::Opc.Classic.Da.OpcBrowseElementResult", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcBrowseElementCodec") },
            { "global::Opc.Classic.Da.OpcItemAttributes", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemAttributesCodec") },
            { "global::Opc.Classic.Da.OpcItemDef", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemDefCodec") },
            { "global::Opc.Classic.Da.OpcGroupState", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcGroupStateCodec") },
            { "global::Opc.Classic.Da.OpcItemProperties", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemPropertiesCodec") },
            { "global::Opc.Classic.Da.OpcItemPropertyResult", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemPropertyCodec") },
            { "global::Opc.Classic.Da.OpcItemResult", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemResultCodec") },
            { "global::Opc.Classic.Da.OpcItemState", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemStateCodec") },
            { "global::Opc.Classic.Da.OpcItemVqt", StaticCodec("global::Opc.Classic.Da.Ndr.NdrOpcItemVqtCodec") },
            { "global::Opc.Classic.Ae.OpcConditionState", StaticCodec("global::Opc.Classic.Ae.Ndr.NdrOpcConditionStateCodec") },
            { "global::Opc.Classic.Ae.OpcEventNotification", StaticCodec("global::Opc.Classic.Ae.Ndr.NdrOpcEventNotificationCodec") },
            { "global::Opc.Classic.Batch.OpcBatchSummary", StaticCodec("global::Opc.Classic.Batch.Ndr.NdrOpcBatchSummaryCodec") },
            { "global::Opc.Classic.Batch.OpcBatchSummaryFilter", StaticCodec("global::Opc.Classic.Batch.Ndr.NdrOpcBatchSummaryFilterCodec") },
            { "global::Opc.Classic.Hda.OpcHdaAnnotation", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaAnnotationCodec") },
            { "global::Opc.Classic.Hda.OpcHdaAttribute", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaAttributeCodec") },
            { "global::Opc.Classic.Hda.OpcHdaItem", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaItemCodec") },
            { "global::Opc.Classic.Hda.OpcHdaModifiedItem", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaModifiedItemCodec") },
            { "global::Opc.Classic.Hda.OpcHdaTime", StaticCodec("global::Opc.Classic.Hda.Ndr.NdrOpcHdaTimeCodec") },
        };

    private const string DiagnosticCategory = "Opc.Classic.Generators";
    private const string DiagnosticsHelpLinkUri = "docs/generators/diagnostics.md";

    private static readonly DiagnosticDescriptor NotPartialDescriptor = new DiagnosticDescriptor(
        id: "OPCGEN101",
        title: "Opc server dispatcher target must be partial",
        messageFormat: "Interface '{0}' is decorated with [OpcGenerateServerDispatch] but is not declared partial",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor MissingOpcInterfaceDescriptor = new DiagnosticDescriptor(
        id: "OPCGEN102",
        title: "Opc server dispatcher target should be decorated with OpcInterface",
        messageFormat: "Interface '{0}' is decorated with [OpcGenerateServerDispatch] but is not decorated with [OpcInterface]",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor UnsupportedSignatureDescriptor = new DiagnosticDescriptor(
        id: "OPCGEN103",
        title: "Opc server method has unsupported signature",
        messageFormat: "Method '{0}' is marked [OpcMethod] but has an unsupported server-dispatch signature: {1}",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor UnsupportedParameterDescriptor = new DiagnosticDescriptor(
        id: "OPCGEN104",
        title: "Opc server method has unsupported parameter type",
        messageFormat: "Method '{0}' has unsupported server parameter '{1}' of OPC method type '{2}'",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    private static readonly DiagnosticDescriptor UnsupportedReturnDescriptor = new DiagnosticDescriptor(
        id: "OPCGEN105",
        title: "Opc server method has unsupported response type",
        messageFormat: "Method '{0}' has unsupported server response OPC method type '{1}'",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        helpLinkUri: DiagnosticsHelpLinkUri);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: "OpcGenerateServerDispatchAttribute.g.cs",
                sourceText: SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: AttributeFullName,
            predicate: static (node, _) => node is InterfaceDeclarationSyntax,
            transform: static (ctx, _) => Transform(ctx));

        context.RegisterSourceOutput(candidates, Emit);
    }

    private static InterfaceModel? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol || ctx.TargetNode is not InterfaceDeclarationSyntax syntax)
        {
            return null;
        }

        bool isPartial = false;
        foreach (var modifier in syntax.Modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword))
            {
                isPartial = true;
                break;
            }
        }

        return new InterfaceModel(
            fullyQualifiedName: symbol.ToDisplayString(TypeDisplayFormat),
            @namespace: symbol.ContainingNamespace != null && !symbol.ContainingNamespace.IsGlobalNamespace
                ? symbol.ContainingNamespace.ToDisplayString()
                : null,
            name: symbol.Name,
            accessibility: symbol.DeclaredAccessibility,
            typeParameterList: TypeParameterList(symbol.TypeParameters),
            typeParameterConstraints: ConstraintClauses(symbol.TypeParameters),
            isPartial: isPartial,
            hasOpcInterfaceAttribute: HasOpcInterfaceAttribute(symbol),
            location: syntax.Identifier.GetLocation(),
            methods: CollectMethods(symbol));
    }

    private static ImmutableArray<MethodModel> CollectMethods(INamedTypeSymbol interfaceSymbol)
    {
        var builder = ImmutableArray.CreateBuilder<MethodModel>();
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol { MethodKind: MethodKind.Ordinary } method && TryGetOpcMethodOpnum(method, out int opnum))
            {
                builder.Add(CreateMethodModel(method, opnum));
            }
        }

        return builder.ToImmutable();
    }

    private static MethodModel CreateMethodModel(IMethodSymbol method, int opnum)
    {
        var parameterNames = ImmutableArray.CreateBuilder<string>();
        var parameters = ImmutableArray.CreateBuilder<ParameterModel>();
        string? cancellationTokenParameterName = null;
        foreach (var parameter in method.Parameters)
        {
            string escapedName = EscapeIdentifier(parameter.Name);
            parameterNames.Add(escapedName);
            bool isCancellationToken = string.Equals(parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::System.Threading.CancellationToken", System.StringComparison.Ordinal);
            if (cancellationTokenParameterName is null && isCancellationToken)
            {
                cancellationTokenParameterName = escapedName;
            }

            DetectUniquePointer(parameter, out bool isUniquePointer, out string? underlyingValueType);
            bool emitArrayCount = HasEmitArrayCountAttribute(parameter);
            bool deferredElements = HasDeferredElementsAttribute(parameter);
            bool fileTimeElements = HasFileTimeElementsAttribute(parameter);
            bool variantElements = HasVariantElementsAttribute(parameter);
            bool refString = HasRefStringAttribute(parameter);

            parameters.Add(new ParameterModel(
                escapedName,
                ToPascalCase(parameter.Name),
                parameter.Type.ToDisplayString(TypeDisplayFormat),
                parameter.Type.ToDisplayString(CodecTypeDisplayFormat),
                isCancellationToken,
                parameter.RefKind,
                IsOpcInterfaceType(parameter.Type),
                isUniquePointer,
                underlyingValueType,
                emitArrayCount,
                fileTimeElements,
                variantElements,
                refString,
                deferredElements));
        }

        TaskReturnKind taskReturnKind = ClassifyTaskReturn(method.ReturnType, out string? taskResultType, out string? taskResultMarshallingType);
        bool taskResultIsOpcInterface = TryGetTaskResultSymbol(method.ReturnType, out var taskResultSymbol) && IsOpcInterfaceType(taskResultSymbol);
        bool taskResultIsUniquePointer = HasReturnUniquePointerAttribute(method);
        string? declaringNamespace = ContainingNamespace(method.ContainingType);
        string? unsupportedSignatureReason = UnsupportedSignatureReason(method, taskReturnKind);
        string? unsupportedType = FindUnsupportedMarshallingType(
            parameters,
            taskReturnKind,
            taskResultMarshallingType,
            taskResultIsOpcInterface,
            declaringNamespace,
            out UnsupportedMarshallingKind unsupportedKind,
            out string? unsupportedParameterName);

        return new MethodModel(
            method.Name,
            opnum,
            parameters.ToImmutable(),
            parameterNames.ToImmutable(),
            taskReturnKind,
            taskResultType,
            taskResultMarshallingType,
            taskResultIsOpcInterface,
            taskResultIsUniquePointer,
            unsupportedSignatureReason,
            unsupportedType,
            unsupportedKind,
            unsupportedParameterName,
            cancellationTokenParameterName,
            declaringNamespace,
            method.Locations.IsDefaultOrEmpty ? Location.None : method.Locations[0]);
    }

    private static void DetectUniquePointer(IParameterSymbol parameter, out bool isUniquePointer, out string? underlyingValueType)
    {
        isUniquePointer = false;
        underlyingValueType = null;
        if (parameter.Type is INamedTypeSymbol namedType
            && namedType.IsGenericType
            && namedType.OriginalDefinition is { } orig
            && string.Equals(orig.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::System.Nullable<T>", System.StringComparison.Ordinal)
            && namedType.TypeArguments.Length == 1)
        {
            isUniquePointer = true;
            underlyingValueType = namedType.TypeArguments[0].ToDisplayString(CodecTypeDisplayFormat);
        }
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcUniquePointerAttributeFullName, System.StringComparison.Ordinal))
            {
                isUniquePointer = true;
            }
        }
    }

    private static bool HasReturnUniquePointerAttribute(IMethodSymbol method)
    {
        foreach (var attr in method.GetReturnTypeAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcUniquePointerAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasEmitArrayCountAttribute(IParameterSymbol parameter)
    {
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcEmitArrayCountAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasDeferredElementsAttribute(IParameterSymbol parameter)
    {
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcDeferredElementsAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasFileTimeElementsAttribute(IParameterSymbol parameter)
    {
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcFileTimeElementsAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasVariantElementsAttribute(IParameterSymbol parameter)
    {
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcVariantElementsAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static bool HasRefStringAttribute(IParameterSymbol parameter)
    {
        foreach (var attr in parameter.GetAttributes())
        {
            if (attr.AttributeClass is null) { continue; }
            if (string.Equals(attr.AttributeClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), "global::" + OpcRefStringAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }
        return false;
    }

    private static string? ContainingNamespace(INamedTypeSymbol symbol) =>
        symbol.ContainingNamespace != null && !symbol.ContainingNamespace.IsGlobalNamespace
            ? symbol.ContainingNamespace.ToDisplayString()
            : null;

    private static void Emit(SourceProductionContext spc, InterfaceModel? maybeModel)
    {
        if (maybeModel is null)
        {
            return;
        }

        InterfaceModel model = maybeModel;
        if (!model.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(NotPartialDescriptor, model.Location, model.FullyQualifiedName));
            return;
        }

        if (!model.HasOpcInterfaceAttribute)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingOpcInterfaceDescriptor, model.Location, model.FullyQualifiedName));
        }

        foreach (var method in model.Methods)
        {
            if (method.UnsupportedSignatureReason is not null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(UnsupportedSignatureDescriptor, method.Location, method.Name, method.UnsupportedSignatureReason));
            }
            else if (method.UnsupportedMarshallingType is not null)
            {
                DiagnosticDescriptor descriptor = method.UnsupportedMarshallingKind == UnsupportedMarshallingKind.Parameter
                    ? UnsupportedParameterDescriptor
                    : UnsupportedReturnDescriptor;
                spc.ReportDiagnostic(Diagnostic.Create(
                    descriptor,
                    method.Location,
                    method.Name,
                    method.UnsupportedParameterName ?? "<return>",
                    method.UnsupportedMarshallingType));
            }
        }

        var sb = new StringBuilder(1024);
        sb.AppendLine("// <auto-generated by Opc.Classic.Generators.OpcServerDispatchGenerator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        string indent = hasNamespace ? "    " : string.Empty;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string accessibility = AccessibilityKeyword(model.Accessibility);
        string dispatcherName = model.Name + "ServerDispatcher";
        sb.Append(indent).Append(accessibility).Append(" partial class ").Append(dispatcherName).Append(model.TypeParameterList)
            .Append(" : global::Opc.Classic.Hosting.IOpcServerDispatcher").Append(model.TypeParameterConstraints).AppendLine();
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    private const int InitialResponseBufferSize = 64 * 1024;");
        sb.Append(indent).Append("    private readonly ").Append(model.FullyQualifiedName).AppendLine(" _impl;");
        sb.AppendLine();
        sb.Append(indent).Append("    public ").Append(dispatcherName).Append('(').Append(model.FullyQualifiedName).AppendLine(" impl)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        _impl = impl ?? throw new global::System.ArgumentNullException(nameof(impl));");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        EmitDispatchMethod(sb, indent, model);
        foreach (var method in model.Methods)
        {
            sb.AppendLine();
            EmitMethodDispatcher(sb, indent, method);
        }

        sb.Append(indent).AppendLine("}");
        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        string hint = model.FullyQualifiedName.Replace("global::", string.Empty).Replace("<", "_").Replace(">", "_") + ".OpcServerDispatch.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitDispatchMethod(StringBuilder sb, string indent, InterfaceModel model)
    {
        bool hasMethods = model.Methods.Length > 0;
        sb.Append(indent).Append("    public ");
        if (hasMethods)
        {
            sb.Append("async ");
        }

        sb.AppendLine("global::System.Threading.Tasks.ValueTask<global::Opc.Classic.Hosting.DispatchResult> DispatchAsync(");
        sb.Append(indent).AppendLine("        int opnum,");
        sb.Append(indent).AppendLine("        global::System.ReadOnlyMemory<byte> requestPayload,");
        sb.Append(indent).AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append(indent).AppendLine("    {");
        if (!hasMethods)
        {
            sb.Append(indent).AppendLine("        _ = requestPayload;");
            sb.Append(indent).AppendLine("        _ = cancellationToken;");
            sb.Append(indent).AppendLine("        return new global::System.Threading.Tasks.ValueTask<global::Opc.Classic.Hosting.DispatchResult>(global::Opc.Classic.Hosting.DispatchResult.NotImplemented(opnum));");
            sb.Append(indent).AppendLine("    }");
            return;
        }

        sb.Append(indent).AppendLine("        try");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            switch (opnum)");
        sb.Append(indent).AppendLine("            {");
        foreach (var method in model.Methods)
        {
            sb.Append(indent).Append("                case ").Append(method.Opnum.ToString(CultureInfo.InvariantCulture)).Append(": return await ")
                .Append(DispatchMethodName(method)).AppendLine("(requestPayload, cancellationToken).ConfigureAwait(false);");
        }

        sb.Append(indent).AppendLine("                default: return global::Opc.Classic.Hosting.DispatchResult.NotImplemented(opnum);");
        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("        catch (global::Opc.Classic.OpcException exception)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            return global::Opc.Classic.Hosting.DispatchResult.Fault(exception.ResultId.Code);");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("    }");
    }

    private static void EmitMethodDispatcher(StringBuilder sb, string indent, MethodModel method)
    {
        if (!method.IsFullyMarshallable)
        {
            sb.Append(indent).Append("    private static global::System.Threading.Tasks.ValueTask<global::Opc.Classic.Hosting.DispatchResult> ").Append(DispatchMethodName(method)).AppendLine("(");
            sb.Append(indent).AppendLine("        global::System.ReadOnlyMemory<byte> requestPayload,");
            sb.Append(indent).AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        _ = requestPayload;");
            sb.Append(indent).AppendLine("        _ = cancellationToken;");
            sb.Append(indent).Append("        return new global::System.Threading.Tasks.ValueTask<global::Opc.Classic.Hosting.DispatchResult>(global::Opc.Classic.Hosting.DispatchResult.NotImplemented(")
                .Append(method.Opnum.ToString(CultureInfo.InvariantCulture)).AppendLine("));");
            sb.Append(indent).AppendLine("    }");
            return;
        }

        sb.Append(indent).Append("    private global::System.Threading.Tasks.ValueTask<global::Opc.Classic.Hosting.DispatchResult> ").Append(DispatchMethodName(method)).AppendLine("(");
        sb.Append(indent).AppendLine("        global::System.ReadOnlyMemory<byte> requestPayload,");
        sb.Append(indent).AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        sb.Append(indent).AppendLine("    {");
        EmitDecodeRequest(sb, indent, method);
        sb.Append(indent).Append("        return ").Append(CoreMethodName(method)).Append('(');
        AppendCoreArguments(sb, method);
        sb.AppendLine(");");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
        EmitCoreMethod(sb, indent, method);
        if (ResponseItemCount(method) > 0)
        {
            sb.AppendLine();
            EmitEncodeResponseMethod(sb, indent, method);
        }
    }

    private static void EmitDecodeRequest(StringBuilder sb, string indent, MethodModel method)
    {
        bool hasRequestValues = HasRequestValues(method);
        string readerLocal = UniqueLocalName(method.ParameterNames, "__opcReader");
        if (hasRequestValues)
        {
            sb.Append(indent).Append("        var ").Append(readerLocal).Append(" = new global::Opc.Classic.Ndr.NdrReader(requestPayload.Span);").AppendLine();
        }
        else
        {
            sb.Append(indent).AppendLine("        _ = requestPayload;");
        }

        foreach (var parameter in method.Parameters)
        {
            if (parameter.IsRequestValue)
            {
                // Sibling-count first if [OpcEmitArrayCount] is present —
                // mirror of the proxy's request encoder so the dispatcher
                // consumes the count before reading the array body.
                if (parameter.EmitArrayCount)
                {
                    sb.Append(indent).Append("        _ = ").Append(readerLocal).AppendLine(".ReadUInt32();");
                }
                if (parameter.RefString && IsStringMarshallingType(parameter.MarshallingType))
                {
                    sb.Append(indent).Append("        var ").Append(parameter.Name).Append(" = ").Append(readerLocal).AppendLine(".ReadUnicodeString();");
                    continue;
                }
                // [OpcVariantElements] on a request parameter: read max_count
                // + N per-element wireVARIANT bodies. Mirror of the proxy
                // request encoder for IDL [in, size_is(N)] VARIANT*.
                if (parameter.VariantElements && IsVariantArrayMarshallingType(parameter.MarshallingType))
                {
                    string countLocal = parameter.Name + "Count";
                    string idxLocal = parameter.Name + "Idx";
                    sb.Append(indent).Append("        int ").Append(countLocal).Append(" = (int)").Append(readerLocal).AppendLine(".ReadUInt32();");
                    sb.Append(indent).Append("        var ").Append(parameter.Name).Append(" = new global::Opc.Classic.OpcVariant[").Append(countLocal).AppendLine("];");
                    sb.Append(indent).Append("        for (int ").Append(idxLocal).Append(" = 0; ").Append(idxLocal).Append(" < ").Append(countLocal).Append("; ").Append(idxLocal).AppendLine("++)");
                    sb.Append(indent).AppendLine("        {");
                    sb.Append(indent).Append("            ").Append(parameter.Name).Append('[').Append(idxLocal).Append("] = global::Opc.Classic.Ndr.NdrVariantExtensions.ReadVariantElement(ref ").Append(readerLocal).AppendLine(");");
                    sb.Append(indent).AppendLine("        }");
                    continue;
                }
                // [OpcDeferredElements] on a string[] request parameter: read
                // the C706 §14.3.12.3 deferred-pile layout that the proxy
                // emits (max_count + N per-element referent IDs + N
                // per-element conformant-varying string bodies, no per-
                // element referent before each body). If combined with
                // [OpcUniquePointer], the outer [unique] referent precedes
                // the max_count; if the outer referent is NULL the array is
                // entirely absent on the wire (proxy writes only the
                // referent), so we synthesise an empty array.
                if (parameter.DeferredElements && string.Equals(parameter.MarshallingType, "global::System.String[]", System.StringComparison.Ordinal))
                {
                    string countLocal = parameter.Name + "Count";
                    string idxLocal = parameter.Name + "Idx";
                    if (parameter.IsUniquePointer)
                    {
                        string refLocal = parameter.Name + "Ref";
                        sb.Append(indent).Append("        uint ").Append(refLocal).Append(" = ").Append(readerLocal).AppendLine(".ReadUInt32();");
                        sb.Append(indent).Append("        global::System.String[] ").Append(parameter.Name).AppendLine(";");
                        sb.Append(indent).Append("        if (").Append(refLocal).AppendLine(" != 0u)");
                        sb.Append(indent).AppendLine("        {");
                        sb.Append(indent).Append("            int ").Append(countLocal).Append(" = (int)").Append(readerLocal).AppendLine(".ReadUInt32();");
                        sb.Append(indent).Append("            for (int ").Append(idxLocal).Append(" = 0; ").Append(idxLocal).Append(" < ").Append(countLocal).Append("; ").Append(idxLocal).AppendLine("++)");
                        sb.Append(indent).AppendLine("            {");
                        sb.Append(indent).Append("                _ = ").Append(readerLocal).AppendLine(".TryReadReferentId(out _);");
                        sb.Append(indent).AppendLine("            }");
                        sb.Append(indent).Append("            ").Append(parameter.Name).Append(" = new global::System.String[").Append(countLocal).AppendLine("];");
                        sb.Append(indent).Append("            for (int ").Append(idxLocal).Append(" = 0; ").Append(idxLocal).Append(" < ").Append(countLocal).Append("; ").Append(idxLocal).AppendLine("++)");
                        sb.Append(indent).AppendLine("            {");
                        sb.Append(indent).Append("                ").Append(parameter.Name).Append('[').Append(idxLocal).Append("] = ").Append(readerLocal).AppendLine(".ReadUnicodeString()!;");
                        sb.Append(indent).AppendLine("            }");
                        sb.Append(indent).AppendLine("        }");
                        sb.Append(indent).AppendLine("        else");
                        sb.Append(indent).AppendLine("        {");
                        sb.Append(indent).Append("            ").Append(parameter.Name).AppendLine(" = global::System.Array.Empty<global::System.String>();");
                        sb.Append(indent).AppendLine("        }");
                        continue;
                    }
                    sb.Append(indent).Append("        int ").Append(countLocal).Append(" = (int)").Append(readerLocal).AppendLine(".ReadUInt32();");
                    sb.Append(indent).Append("        for (int ").Append(idxLocal).Append(" = 0; ").Append(idxLocal).Append(" < ").Append(countLocal).Append("; ").Append(idxLocal).AppendLine("++)");
                    sb.Append(indent).AppendLine("        {");
                    sb.Append(indent).Append("            _ = ").Append(readerLocal).AppendLine(".TryReadReferentId(out _);");
                    sb.Append(indent).AppendLine("        }");
                    sb.Append(indent).Append("        var ").Append(parameter.Name).Append(" = new global::System.String[").Append(countLocal).AppendLine("];");
                    sb.Append(indent).Append("        for (int ").Append(idxLocal).Append(" = 0; ").Append(idxLocal).Append(" < ").Append(countLocal).Append("; ").Append(idxLocal).AppendLine("++)");
                    sb.Append(indent).AppendLine("        {");
                    sb.Append(indent).Append("            ").Append(parameter.Name).Append('[').Append(idxLocal).Append("] = ").Append(readerLocal).AppendLine(".ReadUnicodeString()!;");
                    sb.Append(indent).AppendLine("        }");
                    continue;
                }
                EmitCodecReadLocal(sb, indent + "        ", readerLocal, method, parameter.DeclaredType, parameter.MarshallingType, parameter.IsOpcInterface, parameter.IsUniquePointer, parameter.UnderlyingValueType, parameter.Name, parameter.FileTimeElements);
            }
        }
    }

    private static bool IsStringMarshallingType(string marshallingType) =>
        string.Equals(marshallingType, "string", System.StringComparison.Ordinal) ||
        string.Equals(marshallingType, "string?", System.StringComparison.Ordinal) ||
        string.Equals(marshallingType, "global::System.String", System.StringComparison.Ordinal) ||
        string.Equals(marshallingType, "global::System.String?", System.StringComparison.Ordinal);

    private static void EmitCoreMethod(StringBuilder sb, string indent, MethodModel method)
    {
        sb.Append(indent).Append("    private async global::System.Threading.Tasks.ValueTask<global::Opc.Classic.Hosting.DispatchResult> ").Append(CoreMethodName(method)).Append('(');
        AppendCoreParameters(sb, method);
        sb.AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        EmitOutLocalDeclarations(sb, indent, method);
        EmitCallImpl(sb, indent, method);
        if (ResponseItemCount(method) == 0)
        {
            sb.Append(indent).AppendLine("        return global::Opc.Classic.Hosting.DispatchResult.Success(global::System.Array.Empty<byte>(), global::Opc.Classic.OpcResultId.Ok.Code);");
        }
        else
        {
            sb.Append(indent).Append("        return ").Append(EncodeResponseName(method)).Append('(');
            AppendEncodeArguments(sb, method);
            sb.AppendLine(");");
        }

        sb.Append(indent).AppendLine("    }");
    }

    private static void EmitOutLocalDeclarations(StringBuilder sb, string indent, MethodModel method)
    {
        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsCancellationToken && parameter.RefKind == RefKind.Out)
            {
                sb.Append(indent).Append("        ").Append(parameter.DeclaredType).Append(' ').Append(parameter.Name).AppendLine(";");
            }
        }
    }

    private static void EmitCallImpl(StringBuilder sb, string indent, MethodModel method)
    {
        string taskLocal = UniqueLocalName(method.ParameterNames, "__opcTask");
        sb.Append(indent).Append("        var ").Append(taskLocal).Append(" = _impl.").Append(method.Name).Append('(');
        AppendCallArguments(sb, method);
        sb.AppendLine(");");
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            string returnLocal = ReturnValueLocal(method);
            sb.Append(indent).Append("        var ").Append(returnLocal).Append(" = await ").Append(taskLocal).AppendLine(".ConfigureAwait(false);");
        }
        else
        {
            sb.Append(indent).Append("        await ").Append(taskLocal).AppendLine(".ConfigureAwait(false);");
        }
    }

    private static void AppendCallArguments(StringBuilder sb, MethodModel method)
    {
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            ParameterModel parameter = method.Parameters[i];
            if (parameter.IsCancellationToken)
            {
                sb.Append("cancellationToken");
                continue;
            }

            if (parameter.RefKind == RefKind.Ref)
            {
                sb.Append("ref ");
            }
            else if (parameter.RefKind == RefKind.Out)
            {
                sb.Append("out ");
            }

            sb.Append(parameter.Name);
        }
    }

    private static void EmitEncodeResponseMethod(StringBuilder sb, string indent, MethodModel method)
    {
        sb.Append(indent).Append("    private static global::Opc.Classic.Hosting.DispatchResult ").Append(EncodeResponseName(method)).Append('(');
        AppendEncodeParameters(sb, method);
        sb.AppendLine(")");
        sb.Append(indent).AppendLine("    {");
        string bufferLocal = UniqueLocalName(method.ParameterNames, "__opcBuffer");
        string writerLocal = UniqueLocalName(method.ParameterNames, "__opcWriter", bufferLocal);
        sb.Append(indent).Append("        var ").Append(bufferLocal).AppendLine(" = global::System.Buffers.ArrayPool<byte>.Shared.Rent(InitialResponseBufferSize);");
        sb.Append(indent).AppendLine("        try");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            var ").Append(writerLocal).Append(" = new global::Opc.Classic.Ndr.NdrWriter(new global::System.Span<byte>(").Append(bufferLocal).AppendLine(", 0, InitialResponseBufferSize));");
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            EmitCodecWrite(sb, indent + "            ", writerLocal, method.TaskResultMarshallingType!, ReturnValueLocal(method), method, isUniquePointer: method.TaskResultIsUniquePointer, underlyingValueType: null);
        }

        foreach (var parameter in method.Parameters)
        {
            if (parameter.IsResponseValue)
            {
                // [out, size_is(,N)] FILETIME** with [OpcFileTimeElements]
                // tag: each element is 2x DWORD (4-byte aligned).
                if (parameter.FileTimeElements && IsLongArrayMarshallingType(parameter.MarshallingType))
                {
                    if (parameter.IsUniquePointer)
                    {
                        sb.Append(indent).Append("            ").Append(writerLocal).Append(".WriteUniquePointerReferent(").Append(parameter.Name).AppendLine(" is not null);");
                        sb.Append(indent).Append("            if (").Append(parameter.Name).AppendLine(" is not null)");
                        sb.Append(indent).AppendLine("            {");
                        sb.Append(indent).Append("                ").Append(writerLocal).Append(".WriteConformantFileTimeArray(").Append(parameter.Name).AppendLine(");");
                        sb.Append(indent).AppendLine("            }");
                    }
                    else
                    {
                        sb.Append(indent).Append("            ").Append(writerLocal).Append(".WriteConformantFileTimeArray(").Append(parameter.Name).AppendLine(");");
                    }
                    continue;
                }
                // [out, size_is(,N)] VARIANT** with [OpcVariantElements]
                // tag: MS-OAUT 2.2.29.2 transmission form per element.
                if (parameter.VariantElements && IsVariantArrayMarshallingType(parameter.MarshallingType))
                {
                    EmitDispatchVariantElementsArrayWrite(sb, indent + "            ", writerLocal, parameter.Name, parameter.IsUniquePointer);
                    continue;
                }
                EmitCodecWrite(sb, indent + "            ", writerLocal, parameter.MarshallingType, parameter.Name, method, isUniquePointer: parameter.IsUniquePointer, underlyingValueType: parameter.UnderlyingValueType);
            }
        }

        sb.Append(indent).Append("            return global::Opc.Classic.Hosting.DispatchResult.Success(new global::System.ReadOnlySpan<byte>(").Append(bufferLocal).Append(", 0, ").Append(writerLocal).AppendLine(".Position).ToArray(), global::Opc.Classic.OpcResultId.Ok.Code);");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("        finally");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            global::System.Buffers.ArrayPool<byte>.Shared.Return(").Append(bufferLocal).AppendLine(");");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("    }");
    }

    private static void EmitCodecWrite(StringBuilder sb, string statementIndent, string writerLocal, string marshallingType, string valueExpression, MethodModel method, bool isUniquePointer = false, string? underlyingValueType = null)
    {
        // NDR unique pointer (DCE 1.1 §14.3.10): emit 4-byte referent ID before
        // the value. Used for IDL outputs declared as [out] T** (e.g. GetStatus's
        // ppServerStatus) so the wire layout matches what real DCOM clients
        // expect when calling into our managed server.
        if (isUniquePointer)
        {
            // [out, iid_is(riid)] LPUNKNOWN *ppUnk is wire-encoded as a unique
            // pointer to MInterfacePointer (MS-DCOM §2.2.1.10). Route through
            // OpcMInterfacePointerCodec which emits referent + cbData + OBJREF
            // (vs. OpcInterfaceRefCodec which writes only the OBJREF bytes).
            if (string.Equals(marshallingType, "global::Opc.Classic.Dcom.IOpcInterfaceRef", System.StringComparison.Ordinal))
            {
                sb.Append(statementIndent).Append("global::Opc.Classic.Dcom.OpcMInterfacePointerCodec.Write(ref ").Append(writerLocal).Append(", ").Append(valueExpression).AppendLine(");");
                return;
            }

            string codecKey = underlyingValueType ?? marshallingType;
            if (TryGetCodec(codecKey, method.DeclaringNamespace, out var underlyingCodec) && !underlyingCodec.IsArray)
            {
                if (underlyingValueType is not null)
                {
                    sb.Append(statementIndent).Append(writerLocal).Append(".WriteUniquePointerReferent(").Append(valueExpression).AppendLine(".HasValue);");
                    sb.Append(statementIndent).Append("if (").Append(valueExpression).AppendLine(".HasValue)");
                    sb.Append(statementIndent).AppendLine("{");
                    sb.Append(statementIndent).Append("    ").Append(FormatWriteExpression(underlyingCodec, writerLocal, valueExpression + ".Value")).AppendLine(";");
                    sb.Append(statementIndent).AppendLine("}");
                }
                else
                {
                    sb.Append(statementIndent).Append(writerLocal).AppendLine(".WriteUniquePointerReferent(true);");
                    sb.Append(statementIndent).Append(FormatWriteExpression(underlyingCodec, writerLocal, valueExpression)).AppendLine(";");
                }
                return;
            }
        }

        if (TryGetCodec(marshallingType, method.DeclaringNamespace, out var codec))
        {
            if (codec.IsArray)
            {
                // Codecs with nested deferred-pointer elements use the
                // matching deferred-pile encoder.
                string? deferredHelper = TryGetDeferredPileArrayHelperWrite(codec.ArrayElementType);
                if (deferredHelper is not null)
                {
                    sb.Append(statementIndent).Append(deferredHelper).Append("(ref ").Append(writerLocal).Append(", ").Append(valueExpression).AppendLine(");");
                    return;
                }
                // [out] T** unique-pointer-prefixed conformant array. Emit
                // referent + (max_count + elements) so the proxy can decode it.
                if (isUniquePointer)
                {
                    sb.Append(statementIndent).Append(writerLocal).Append(".WriteUniquePointerReferent(").Append(valueExpression).AppendLine(" is not null);");
                    sb.Append(statementIndent).Append("if (").Append(valueExpression).AppendLine(" is not null)");
                    sb.Append(statementIndent).AppendLine("{");
                    EmitArrayCodecWrite(sb, statementIndent + "    ", writerLocal, valueExpression, codec, method.ParameterNames);
                    sb.Append(statementIndent).AppendLine("}");
                    return;
                }
                EmitArrayCodecWrite(sb, statementIndent, writerLocal, valueExpression, codec, method.ParameterNames);
                return;
            }

            sb.Append(statementIndent).Append(FormatWriteExpression(codec, writerLocal, valueExpression)).AppendLine(";");
            return;
        }

        sb.Append(statementIndent).Append(writerLocal).AppendLine(".WriteRawBytes(global::System.ReadOnlySpan<byte>.Empty);");
    }

    private static string? TryGetDeferredPileArrayHelperWrite(string? arrayElementType) => arrayElementType switch
    {
        "global::Opc.Classic.Da.OpcBrowseElementResult" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcBrowseResponseDecoder.WriteConformantArrayWithReferent",
        "global::Opc.Classic.Da.OpcItemProperties" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcBrowseResponseDecoder.WriteItemPropertiesConformantArray",
        "global::Opc.Classic.Da.OpcItemResult" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcItemResultCodec.WriteConformantArray",
        "global::Opc.Classic.Da.OpcItemAttributes" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcItemAttributesCodec.WriteConformantArray",
        // OpcItemState contains a [unique] VARIANT body. NDR §14.3.12.3 requires
        // conformant arrays of structs with deferred pointers to use the
        // deferred-pile layout: N inline parts followed by N deferred bodies
        // (NOT inline+body interleaved per item). NdrOpcItemStateCodec.WriteConformantArray
        // implements this layout and matches the hand-written
        // IOPCSyncIOClientProxy.ReadConformantOpcItemStateArray reader.
        "global::Opc.Classic.Da.OpcItemState" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcItemStateCodec.WriteConformantArray",
        _ => null,
    };

    private static void EmitArrayCodecWrite(StringBuilder sb, string statementIndent, string writerLocal, string valueExpression, CodecEmitter codec, ImmutableArray<string> parameterNames)
    {
        string itemLocal = UniqueLocalName(parameterNames, "__opcItem", writerLocal, valueExpression);
        sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32((uint)(").Append(valueExpression).AppendLine("?.Length ?? 0));");
        sb.Append(statementIndent).Append("if (").Append(valueExpression).AppendLine(" != null)");
        sb.Append(statementIndent).AppendLine("{");
        sb.Append(statementIndent).Append("    foreach (var ").Append(itemLocal).Append(" in ").Append(valueExpression).AppendLine(")");
        sb.Append(statementIndent).AppendLine("    {");
        sb.Append(statementIndent).Append("        ").Append(FormatWriteExpression(codec, writerLocal, itemLocal)).AppendLine(";");
        sb.Append(statementIndent).AppendLine("    }");
        sb.Append(statementIndent).AppendLine("}");
    }

    private static bool IsLongArrayMarshallingType(string marshallingType) =>
        string.Equals(marshallingType, "global::System.Int64[]", System.StringComparison.Ordinal) ||
        string.Equals(marshallingType, "long[]", System.StringComparison.Ordinal);

    private static bool IsVariantArrayMarshallingType(string marshallingType) =>
        string.Equals(marshallingType, "global::Opc.Classic.OpcVariant[]", System.StringComparison.Ordinal);

    private static void EmitDispatchVariantElementsArrayWrite(StringBuilder sb, string statementIndent, string writerLocal, string valueExpression, bool isUniquePointer)
    {
        if (isUniquePointer)
        {
            sb.Append(statementIndent).Append(writerLocal).Append(".WriteUniquePointerReferent(").Append(valueExpression).AppendLine(" is not null);");
            sb.Append(statementIndent).Append("if (").Append(valueExpression).AppendLine(" is not null)");
            sb.Append(statementIndent).AppendLine("{");
            sb.Append(statementIndent).Append("    ").Append(writerLocal).Append(".WriteUInt32((uint)").Append(valueExpression).AppendLine(".Length);");
            // Per DCE 1.1 §14.3.12.3 deferred pile: emit N per-element unique-pointer
            // referents inline, then align to 8 and emit the bodies in order.
            sb.Append(statementIndent).Append("    for (int __opcRefIdx = 0; __opcRefIdx < ").Append(valueExpression).AppendLine(".Length; __opcRefIdx++)");
            sb.Append(statementIndent).AppendLine("    {");
            sb.Append(statementIndent).Append("        ").Append(writerLocal).AppendLine(".WriteUniquePointerReferent(true);");
            sb.Append(statementIndent).AppendLine("    }");
            sb.Append(statementIndent).Append("    ").Append(writerLocal).AppendLine(".AlignTo(8);");
            sb.Append(statementIndent).Append("    foreach (var __opcV in ").Append(valueExpression).AppendLine(")");
            sb.Append(statementIndent).AppendLine("    {");
            sb.Append(statementIndent).Append("        global::Opc.Classic.Ndr.NdrVariantExtensions.WriteVariantElement(ref ").Append(writerLocal).AppendLine(", __opcV);");
            sb.Append(statementIndent).AppendLine("    }");
            sb.Append(statementIndent).AppendLine("}");
            return;
        }
        sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32((uint)(").Append(valueExpression).AppendLine("?.Length ?? 0));");
        sb.Append(statementIndent).Append("if (").Append(valueExpression).AppendLine(" is not null)");
        sb.Append(statementIndent).AppendLine("{");
        sb.Append(statementIndent).Append("    for (int __opcRefIdx = 0; __opcRefIdx < ").Append(valueExpression).AppendLine(".Length; __opcRefIdx++)");
        sb.Append(statementIndent).AppendLine("    {");
        sb.Append(statementIndent).Append("        ").Append(writerLocal).AppendLine(".WriteUniquePointerReferent(true);");
        sb.Append(statementIndent).AppendLine("    }");
        sb.Append(statementIndent).Append("    ").Append(writerLocal).AppendLine(".AlignTo(8);");
        sb.Append(statementIndent).Append("    foreach (var __opcV in ").Append(valueExpression).AppendLine(")");
        sb.Append(statementIndent).AppendLine("    {");
        sb.Append(statementIndent).Append("        global::Opc.Classic.Ndr.NdrVariantExtensions.WriteVariantElement(ref ").Append(writerLocal).AppendLine(", __opcV);");
        sb.Append(statementIndent).AppendLine("    }");
        sb.Append(statementIndent).AppendLine("}");
    }

    private static void EmitCodecReadLocal(StringBuilder sb, string statementIndent, string readerLocal, MethodModel method, string declaredType, string marshallingType, bool isOpcInterface, bool isUniquePointer, string? underlyingValueType, string targetLocal, bool fileTimeElements = false)
    {
        if (isOpcInterface)
        {
            string interfaceRead = isUniquePointer
                ? FormatMInterfacePointerReadExpression(readerLocal, declaredType)
                : FormatInterfaceReadExpression(readerLocal, declaredType);
            sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ").Append(interfaceRead).AppendLine(";");
            return;
        }

        // NDR unique pointer (DCE 1.1 §14.3.10): read 4-byte referent ID. If
        // non-zero, the value follows inline. We look up the inner codec by the
        // underlying value type for nullable parameters; for non-nullable
        // [OpcUniquePointer] parameters the C# type can't represent null so we
        // always read the value (since the client should always emit a non-null
        // referent for them).
        if (isUniquePointer)
        {
            string codecKey = underlyingValueType ?? marshallingType;
            if (TryGetCodec(codecKey, method.DeclaringNamespace, out var underlyingCodec) && !underlyingCodec.IsArray)
            {
                if (underlyingValueType is not null)
                {
                    string referentLocal = UniqueLocalName(method.ParameterNames, targetLocal + "Ref", readerLocal, targetLocal);
                    sb.Append(statementIndent).Append("uint ").Append(referentLocal).Append(" = ").Append(readerLocal).AppendLine(".ReadUInt32();");
                    sb.Append(statementIndent).Append(declaredType).Append(' ').Append(targetLocal).Append(" = ").Append(referentLocal).Append(" != 0u ? ").Append(FormatReadExpression(underlyingCodec, readerLocal)).AppendLine(" : null;");
                }
                else
                {
                    sb.Append(statementIndent).Append("_ = ").Append(readerLocal).AppendLine(".ReadUInt32();");
                    sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ").Append(FormatReadExpression(underlyingCodec, readerLocal)).AppendLine(";");
                }
                return;
            }
        }

        if (TryGetCodec(marshallingType, method.DeclaringNamespace, out var codec))
        {
            if (codec.IsArray)
            {
                // [in] T** unique-pointer-prefixed conformant array. Read the
                // 4-byte referent; if non-zero, read max_count + elements. If
                // zero (NULL), set the target to an empty array — the proxy
                // writes only the referent in that case (per DCE 1.1 §14.3.10).
                if (isUniquePointer)
                {
                    string refLocal = UniqueLocalName(method.ParameterNames, targetLocal + "Ref", readerLocal, targetLocal);
                    sb.Append(statementIndent).Append("uint ").Append(refLocal).Append(" = ").Append(readerLocal).AppendLine(".ReadUInt32();");
                    sb.Append(statementIndent).Append(codec.ArrayElementType).Append("[] ").Append(targetLocal).AppendLine(";");
                    sb.Append(statementIndent).Append("if (").Append(refLocal).AppendLine(" != 0u)");
                    sb.Append(statementIndent).AppendLine("{");
                    string innerTargetLocal = UniqueLocalName(method.ParameterNames, targetLocal + "Body", readerLocal, targetLocal, refLocal);
                    EmitArrayCodecReadLocal(sb, statementIndent + "    ", readerLocal, codec, method.ParameterNames, innerTargetLocal, fileTimeElements);
                    sb.Append(statementIndent).Append("    ").Append(targetLocal).Append(" = ").Append(innerTargetLocal).AppendLine(";");
                    sb.Append(statementIndent).AppendLine("}");
                    sb.Append(statementIndent).AppendLine("else");
                    sb.Append(statementIndent).AppendLine("{");
                    sb.Append(statementIndent).Append("    ").Append(targetLocal).Append(" = global::System.Array.Empty<").Append(codec.ArrayElementType).AppendLine(">();");
                    sb.Append(statementIndent).AppendLine("}");
                    return;
                }
                EmitArrayCodecReadLocal(sb, statementIndent, readerLocal, codec, method.ParameterNames, targetLocal, fileTimeElements);
                return;
            }

            sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ")
                .Append(FormatReadExpression(codec, readerLocal)).AppendLine(";");
            return;
        }

        sb.Append(statementIndent).Append(declaredType).Append(' ').Append(targetLocal).AppendLine(" = default!;");
    }

    private static void EmitArrayCodecReadLocal(StringBuilder sb, string statementIndent, string readerLocal, CodecEmitter codec, ImmutableArray<string> parameterNames, string targetLocal, bool fileTimeElements = false)
    {
        string countLocal = UniqueLocalName(parameterNames, targetLocal + "Count", readerLocal, targetLocal);
        string arrayLocal = UniqueLocalName(parameterNames, targetLocal + "Array", readerLocal, targetLocal, countLocal);
        string indexLocal = UniqueLocalName(parameterNames, targetLocal + "Index", readerLocal, targetLocal, countLocal, arrayLocal);
        string? deferredPileReadHelper = TryGetDeferredPileArrayHelperRead(codec.ArrayElementType);
        if (deferredPileReadHelper is not null)
        {
            sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ").Append(deferredPileReadHelper).Append("(ref ").Append(readerLocal).AppendLine(");");
            return;
        }

        sb.Append(statementIndent).Append("var ").Append(countLocal).Append(" = (int)").Append(readerLocal).AppendLine(".ReadUInt32();");
        sb.Append(statementIndent).Append("var ").Append(arrayLocal).Append(" = new ").Append(codec.ArrayElementType).Append('[').Append(countLocal).AppendLine("]; ");
        sb.Append(statementIndent).Append("for (int ").Append(indexLocal).Append(" = 0; ").Append(indexLocal).Append(" < ").Append(countLocal).Append("; ").Append(indexLocal).AppendLine("++)");
        sb.Append(statementIndent).AppendLine("{");
        // [OpcFileTimeElements] on a long[] array means the wire elements are
        // FILETIME (2x DWORD, 4-byte aligned 8 bytes) rather than NDR
        // hyper/int64 (8-byte aligned). Use ReadFileTime instead of ReadInt64
        // to match the proxy's WriteFileTime emit.
        string elemReadExpr = (fileTimeElements && string.Equals(codec.ArrayElementType, "global::System.Int64", System.StringComparison.Ordinal))
            ? readerLocal + ".ReadFileTime()"
            : FormatReadExpression(codec, readerLocal);
        sb.Append(statementIndent).Append("    ").Append(arrayLocal).Append('[').Append(indexLocal).Append("] = ").Append(elemReadExpr).AppendLine(";");
        sb.Append(statementIndent).AppendLine("}");
        sb.Append(statementIndent).Append("var ").Append(targetLocal).Append(" = ").Append(arrayLocal).AppendLine(";");
    }

    private static string? TryGetDeferredPileArrayHelperRead(string? arrayElementType) => arrayElementType switch
    {
        "global::Opc.Classic.Da.OpcItemDef" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcItemDefCodec.ReadConformantArray",
        "global::Opc.Classic.Da.OpcItemResult" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcItemResultCodec.ReadConformantArray",
        "global::Opc.Classic.Da.OpcItemAttributes" =>
            "global::Opc.Classic.Da.Ndr.NdrOpcItemAttributesCodec.ReadConformantArray",
        _ => null,
    };

    private static bool HasRequestValues(MethodModel method)
    {
        foreach (var parameter in method.Parameters)
        {
            if (parameter.IsRequestValue)
            {
                return true;
            }
        }

        return false;
    }

    private static int ResponseItemCount(MethodModel method)
    {
        int count = method.TaskReturnKind == TaskReturnKind.TaskOfT ? 1 : 0;
        foreach (var parameter in method.Parameters)
        {
            if (parameter.IsResponseValue)
            {
                count++;
            }
        }

        return count;
    }

    private static string DispatchMethodName(MethodModel method) => "Dispatch_" + method.Name;
    private static string CoreMethodName(MethodModel method) => "Dispatch_" + method.Name + "CoreAsync";
    private static string EncodeResponseName(MethodModel method) => "Encode_" + method.Name + "Response";
    private static string ReturnValueLocal(MethodModel method) => UniqueLocalName(method.ParameterNames, "__opcReturnValue");

    private static void AppendCoreParameters(StringBuilder sb, MethodModel method)
    {
        bool first = true;
        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsRequestValue)
            {
                continue;
            }

            AppendParameterSeparator(sb, ref first);
            sb.Append(parameter.DeclaredType).Append(' ').Append(parameter.Name);
        }

        AppendParameterSeparator(sb, ref first);
        sb.Append("global::System.Threading.CancellationToken cancellationToken");
    }

    private static void AppendCoreArguments(StringBuilder sb, MethodModel method)
    {
        bool first = true;
        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsRequestValue)
            {
                continue;
            }

            AppendParameterSeparator(sb, ref first);
            sb.Append(parameter.Name);
        }

        AppendParameterSeparator(sb, ref first);
        sb.Append("cancellationToken");
    }

    private static void AppendEncodeParameters(StringBuilder sb, MethodModel method)
    {
        bool first = true;
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            AppendParameterSeparator(sb, ref first);
            sb.Append(method.TaskResultType).Append(' ').Append(ReturnValueLocal(method));
        }

        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsResponseValue)
            {
                continue;
            }

            AppendParameterSeparator(sb, ref first);
            sb.Append(parameter.DeclaredType).Append(' ').Append(parameter.Name);
        }
    }

    private static void AppendEncodeArguments(StringBuilder sb, MethodModel method)
    {
        bool first = true;
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            AppendParameterSeparator(sb, ref first);
            sb.Append(ReturnValueLocal(method));
        }

        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsResponseValue)
            {
                continue;
            }

            AppendParameterSeparator(sb, ref first);
            sb.Append(parameter.Name);
        }
    }

    private static void AppendParameterSeparator(StringBuilder sb, ref bool first)
    {
        if (!first)
        {
            sb.Append(", ");
        }

        first = false;
    }

    private static string? FindUnsupportedMarshallingType(
        IEnumerable<ParameterModel> parameters,
        TaskReturnKind taskReturnKind,
        string? taskResultMarshallingType,
        bool taskResultIsOpcInterface,
        string? declaringNamespace,
        out UnsupportedMarshallingKind unsupportedMarshallingKind,
        out string? unsupportedParameterName)
    {
        unsupportedMarshallingKind = UnsupportedMarshallingKind.None;
        unsupportedParameterName = null;
        foreach (var parameter in parameters)
        {
            if (parameter.IsCancellationToken)
            {
                continue;
            }

            if (parameter.IsRequestValue && !CanReadType(parameter.MarshallingType, parameter.IsOpcInterface, declaringNamespace))
            {
                if (parameter.IsUniquePointer
                    && parameter.UnderlyingValueType is { } underlyingRead
                    && CanReadType(underlyingRead, isOpcInterface: false, declaringNamespace))
                {
                    continue;
                }
                unsupportedMarshallingKind = UnsupportedMarshallingKind.Parameter;
                unsupportedParameterName = parameter.Name;
                return parameter.MarshallingType;
            }

            if (parameter.IsResponseValue && !CanWriteType(parameter.MarshallingType, parameter.IsOpcInterface, declaringNamespace))
            {
                if (parameter.IsUniquePointer
                    && parameter.UnderlyingValueType is { } underlyingWrite
                    && CanWriteType(underlyingWrite, isOpcInterface: false, declaringNamespace))
                {
                    continue;
                }
                unsupportedMarshallingKind = UnsupportedMarshallingKind.Response;
                unsupportedParameterName = parameter.Name;
                return parameter.MarshallingType;
            }
        }

        if (taskReturnKind == TaskReturnKind.TaskOfT &&
            (taskResultMarshallingType is null || !CanWriteType(taskResultMarshallingType, taskResultIsOpcInterface, declaringNamespace)))
        {
            unsupportedMarshallingKind = UnsupportedMarshallingKind.Response;
            return taskResultMarshallingType ?? "<unknown>";
        }

        return null;
    }

    private static bool CanReadType(string typeName, bool isOpcInterface, string? declaringNamespace) =>
        isOpcInterface || TryGetCodec(typeName, declaringNamespace, out _);

    private static bool CanWriteType(string typeName, bool isOpcInterface, string? declaringNamespace) =>
        !isOpcInterface && TryGetCodec(typeName, declaringNamespace, out _);

    private static bool TryGetCodec(string typeName, string? declaringNamespace, out CodecEmitter codec)
    {
        if (TryGetArrayElementTypeName(typeName, out string elementTypeName) &&
            !TryGetArrayElementTypeName(elementTypeName, out _) &&
            TryGetCodec(elementTypeName, declaringNamespace, out var elementCodec) &&
            !elementCodec.IsArray)
        {
            codec = CodecEmitter.Array(elementTypeName, elementCodec);
            return true;
        }

        if (string.Equals(typeName, "global::Opc.Classic.OpcServerStatus", System.StringComparison.Ordinal))
        {
            if (IsAeNamespace(declaringNamespace))
            {
                codec = AeServerStatusCodec;
                return true;
            }

            if (IsHdaNamespace(declaringNamespace))
            {
                codec = HdaServerStatusCodec;
                return true;
            }
        }

        return Codecs.TryGetValue(typeName, out codec);
    }

    private static bool TryGetArrayElementTypeName(string typeName, out string elementTypeName)
    {
        if (typeName.EndsWith("[]", System.StringComparison.Ordinal))
        {
            elementTypeName = typeName.Substring(0, typeName.Length - 2);
            return true;
        }

        elementTypeName = string.Empty;
        return false;
    }

    private static CodecEmitter StaticCodec(string codecClassName) =>
        new CodecEmitter(codecClassName + ".Write(ref {Writer}, {Param})", codecClassName + ".Read(ref {Reader})");

    private static string FormatWriteExpression(CodecEmitter codec, string writerLocal, string parameterName) =>
        codec.WriteExpression.Replace("{Writer}", writerLocal).Replace("{Param}", parameterName);

    private static string FormatReadExpression(CodecEmitter codec, string readerLocal) =>
        codec.ReadExpression.Replace("{Reader}", readerLocal);

    private static string FormatInterfaceReadExpression(string readerLocal, string declaredType)
    {
        string readExpression = "global::Opc.Classic.Dcom.OpcInterfaceRefCodec.Read(ref " + readerLocal + ")";
        if (string.Equals(declaredType, "global::Opc.Classic.Dcom.IOpcInterfaceRef", System.StringComparison.Ordinal))
        {
            return readExpression;
        }

        return "(" + declaredType + ")(object)" + readExpression;
    }

    private static string FormatMInterfacePointerReadExpression(string readerLocal, string declaredType)
    {
        string readExpression = "global::Opc.Classic.Dcom.OpcMInterfacePointerCodec.Read(ref " + readerLocal + ")!";
        if (string.Equals(declaredType, "global::Opc.Classic.Dcom.IOpcInterfaceRef", System.StringComparison.Ordinal))
        {
            return readExpression;
        }

        return "(" + declaredType + ")(object)" + readExpression;
    }

    private static bool IsAeNamespace(string? declaringNamespace) =>
        string.Equals(declaringNamespace, "Opc.Classic.Ae", System.StringComparison.Ordinal) ||
        (declaringNamespace != null && declaringNamespace.StartsWith("Opc.Classic.Ae.", System.StringComparison.Ordinal));

    private static bool IsHdaNamespace(string? declaringNamespace) =>
        string.Equals(declaringNamespace, "Opc.Classic.Hda", System.StringComparison.Ordinal) ||
        (declaringNamespace != null && declaringNamespace.StartsWith("Opc.Classic.Hda.", System.StringComparison.Ordinal));

    private static TaskReturnKind ClassifyTaskReturn(ITypeSymbol returnType, out string? taskResultType, out string? taskResultMarshallingType)
    {
        taskResultType = null;
        taskResultMarshallingType = null;
        if (returnType is not INamedTypeSymbol namedType ||
            !string.Equals(namedType.Name, "Task", System.StringComparison.Ordinal) ||
            !string.Equals(namedType.ContainingNamespace.ToDisplayString(), "System.Threading.Tasks", System.StringComparison.Ordinal))
        {
            return TaskReturnKind.Unsupported;
        }

        if (namedType.Arity == 0)
        {
            return TaskReturnKind.Task;
        }

        if (namedType.Arity == 1)
        {
            taskResultType = namedType.TypeArguments[0].ToDisplayString(TypeDisplayFormat);
            taskResultMarshallingType = namedType.TypeArguments[0].ToDisplayString(CodecTypeDisplayFormat);
            return TaskReturnKind.TaskOfT;
        }

        return TaskReturnKind.Unsupported;
    }

    private static string? UnsupportedSignatureReason(IMethodSymbol method, TaskReturnKind taskReturnKind)
    {
        if (method.TypeParameters.Length > 0)
        {
            return "generic methods are not supported";
        }

        if (taskReturnKind == TaskReturnKind.Unsupported)
        {
            return "method must return System.Threading.Tasks.Task or System.Threading.Tasks.Task<T>";
        }

        return null;
    }

    private static bool HasOpcInterfaceAttribute(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (string.Equals(fullName, OpcInterfaceAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool TryGetOpcMethodOpnum(IMethodSymbol method, out int opnum)
    {
        foreach (var attr in method.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (!string.Equals(fullName, OpcMethodAttributeFullName, System.StringComparison.Ordinal))
            {
                continue;
            }

            if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is int value)
            {
                opnum = value;
                return true;
            }
        }

        opnum = 0;
        return false;
    }

    private static bool IsOpcInterfaceType(ITypeSymbol symbol) =>
        symbol is INamedTypeSymbol { TypeKind: TypeKind.Interface } namedType && HasOpcInterfaceAttribute(namedType);

    private static bool TryGetTaskResultSymbol(ITypeSymbol returnType, out ITypeSymbol resultType)
    {
        if (returnType is INamedTypeSymbol { Name: "Task", Arity: 1 } namedType &&
            string.Equals(namedType.ContainingNamespace.ToDisplayString(), "System.Threading.Tasks", System.StringComparison.Ordinal))
        {
            resultType = namedType.TypeArguments[0];
            return true;
        }

        resultType = returnType;
        return false;
    }

    private static string TypeParameterList(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.Append('<');
        for (int i = 0; i < typeParameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(typeParameters[i].Name);
        }

        sb.Append('>');
        return sb.ToString();
    }

    private static string ConstraintClauses(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var typeParameter in typeParameters)
        {
            string constraints = Constraints(typeParameter);
            if (constraints.Length > 0)
            {
                sb.Append(" where ").Append(typeParameter.Name).Append(" : ").Append(constraints);
            }
        }

        return sb.ToString();
    }

    private static string Constraints(ITypeParameterSymbol typeParameter)
    {
        var constraints = new List<string>();
        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("unmanaged");
        }
        else if (typeParameter.HasValueTypeConstraint)
        {
            constraints.Add("struct");
        }
        else if (typeParameter.HasReferenceTypeConstraint)
        {
            constraints.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
        }
        else if (typeParameter.HasNotNullConstraint)
        {
            constraints.Add("notnull");
        }

        foreach (var constraintType in typeParameter.ConstraintTypes)
        {
            constraints.Add(constraintType.ToDisplayString(TypeDisplayFormat));
        }

        if (typeParameter.HasConstructorConstraint && !typeParameter.HasValueTypeConstraint && !typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("new()");
        }

        return string.Join(", ", constraints);
    }

    private static string ToPascalCase(string name)
    {
        string unescaped = name.StartsWith("@", System.StringComparison.Ordinal) ? name.Substring(1) : name;
        if (unescaped.Length == 0)
        {
            return "Value";
        }

        return char.ToUpperInvariant(unescaped[0]) + unescaped.Substring(1);
    }

    private static string UniqueLocalName(ImmutableArray<string> parameterNames, string preferredName, params string[] additionalNames)
    {
        string candidate = preferredName;
        int suffix = 0;
        while (NameMatches(parameterNames, candidate) || NameMatches(additionalNames, candidate))
        {
            suffix++;
            candidate = preferredName + suffix.ToString(CultureInfo.InvariantCulture);
        }

        return candidate;
    }

    private static bool NameMatches(IEnumerable<string> names, string candidate)
    {
        foreach (var name in names)
        {
            if (string.Equals(name, candidate, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string AccessibilityKeyword(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.NotApplicable => "internal",
        _ => "internal",
    };

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    private enum UnsupportedMarshallingKind
    {
        None,
        Parameter,
        Response,
    }

    private enum TaskReturnKind
    {
        Unsupported,
        Task,
        TaskOfT,
    }

    private readonly struct CodecEmitter
    {
        public CodecEmitter(string writeExpression, string readExpression)
            : this(writeExpression, readExpression, null)
        {
        }

        private CodecEmitter(string writeExpression, string readExpression, string? arrayElementType)
        {
            WriteExpression = writeExpression;
            ReadExpression = readExpression;
            ArrayElementType = arrayElementType;
        }

        public string WriteExpression { get; }
        public string ReadExpression { get; }
        public string? ArrayElementType { get; }
        public bool IsArray => ArrayElementType is not null;

        public static CodecEmitter Array(string elementTypeName, CodecEmitter elementCodec) =>
            new CodecEmitter(elementCodec.WriteExpression, elementCodec.ReadExpression, elementTypeName);
    }

    private sealed class ParameterModel
    {
        public ParameterModel(string name, string resultMemberName, string declaredType, string marshallingType, bool isCancellationToken, RefKind refKind, bool isOpcInterface, bool isUniquePointer = false, string? underlyingValueType = null, bool emitArrayCount = false, bool fileTimeElements = false, bool variantElements = false, bool refString = false, bool deferredElements = false)
        {
            Name = name;
            ResultMemberName = resultMemberName;
            DeclaredType = declaredType;
            MarshallingType = marshallingType;
            IsCancellationToken = isCancellationToken;
            RefKind = refKind;
            IsOpcInterface = isOpcInterface;
            IsUniquePointer = isUniquePointer;
            UnderlyingValueType = underlyingValueType;
            EmitArrayCount = emitArrayCount;
            FileTimeElements = fileTimeElements;
            VariantElements = variantElements;
            RefString = refString;
            DeferredElements = deferredElements;
        }

        public string Name { get; }
        public string ResultMemberName { get; }
        public string DeclaredType { get; }
        public string MarshallingType { get; }
        public bool IsCancellationToken { get; }
        public RefKind RefKind { get; }
        public bool IsOpcInterface { get; }
        public bool IsUniquePointer { get; }
        public string? UnderlyingValueType { get; }
        public bool EmitArrayCount { get; }
        public bool FileTimeElements { get; }
        public bool VariantElements { get; }
        /// <summary>
        /// True when [OpcRefString] is present — bare conformant string with no referent.
        /// </summary>
        public bool RefString { get; }
        /// <summary>
        /// True when [OpcDeferredElements] is present: the array decoder expects per-element referent IDs followed by deferred per-element
        /// string bodies (matching the proxy's two-pass write).
        /// </summary>
        public bool DeferredElements { get; }
        public bool IsRequestValue => !IsCancellationToken && RefKind != RefKind.Out;
        public bool IsResponseValue => !IsCancellationToken && (RefKind == RefKind.Out || RefKind == RefKind.Ref);
    }

    private sealed class MethodModel
    {
        public MethodModel(
            string name,
            int opnum,
            ImmutableArray<ParameterModel> parameters,
            ImmutableArray<string> parameterNames,
            TaskReturnKind taskReturnKind,
            string? taskResultType,
            string? taskResultMarshallingType,
            bool taskResultIsOpcInterface,
            bool taskResultIsUniquePointer,
            string? unsupportedSignatureReason,
            string? unsupportedMarshallingType,
            UnsupportedMarshallingKind unsupportedMarshallingKind,
            string? unsupportedParameterName,
            string? cancellationTokenParameterName,
            string? declaringNamespace,
            Location location)
        {
            Name = name;
            Opnum = opnum;
            Parameters = parameters;
            ParameterNames = parameterNames;
            TaskReturnKind = taskReturnKind;
            TaskResultType = taskResultType;
            TaskResultMarshallingType = taskResultMarshallingType;
            TaskResultIsOpcInterface = taskResultIsOpcInterface;
            TaskResultIsUniquePointer = taskResultIsUniquePointer;
            UnsupportedSignatureReason = unsupportedSignatureReason;
            UnsupportedMarshallingType = unsupportedMarshallingType;
            UnsupportedMarshallingKind = unsupportedMarshallingKind;
            UnsupportedParameterName = unsupportedParameterName;
            CancellationTokenParameterName = cancellationTokenParameterName;
            DeclaringNamespace = declaringNamespace;
            Location = location;
            IsFullyMarshallable = unsupportedSignatureReason is null && unsupportedMarshallingType is null;
        }

        public string Name { get; }
        public int Opnum { get; }
        public ImmutableArray<ParameterModel> Parameters { get; }
        public ImmutableArray<string> ParameterNames { get; }
        public TaskReturnKind TaskReturnKind { get; }
        public string? TaskResultType { get; }
        public string? TaskResultMarshallingType { get; }
        public bool TaskResultIsOpcInterface { get; }
        /// <summary>
        /// True when the Task&lt;T&gt; result wire-encodes as a unique pointer (referent + value).
        /// </summary>
        public bool TaskResultIsUniquePointer { get; }
        public string? UnsupportedSignatureReason { get; }
        public string? UnsupportedMarshallingType { get; }
        public UnsupportedMarshallingKind UnsupportedMarshallingKind { get; }
        public string? UnsupportedParameterName { get; }
        public string? CancellationTokenParameterName { get; }
        public string? DeclaringNamespace { get; }
        public Location Location { get; }
        public bool IsFullyMarshallable { get; }
    }

    private sealed class InterfaceModel
    {
        public InterfaceModel(string fullyQualifiedName, string? @namespace, string name, Accessibility accessibility, string typeParameterList, string typeParameterConstraints, bool isPartial, bool hasOpcInterfaceAttribute, Location location, ImmutableArray<MethodModel> methods)
        {
            FullyQualifiedName = fullyQualifiedName;
            Namespace = @namespace;
            Name = name;
            Accessibility = accessibility;
            TypeParameterList = typeParameterList;
            TypeParameterConstraints = typeParameterConstraints;
            IsPartial = isPartial;
            HasOpcInterfaceAttribute = hasOpcInterfaceAttribute;
            Location = location;
            Methods = methods;
        }

        public string FullyQualifiedName { get; }
        public string? Namespace { get; }
        public string Name { get; }
        public Accessibility Accessibility { get; }
        public string TypeParameterList { get; }
        public string TypeParameterConstraints { get; }
        public bool IsPartial { get; }
        public bool HasOpcInterfaceAttribute { get; }
        public Location Location { get; }
        public ImmutableArray<MethodModel> Methods { get; }
    }
}
