//
// SPDX-License-Identifier: EPL-1.0
// Copyright (c) 2026 OPC Classic .NET Contributors
//
// Phase 4A.1 skeleton — proves the source-generator toolchain works end-to-end.
// Subsequent generators (DispatchGenerator, MarshallerGenerator, GuidTableGenerator,
// JsonContextGenerator) live in sibling files under this same assembly.
//

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace OpcClassic.Generators;

/// <summary>
/// Emits <c>OpcClassic.Generators.OpcClassicGeneratorMarker</c> into every
/// consuming project as a smoke-test that the generator pipeline is alive.
/// Future per-feature generators are sibling <see cref="IIncrementalGenerator"/>
/// implementations in this same assembly.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OpcClassicMarkerGenerator : IIncrementalGenerator
{
    private const string GeneratedSource = @"// <auto-generated by OpcClassic.Generators />
#nullable enable

namespace OpcClassic.Generators
{
    /// <summary>
    /// Smoke-test marker emitted into every project that references
    /// <c>OpcClassic.Generators</c> as an analyzer. Confirms the source-generator
    /// pipeline is wired correctly end-to-end.
    /// </summary>
    public static class OpcClassicGeneratorMarker
    {
        /// <summary>Tracks the generator surface as it evolves. Bumped per phase.</summary>
        public const string Version = ""0.1.0-dev"";

        /// <summary>Human-readable description of the current generator surface.</summary>
        public const string Description = ""Phase 4A.1 skeleton (smoke test only)"";
    }
}
";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // RegisterPostInitializationOutput emits unconditional source — runs once
        // per compilation, before any syntax/symbol-driven generators see input.
        // Perfect for emitting marker types that future generators will reference.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: "OpcClassicGeneratorMarker.g.cs",
                sourceText: SourceText.From(GeneratedSource, Encoding.UTF8)));
    }
}
