//
// SPDX-License-Identifier: EPL-1.0
// Copyright (c) 2026 OPC Classic .NET Contributors
//
// Phase 4A.6b — call-shim emission scaffold.
//

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace OpcClassic.Generators;

/// <summary>
/// Source generator that handles <c>[GenerateOpcProxy]</c>-annotated partial
/// OPC interface projections. Emits a sibling client proxy scaffold whose
/// method bodies are filled in by later NDR marshaling phases.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OpcProxyGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "OpcClassic.Generators";
    private const string AttributeName = "GenerateOpcProxyAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;
    private const string OpcInterfaceAttributeFullName = AttributeNamespace + ".OpcInterfaceAttribute";

    private const string AttributeSource = @"// <auto-generated by OpcClassic.Generators.OpcProxyGenerator />
#nullable enable

namespace OpcClassic.Generators
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class GenerateOpcProxyAttribute : global::System.Attribute { }
}
";

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly DiagnosticDescriptor NotPartialDescriptor = new(
        id: "OPCGEN004",
        title: "OpcProxy target must be partial",
        messageFormat: "Interface '{0}' is decorated with [GenerateOpcProxy] but is not declared partial",
        category: "OpcClassic.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingOpcInterfaceDescriptor = new(
        id: "OPCGEN005",
        title: "OpcProxy target should be decorated with OpcInterface",
        messageFormat: "Interface '{0}' is decorated with [GenerateOpcProxy] but is not decorated with [OpcInterface]",
        category: "OpcClassic.Generators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: "GenerateOpcProxyAttribute.g.cs",
                sourceText: SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: AttributeFullName,
            predicate: static (node, _) => node is InterfaceDeclarationSyntax,
            transform: static (ctx, _) => Transform(ctx));

        context.RegisterSourceOutput(candidates, Emit);
    }

    private static InterfaceModel? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (ctx.TargetNode is not InterfaceDeclarationSyntax syntax)
        {
            return null;
        }

        bool isPartial = false;
        foreach (var modifier in syntax.Modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword))
            {
                isPartial = true;
                break;
            }
        }

        return new InterfaceModel(
            fullyQualifiedName: symbol.ToDisplayString(TypeDisplayFormat),
            @namespace: symbol.ContainingNamespace?.IsGlobalNamespace == false
                ? symbol.ContainingNamespace!.ToDisplayString()
                : null,
            name: symbol.Name,
            accessibility: symbol.DeclaredAccessibility,
            typeParameterList: TypeParameterList(symbol.TypeParameters),
            typeParameterConstraints: ConstraintClauses(symbol.TypeParameters),
            isPartial: isPartial,
            hasOpcInterfaceAttribute: HasOpcInterfaceAttribute(symbol),
            location: syntax.Identifier.GetLocation(),
            methods: CollectMethods(symbol));
    }

    private static ImmutableArray<MethodModel> CollectMethods(INamedTypeSymbol interfaceSymbol)
    {
        var builder = ImmutableArray.CreateBuilder<MethodModel>();
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol { MethodKind: MethodKind.Ordinary } method)
            {
                builder.Add(CreateMethodModel(method));
            }
        }

        return builder.ToImmutable();
    }

    private static MethodModel CreateMethodModel(IMethodSymbol method)
    {
        var outParameters = ImmutableArray.CreateBuilder<string>();
        foreach (var parameter in method.Parameters)
        {
            if (parameter.RefKind == RefKind.Out)
            {
                outParameters.Add(EscapeIdentifier(parameter.Name));
            }
        }

        return new MethodModel(
            name: method.Name,
            returnType: method.ReturnType.ToDisplayString(TypeDisplayFormat),
            typeParameterList: TypeParameterList(method.TypeParameters),
            parameterList: ParameterList(method.Parameters),
            constraintClauses: ConstraintClauses(method.TypeParameters),
            outParameters: outParameters.ToImmutable());
    }

    private static void Emit(SourceProductionContext spc, InterfaceModel? maybeModel)
    {
        if (maybeModel is null)
        {
            return;
        }

        InterfaceModel model = maybeModel;

        if (!model.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(NotPartialDescriptor, model.Location, model.FullyQualifiedName));
            return;
        }

        if (!model.HasOpcInterfaceAttribute)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingOpcInterfaceDescriptor, model.Location, model.FullyQualifiedName));
        }

        var sb = new StringBuilder(1024);
        sb.AppendLine("// <auto-generated by OpcClassic.Generators.OpcProxyGenerator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0414 // _channel is captured now and read by later call-shim phases.");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        string indent = hasNamespace ? "    " : string.Empty;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string accessibility = AccessibilityKeyword(model.Accessibility);
        string proxyName = model.Name + "_ClientProxy";
        sb.Append(indent).Append(accessibility).Append(" partial class ").Append(proxyName).Append(model.TypeParameterList)
            .Append(" : ").Append(model.Name).Append(model.TypeParameterList).Append(model.TypeParameterConstraints).AppendLine();
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    private readonly global::OpcClassic.ICallChannel _channel;");
        sb.AppendLine();
        sb.Append(indent).Append("    public ").Append(proxyName).Append("(global::OpcClassic.ICallChannel channel)").AppendLine();
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        _channel = channel ?? throw new global::System.ArgumentNullException(nameof(channel));");
        sb.Append(indent).AppendLine("    }");

        foreach (var method in model.Methods)
        {
            EmitMethod(sb, indent, model.Name, method);
        }

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        string hint = model.FullyQualifiedName.Replace("global::", string.Empty).Replace("<", "_").Replace(">", "_") + ".OpcProxy.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMethod(StringBuilder sb, string indent, string interfaceName, MethodModel method)
    {
        sb.AppendLine();
        sb.Append(indent).Append("    public ").Append(method.ReturnType).Append(' ').Append(method.Name)
            .Append(method.TypeParameterList).Append('(').Append(method.ParameterList).Append(')')
            .Append(method.ConstraintClauses).AppendLine();
        sb.Append(indent).AppendLine("    {");
        foreach (var parameterName in method.OutParameters)
        {
            sb.Append(indent).Append("        ").Append(parameterName).AppendLine(" = default!;");
        }

        sb.Append(indent).Append("        throw new global::System.NotImplementedException(")
            .Append("\"Phase 6B/7B/8B - per-method shim for '").Append(interfaceName).Append('.')
            .Append(method.Name).Append("' TBD\");").AppendLine();
        sb.Append(indent).AppendLine("    }");
    }

    private static string ParameterList(ImmutableArray<IParameterSymbol> parameters)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            IParameterSymbol parameter = parameters[i];
            if (parameter.IsParams)
            {
                sb.Append("params ");
            }

            sb.Append(parameter.RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => string.Empty,
            });

            sb.Append(parameter.Type.ToDisplayString(TypeDisplayFormat)).Append(' ').Append(EscapeIdentifier(parameter.Name));

            if (parameter.HasExplicitDefaultValue)
            {
                sb.Append(" = ").Append(FormatDefaultValue(parameter));
            }
        }

        return sb.ToString();
    }

    private static string TypeParameterList(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.Append('<');
        for (int i = 0; i < typeParameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(typeParameters[i].Name);
        }

        sb.Append('>');
        return sb.ToString();
    }

    private static string ConstraintClauses(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var typeParameter in typeParameters)
        {
            string constraints = Constraints(typeParameter);
            if (constraints.Length > 0)
            {
                sb.Append(" where ").Append(typeParameter.Name).Append(" : ").Append(constraints);
            }
        }

        return sb.ToString();
    }

    private static string Constraints(ITypeParameterSymbol typeParameter)
    {
        var constraints = new List<string>();
        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("unmanaged");
        }
        else if (typeParameter.HasValueTypeConstraint)
        {
            constraints.Add("struct");
        }
        else if (typeParameter.HasReferenceTypeConstraint)
        {
            constraints.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
        }
        else if (typeParameter.HasNotNullConstraint)
        {
            constraints.Add("notnull");
        }

        foreach (var constraintType in typeParameter.ConstraintTypes)
        {
            constraints.Add(constraintType.ToDisplayString(TypeDisplayFormat));
        }

        if (typeParameter.HasConstructorConstraint && !typeParameter.HasValueTypeConstraint && !typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("new()");
        }

        return string.Join(", ", constraints);
    }

    private static string FormatDefaultValue(IParameterSymbol parameter)
    {
        object? value = parameter.ExplicitDefaultValue;
        if (value is null)
        {
            return parameter.Type.IsValueType && parameter.NullableAnnotation != NullableAnnotation.Annotated ? "default" : "null";
        }

        if (parameter.Type.TypeKind == TypeKind.Enum)
        {
            return "(" + parameter.Type.ToDisplayString(TypeDisplayFormat) + ")" +
                System.Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
        }

        return value switch
        {
            string text => SymbolDisplay.FormatLiteral(text, quote: true),
            char ch => SymbolDisplay.FormatLiteral(ch, quote: true),
            bool flag => flag ? "true" : "false",
            sbyte number => number.ToString(CultureInfo.InvariantCulture),
            byte number => number.ToString(CultureInfo.InvariantCulture),
            short number => number.ToString(CultureInfo.InvariantCulture),
            ushort number => number.ToString(CultureInfo.InvariantCulture),
            int number => number.ToString(CultureInfo.InvariantCulture),
            uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number => number.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            _ => "default",
        };
    }

    private static bool HasOpcInterfaceAttribute(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (string.Equals(fullName, OpcInterfaceAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string AccessibilityKeyword(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.NotApplicable => "internal",
        _ => "internal",
    };

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    private sealed class MethodModel
    {
        public MethodModel(string name, string returnType, string typeParameterList, string parameterList, string constraintClauses, ImmutableArray<string> outParameters)
        {
            Name = name;
            ReturnType = returnType;
            TypeParameterList = typeParameterList;
            ParameterList = parameterList;
            ConstraintClauses = constraintClauses;
            OutParameters = outParameters;
        }

        public string Name { get; }
        public string ReturnType { get; }
        public string TypeParameterList { get; }
        public string ParameterList { get; }
        public string ConstraintClauses { get; }
        public ImmutableArray<string> OutParameters { get; }
    }

    private sealed class InterfaceModel
    {
        public InterfaceModel(string fullyQualifiedName, string? @namespace, string name, Accessibility accessibility, string typeParameterList, string typeParameterConstraints, bool isPartial, bool hasOpcInterfaceAttribute, Location location, ImmutableArray<MethodModel> methods)
        {
            FullyQualifiedName = fullyQualifiedName;
            Namespace = @namespace;
            Name = name;
            Accessibility = accessibility;
            TypeParameterList = typeParameterList;
            TypeParameterConstraints = typeParameterConstraints;
            IsPartial = isPartial;
            HasOpcInterfaceAttribute = hasOpcInterfaceAttribute;
            Location = location;
            Methods = methods;
        }

        public string FullyQualifiedName { get; }
        public string? Namespace { get; }
        public string Name { get; }
        public Accessibility Accessibility { get; }
        public string TypeParameterList { get; }
        public string TypeParameterConstraints { get; }
        public bool IsPartial { get; }
        public bool HasOpcInterfaceAttribute { get; }
        public Location Location { get; }
        public ImmutableArray<MethodModel> Methods { get; }
    }
}
