//
// SPDX-License-Identifier: EPL-1.0
// Copyright (c) 2026 OPC Classic .NET Contributors
//
// Phase 4A.6b — call-shim emission scaffold.
//

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace OpcClassic.Generators;

/// <summary>
/// Source generator that handles <c>[GenerateOpcProxy]</c>-annotated partial
/// OPC interface projections. Emits a sibling client proxy scaffold whose
/// method bodies are filled in by later NDR marshaling phases.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OpcProxyGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "OpcClassic.Generators";
    private const string AttributeName = "GenerateOpcProxyAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;
    private const string OpcInterfaceAttributeFullName = AttributeNamespace + ".OpcInterfaceAttribute";
    private const string OpcMethodAttributeFullName = AttributeNamespace + ".OpcMethodAttribute";

    private const string AttributeSource = @"// <auto-generated by OpcClassic.Generators.OpcProxyGenerator />
#nullable enable

namespace OpcClassic.Generators
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class GenerateOpcProxyAttribute : global::System.Attribute { }
}
";

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly SymbolDisplayFormat CodecTypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            (SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
             SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier) &
            ~SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly CodecEmitter AeServerStatusCodec = StaticCodec(
        "global::OpcClassic.Ae.Ndr.NdrOpcEventServerStatusCodec");

    private static readonly Dictionary<string, CodecEmitter> Codecs =
        new(System.StringComparer.Ordinal)
        {
            { "global::System.Int32", new CodecEmitter("{Writer}.WriteInt32({Param})", "{Reader}.ReadInt32()") },
            { "global::System.UInt32", new CodecEmitter("{Writer}.WriteUInt32({Param})", "{Reader}.ReadUInt32()") },
            { "global::System.Int16", new CodecEmitter("{Writer}.WriteInt16({Param})", "{Reader}.ReadInt16()") },
            { "global::System.UInt16", new CodecEmitter("{Writer}.WriteUInt16({Param})", "{Reader}.ReadUInt16()") },
            { "global::System.Int64", new CodecEmitter("{Writer}.WriteInt64({Param})", "{Reader}.ReadInt64()") },
            { "global::System.UInt64", new CodecEmitter("{Writer}.WriteUInt64({Param})", "{Reader}.ReadUInt64()") },
            { "global::System.Single", new CodecEmitter("{Writer}.WriteSingle({Param})", "{Reader}.ReadSingle()") },
            { "global::System.Double", new CodecEmitter("{Writer}.WriteDouble({Param})", "{Reader}.ReadDouble()") },
            { "global::System.Boolean", new CodecEmitter("{Writer}.WriteInt32({Param} ? -1 : 0)", "({Reader}.ReadInt32() != 0)") },
            { "global::System.Guid", new CodecEmitter("{Writer}.WriteGuid({Param})", "{Reader}.ReadGuid()") },
            { "global::System.String", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "global::System.String?", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "string", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "string?", new CodecEmitter("{Writer}.WriteUnicodeStringPtr({Param})", "{Reader}.ReadUnicodeStringPtr()!") },
            { "global::OpcClassic.OpcVariant", new CodecEmitter("global::OpcClassic.Ndr.NdrVariantExtensions.WriteVariant(ref {Writer}, {Param})", "global::OpcClassic.Ndr.NdrVariantExtensions.ReadVariant(ref {Reader})") },
            { "global::OpcClassic.OpcSafeArray", new CodecEmitter("global::OpcClassic.Ndr.NdrSafeArrayExtensions.WriteSafeArray(ref {Writer}, {Param})", "global::OpcClassic.Ndr.NdrSafeArrayExtensions.ReadSafeArray(ref {Reader})") },
            { "global::OpcClassic.OpcServerStatus", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcServerStatusCodec") },
            { "global::OpcClassic.Da.OpcBrowseElementResult", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcBrowseElementCodec") },
            { "global::OpcClassic.Da.OpcItemAttributes", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcItemAttributesCodec") },
            { "global::OpcClassic.Da.OpcItemDef", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcItemDefCodec") },
            { "global::OpcClassic.Da.OpcGroupState", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcGroupStateCodec") },
            { "global::OpcClassic.Da.OpcItemProperties", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcItemPropertiesCodec") },
            { "global::OpcClassic.Da.OpcItemPropertyResult", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcItemPropertyCodec") },
            { "global::OpcClassic.Da.OpcItemResult", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcItemResultCodec") },
            { "global::OpcClassic.Da.OpcItemState", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcItemStateCodec") },
            { "global::OpcClassic.Da.OpcItemVqt", StaticCodec("global::OpcClassic.Da.Ndr.NdrOpcItemVqtCodec") },
            { "global::OpcClassic.Ae.OpcConditionState", StaticCodec("global::OpcClassic.Ae.Ndr.NdrOpcConditionStateCodec") },
            { "global::OpcClassic.Ae.OpcEventNotification", StaticCodec("global::OpcClassic.Ae.Ndr.NdrOpcEventNotificationCodec") },
            { "global::OpcClassic.Batch.OpcBatchSummary", StaticCodec("global::OpcClassic.Batch.Ndr.NdrOpcBatchSummaryCodec") },
            { "global::OpcClassic.Batch.OpcBatchSummaryFilter", StaticCodec("global::OpcClassic.Batch.Ndr.NdrOpcBatchSummaryFilterCodec") },
            { "global::OpcClassic.Hda.OpcHdaAnnotation", StaticCodec("global::OpcClassic.Hda.Ndr.NdrOpcHdaAnnotationCodec") },
            { "global::OpcClassic.Hda.OpcHdaAttribute", StaticCodec("global::OpcClassic.Hda.Ndr.NdrOpcHdaAttributeCodec") },
            { "global::OpcClassic.Hda.OpcHdaItem", StaticCodec("global::OpcClassic.Hda.Ndr.NdrOpcHdaItemCodec") },
            { "global::OpcClassic.Hda.OpcHdaModifiedItem", StaticCodec("global::OpcClassic.Hda.Ndr.NdrOpcHdaModifiedItemCodec") },
            { "global::OpcClassic.Hda.OpcHdaTime", StaticCodec("global::OpcClassic.Hda.Ndr.NdrOpcHdaTimeCodec") },
        };

    private static readonly DiagnosticDescriptor NotPartialDescriptor = new(
        id: "OPCGEN004",
        title: "OpcProxy target must be partial",
        messageFormat: "Interface '{0}' is decorated with [GenerateOpcProxy] but is not declared partial",
        category: "OpcClassic.Generators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingOpcInterfaceDescriptor = new(
        id: "OPCGEN005",
        title: "OpcProxy target should be decorated with OpcInterface",
        messageFormat: "Interface '{0}' is decorated with [GenerateOpcProxy] but is not decorated with [OpcInterface]",
        category: "OpcClassic.Generators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor OpcMethodRefOutDescriptor = new(
        id: "OPCGEN006",
        title: "OpcMethod with ref/out parameter cannot have generated body",
        messageFormat: "Method '{0}' is decorated with [OpcMethod] but has a ref/out parameter; falling back to NotImplementedException",
        category: "OpcClassic.Generators",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedMarshallingDescriptor = new(
        id: "OPCGEN008",
        title: "OpcMethod has unsupported parameter or return type",
        messageFormat: "Method '{0}' uses unsupported OPC method type '{1}'; emitting empty-payload placeholder body",
        category: "OpcClassic.Generators",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: "GenerateOpcProxyAttribute.g.cs",
                sourceText: SourceText.From(AttributeSource, Encoding.UTF8)));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: AttributeFullName,
            predicate: static (node, _) => node is InterfaceDeclarationSyntax,
            transform: static (ctx, _) => Transform(ctx));

        context.RegisterSourceOutput(candidates, Emit);
    }

    private static InterfaceModel? Transform(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (ctx.TargetNode is not InterfaceDeclarationSyntax syntax)
        {
            return null;
        }

        bool isPartial = false;
        foreach (var modifier in syntax.Modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword))
            {
                isPartial = true;
                break;
            }
        }

        return new InterfaceModel(
            fullyQualifiedName: symbol.ToDisplayString(TypeDisplayFormat),
            @namespace: symbol.ContainingNamespace?.IsGlobalNamespace == false
                ? symbol.ContainingNamespace!.ToDisplayString()
                : null,
            name: symbol.Name,
            accessibility: symbol.DeclaredAccessibility,
            typeParameterList: TypeParameterList(symbol.TypeParameters),
            typeParameterConstraints: ConstraintClauses(symbol.TypeParameters),
            isPartial: isPartial,
            hasOpcInterfaceAttribute: HasOpcInterfaceAttribute(symbol),
            location: syntax.Identifier.GetLocation(),
            methods: CollectMethods(symbol));
    }

    private static ImmutableArray<MethodModel> CollectMethods(INamedTypeSymbol interfaceSymbol)
    {
        var builder = ImmutableArray.CreateBuilder<MethodModel>();
        foreach (var member in interfaceSymbol.GetMembers())
        {
            if (member is IMethodSymbol { MethodKind: MethodKind.Ordinary } method)
            {
                builder.Add(CreateMethodModel(method));
            }
        }

        return builder.ToImmutable();
    }

    private static MethodModel CreateMethodModel(IMethodSymbol method)
    {
        var outParameters = ImmutableArray.CreateBuilder<string>();
        var parameterNames = ImmutableArray.CreateBuilder<string>();
        var parameters = ImmutableArray.CreateBuilder<ParameterModel>();
        string? cancellationTokenParameterName = null;
        bool hasUnsupportedRefOutParameter = false;

        foreach (var parameter in method.Parameters)
        {
            parameterNames.Add(parameter.Name);

            if (parameter.RefKind == RefKind.Out)
            {
                outParameters.Add(EscapeIdentifier(parameter.Name));
            }

            hasUnsupportedRefOutParameter |= parameter.RefKind != RefKind.None && parameter.RefKind != RefKind.In;

            bool isCancellationToken = string.Equals(
                parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                "global::System.Threading.CancellationToken",
                System.StringComparison.Ordinal);
            if (cancellationTokenParameterName is null && isCancellationToken)
            {
                cancellationTokenParameterName = EscapeIdentifier(parameter.Name);
            }

            parameters.Add(new ParameterModel(
                name: EscapeIdentifier(parameter.Name),
                marshallingType: parameter.Type.ToDisplayString(CodecTypeDisplayFormat),
                isCancellationToken: isCancellationToken));
        }

        var taskReturnKind = ClassifyTaskReturn(method.ReturnType, out string? taskResultType, out string? taskResultMarshallingType);
        string? unsupportedMarshallingType = FindUnsupportedMarshallingType(
            parameters,
            taskReturnKind,
            taskResultMarshallingType);
        string? declaringNamespace = ContainingNamespace(method.ContainingType);

        return new MethodModel(
            name: method.Name,
            returnType: method.ReturnType.ToDisplayString(TypeDisplayFormat),
            typeParameterList: TypeParameterList(method.TypeParameters),
            parameterList: ParameterList(method.Parameters),
            constraintClauses: ConstraintClauses(method.TypeParameters),
            outParameters: outParameters.ToImmutable(),
            parameterNames: parameterNames.ToImmutable(),
            parameters: parameters.ToImmutable(),
            hasOpcMethodAttribute: HasOpcMethodAttribute(method),
            hasUnsupportedRefOutParameter: hasUnsupportedRefOutParameter,
            taskReturnKind: taskReturnKind,
            taskResultType: taskResultType,
            taskResultMarshallingType: taskResultMarshallingType,
            unsupportedMarshallingType: unsupportedMarshallingType,
            cancellationTokenParameterName: cancellationTokenParameterName,
            declaringNamespace: declaringNamespace,
            location: method.Locations.IsDefaultOrEmpty ? Location.None : method.Locations[0]);
    }

    private static string? ContainingNamespace(INamedTypeSymbol symbol) =>
        symbol.ContainingNamespace?.IsGlobalNamespace == false
            ? symbol.ContainingNamespace!.ToDisplayString()
            : null;

    private static void Emit(SourceProductionContext spc, InterfaceModel? maybeModel)
    {
        if (maybeModel is null)
        {
            return;
        }

        InterfaceModel model = maybeModel;

        if (!model.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(NotPartialDescriptor, model.Location, model.FullyQualifiedName));
            return;
        }

        if (!model.HasOpcInterfaceAttribute)
        {
            spc.ReportDiagnostic(Diagnostic.Create(MissingOpcInterfaceDescriptor, model.Location, model.FullyQualifiedName));
        }

        var sb = new StringBuilder(1024);
        sb.AppendLine("// <auto-generated by OpcClassic.Generators.OpcProxyGenerator />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0414 // _channel is captured now and read by later call-shim phases.");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        string indent = hasNamespace ? "    " : string.Empty;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string accessibility = AccessibilityKeyword(model.Accessibility);
        string proxyName = model.Name + "_ClientProxy";
        sb.Append(indent).Append(accessibility).Append(" partial class ").Append(proxyName).Append(model.TypeParameterList)
            .Append(" : ").Append(model.Name).Append(model.TypeParameterList).Append(model.TypeParameterConstraints).AppendLine();
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    private readonly global::OpcClassic.ICallChannel _channel;");
        sb.AppendLine();
        sb.Append(indent).Append("    public ").Append(proxyName).Append("(global::OpcClassic.ICallChannel channel)").AppendLine();
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        _channel = channel ?? throw new global::System.ArgumentNullException(nameof(channel));");
        sb.Append(indent).AppendLine("    }");

        EmitMethods(spc, sb, indent, model);

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        string hint = model.FullyQualifiedName.Replace("global::", string.Empty).Replace("<", "_").Replace(">", "_") + ".OpcProxy.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMethods(SourceProductionContext spc, StringBuilder sb, string indent, InterfaceModel model)
    {
        foreach (var method in model.Methods)
        {
            if (method.HasOpcMethodAttribute && method.HasUnsupportedRefOutParameter)
            {
                spc.ReportDiagnostic(Diagnostic.Create(OpcMethodRefOutDescriptor, method.Location, method.Name));
            }
            else if (method.HasOpcMethodAttribute &&
                method.TaskReturnKind != TaskReturnKind.Unsupported &&
                !method.IsFullyMarshallable)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedMarshallingDescriptor,
                    method.Location,
                    method.Name,
                    method.UnsupportedMarshallingType ?? "<unknown>"));
            }

            EmitMethod(sb, indent, model.Name, model.FullyQualifiedName, method);
        }
    }

    private static void EmitMethod(StringBuilder sb, string indent, string interfaceName, string fullyQualifiedInterfaceName, MethodModel method)
    {
        bool emitInvokeBody = method.HasOpcMethodAttribute &&
            !method.HasUnsupportedRefOutParameter &&
            method.TaskReturnKind != TaskReturnKind.Unsupported;

        sb.AppendLine();
        sb.Append(indent).Append("    public ");
        if (emitInvokeBody && !method.IsFullyMarshallable)
        {
            sb.Append("async ");
        }

        sb.Append(method.ReturnType).Append(' ').Append(method.Name)
            .Append(method.TypeParameterList).Append('(').Append(method.ParameterList).Append(')')
            .Append(method.ConstraintClauses).AppendLine();
        sb.Append(indent).AppendLine("    {");

        if (!emitInvokeBody)
        {
            EmitNotImplementedBody(sb, indent, interfaceName, method);
            sb.Append(indent).AppendLine("    }");
            return;
        }

        EmitInvokeAsyncBody(sb, indent, fullyQualifiedInterfaceName, method);
        sb.Append(indent).AppendLine("    }");
    }

    private static void EmitNotImplementedBody(StringBuilder sb, string indent, string interfaceName, MethodModel method)
    {
        foreach (var parameterName in method.OutParameters)
        {
            sb.Append(indent).Append("        ").Append(parameterName).AppendLine(" = default!;");
        }

        sb.Append(indent).Append("        throw new global::System.NotImplementedException(")
            .Append("\"Phase 6B/7B/8B - per-method shim for '").Append(interfaceName).Append('.')
            .Append(method.Name).Append("' TBD\");").AppendLine();
    }

    private static void EmitInvokeAsyncBody(StringBuilder sb, string indent, string fullyQualifiedInterfaceName, MethodModel method)
    {
        if (method.IsFullyMarshallable)
        {
            EmitMarshalledInvokeAsyncBody(sb, indent, fullyQualifiedInterfaceName, method);
            return;
        }

        EmitEmptyPayloadInvokeAsyncBody(sb, indent, fullyQualifiedInterfaceName, method);
    }

    private static void EmitEmptyPayloadInvokeAsyncBody(StringBuilder sb, string indent, string fullyQualifiedInterfaceName, MethodModel method)
    {
        string cancellationTokenLocal = UniqueLocalName(method.ParameterNames, "__opcCancellationToken");
        string resultLocal = UniqueLocalName(method.ParameterNames, "__opcResult", cancellationTokenLocal);
        string cancellationTokenValue = method.CancellationTokenParameterName ?? "global::System.Threading.CancellationToken.None";

        sb.Append(indent).Append("        var ").Append(cancellationTokenLocal).Append(" = ").Append(cancellationTokenValue).AppendLine(";");
        sb.Append(indent).Append("        var ").Append(resultLocal).AppendLine(" = await _channel.InvokeAsync(");
        sb.Append(indent).Append("            ").Append(fullyQualifiedInterfaceName).AppendLine(".InterfaceId,");
        sb.Append(indent).Append("            ").Append(fullyQualifiedInterfaceName).Append(".Opnums.").Append(method.Name).AppendLine(",");
        sb.Append(indent).AppendLine("            global::System.ReadOnlyMemory<byte>.Empty,");
        sb.Append(indent).Append("            ").Append(cancellationTokenLocal).AppendLine(").ConfigureAwait(false);");
        EmitFailureCheck(sb, indent, resultLocal);

        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            sb.Append(indent).Append("        // Unsupported OPC method type '").Append(method.UnsupportedMarshallingType ?? "<unknown>")
                .AppendLine("'; Phase 6B emits the empty-payload placeholder.");
            sb.Append(indent).AppendLine("        return default!;");
        }
        else
        {
            sb.Append(indent).Append("        // Unsupported OPC method type '").Append(method.UnsupportedMarshallingType ?? "<unknown>")
                .AppendLine("'; Phase 6B emits the empty-payload placeholder.");
        }
    }

    private static void EmitMarshalledInvokeAsyncBody(StringBuilder sb, string indent, string fullyQualifiedInterfaceName, MethodModel method)
    {
        string cancellationTokenLocal = UniqueLocalName(method.ParameterNames, "__opcCancellationToken");
        string bufferLocal = UniqueLocalName(method.ParameterNames, "__opcBuffer", cancellationTokenLocal);
        string payloadLocal = UniqueLocalName(method.ParameterNames, "__opcPayload", cancellationTokenLocal, bufferLocal);
        string writerLocal = UniqueLocalName(method.ParameterNames, "__opcWriter", cancellationTokenLocal, bufferLocal, payloadLocal);
        string channelLocal = UniqueLocalName(method.ParameterNames, "__opcChannel", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal);
        string resultLocal = UniqueLocalName(method.ParameterNames, "__opcResult", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal);
        string responsePayloadLocal = UniqueLocalName(method.ParameterNames, "__opcResponsePayload", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal, resultLocal);
        string responseSpanLocal = UniqueLocalName(method.ParameterNames, "__opcResponseSpan", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal, resultLocal, responsePayloadLocal);
        string readerLocal = UniqueLocalName(method.ParameterNames, "__opcReader", cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, channelLocal, resultLocal, responsePayloadLocal, responseSpanLocal);
        string cancellationTokenValue = method.CancellationTokenParameterName ?? "global::System.Threading.CancellationToken.None";

        EmitEncodeAndInvokeReturn(sb, indent, method, cancellationTokenLocal, bufferLocal, payloadLocal, writerLocal, cancellationTokenValue);
        sb.AppendLine();
        EmitInvokeCoreLocalFunction(sb, indent, fullyQualifiedInterfaceName, method, channelLocal, payloadLocal, bufferLocal, cancellationTokenLocal, resultLocal);
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            sb.AppendLine();
            EmitDecodeResponseLocalFunction(sb, indent, method, responsePayloadLocal, responseSpanLocal, readerLocal);
        }
    }

    private static void EmitEncodeAndInvokeReturn(
        StringBuilder sb,
        string indent,
        MethodModel method,
        string cancellationTokenLocal,
        string bufferLocal,
        string payloadLocal,
        string writerLocal,
        string cancellationTokenValue)
    {
        sb.Append(indent).Append("        var ").Append(cancellationTokenLocal).Append(" = ").Append(cancellationTokenValue).AppendLine(";");
        sb.Append(indent).Append("        var ").Append(bufferLocal).AppendLine(" = global::System.Buffers.ArrayPool<byte>.Shared.Rent(1024);");
        sb.Append(indent).AppendLine("        try");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            global::System.ReadOnlyMemory<byte> ").Append(payloadLocal).AppendLine(";");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).Append("                var ").Append(writerLocal).Append(" = new global::OpcClassic.Ndr.NdrWriter(new global::System.Span<byte>(")
            .Append(bufferLocal).AppendLine(", 0, 1024));");
        foreach (var parameter in method.Parameters)
        {
            if (!parameter.IsCancellationToken)
            {
                EmitCodecWrite(sb, indent, writerLocal, parameter, method);
            }
        }

        sb.Append(indent).Append("                ").Append(payloadLocal).Append(" = new global::System.ReadOnlyMemory<byte>(")
            .Append(bufferLocal).Append(", 0, ").Append(writerLocal).AppendLine(".Position);");
        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).Append("            return ").Append(InvokeCoreName(method)).Append("(_channel, ").Append(payloadLocal).Append(", ")
            .Append(bufferLocal).Append(", ").Append(cancellationTokenLocal).AppendLine(");");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine("        catch");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            global::System.Buffers.ArrayPool<byte>.Shared.Return(").Append(bufferLocal).AppendLine(");");
        sb.Append(indent).AppendLine("            throw;");
        sb.Append(indent).AppendLine("        }");
    }

    private static void EmitInvokeCoreLocalFunction(
        StringBuilder sb,
        string indent,
        string fullyQualifiedInterfaceName,
        MethodModel method,
        string channelLocal,
        string payloadLocal,
        string bufferLocal,
        string cancellationTokenLocal,
        string resultLocal)
    {
        EmitInvokeCoreSignature(sb, indent, method);
        sb.Append(indent).Append("            global::OpcClassic.ICallChannel ").Append(channelLocal).AppendLine(",");
        sb.Append(indent).Append("            global::System.ReadOnlyMemory<byte> ").Append(payloadLocal).AppendLine(",");
        sb.Append(indent).Append("            byte[] ").Append(bufferLocal).AppendLine(",");
        sb.Append(indent).Append("            global::System.Threading.CancellationToken ").Append(cancellationTokenLocal).AppendLine(")");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            try");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).Append("                var ").Append(resultLocal).Append(" = await ").Append(channelLocal).AppendLine(".InvokeAsync(");
        sb.Append(indent).Append("                    ").Append(fullyQualifiedInterfaceName).AppendLine(".InterfaceId,");
        sb.Append(indent).Append("                    ").Append(fullyQualifiedInterfaceName).Append(".Opnums.").Append(method.Name).AppendLine(",");
        sb.Append(indent).Append("                    ").Append(payloadLocal).AppendLine(",");
        sb.Append(indent).Append("                    ").Append(cancellationTokenLocal).AppendLine(").ConfigureAwait(false);");
        EmitFailureCheck(sb, indent + "        ", resultLocal);
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            sb.Append(indent).Append("                return ").Append(DecodeResponseName(method)).Append('(').Append(resultLocal).AppendLine(".ResponsePayload);");
        }

        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("            finally");
        sb.Append(indent).AppendLine("            {");
        sb.Append(indent).Append("                global::System.Buffers.ArrayPool<byte>.Shared.Return(").Append(bufferLocal).AppendLine(");");
        sb.Append(indent).AppendLine("            }");
        sb.Append(indent).AppendLine("        }");
    }

    private static void EmitInvokeCoreSignature(StringBuilder sb, string indent, MethodModel method)
    {
        if (method.TaskReturnKind == TaskReturnKind.TaskOfT)
        {
            sb.Append(indent).Append("        static async ").Append(method.ReturnType).Append(' ').Append(InvokeCoreName(method)).AppendLine("(");
        }
        else
        {
            sb.Append(indent).Append("        static async global::System.Threading.Tasks.Task ").Append(InvokeCoreName(method)).AppendLine("(");
        }
    }

    private static void EmitDecodeResponseLocalFunction(
        StringBuilder sb,
        string indent,
        MethodModel method,
        string responsePayloadLocal,
        string responseSpanLocal,
        string readerLocal)
    {
        sb.Append(indent).Append("        static ").Append(method.TaskResultType).Append(' ').Append(DecodeResponseName(method))
            .Append("(global::System.ReadOnlyMemory<byte> ").Append(responsePayloadLocal).AppendLine(")");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            var ").Append(responseSpanLocal).Append(" = ").Append(responsePayloadLocal).AppendLine(".Span;");
        sb.Append(indent).Append("            var ").Append(readerLocal).Append(" = new global::OpcClassic.Ndr.NdrReader(")
            .Append(responseSpanLocal).AppendLine(");");
        EmitCodecReadReturn(sb, indent, readerLocal, method, responsePayloadLocal, responseSpanLocal);
        sb.Append(indent).AppendLine("        }");
    }
    private static string InvokeCoreName(MethodModel method) => "__opcInvoke" + method.Name + "CoreAsync";

    private static string DecodeResponseName(MethodModel method) => "__opcDecode" + method.Name + "Response";

    private static void EmitFailureCheck(StringBuilder sb, string indent, string resultLocal)
    {
        sb.Append(indent).Append("        if (").Append(resultLocal).AppendLine(".IsFailure)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            throw new global::OpcClassic.OpcException(new global::OpcClassic.OpcResultId(")
            .Append(resultLocal).AppendLine(".Hresult, null));");
        sb.Append(indent).AppendLine("        }");
    }

    private static string? FindUnsupportedMarshallingType(
        IEnumerable<ParameterModel> parameters,
        TaskReturnKind taskReturnKind,
        string? taskResultMarshallingType)
    {
        foreach (var parameter in parameters)
        {
            if (!parameter.IsCancellationToken && !TryGetCodec(parameter.MarshallingType, declaringNamespace: null, out _))
            {
                return parameter.MarshallingType;
            }
        }

        if (taskReturnKind == TaskReturnKind.TaskOfT &&
            (taskResultMarshallingType is null || !TryGetCodec(taskResultMarshallingType, declaringNamespace: null, out _)))
        {
            return taskResultMarshallingType ?? "<unknown>";
        }

        return null;
    }

    private static void EmitCodecWrite(
        StringBuilder sb,
        string indent,
        string writerLocal,
        ParameterModel parameter,
        MethodModel method)
    {
        string statementIndent = indent + "                ";
        if (TryGetCodec(parameter.MarshallingType, method.DeclaringNamespace, out var codec))
        {
            if (codec.IsArray)
            {
                EmitArrayCodecWrite(sb, statementIndent, writerLocal, parameter.Name, codec, method.ParameterNames);
                return;
            }

            sb.Append(statementIndent).Append(FormatWriteExpression(codec, writerLocal, parameter.Name)).AppendLine(";");
            return;
        }

        sb.Append(statementIndent).Append(writerLocal).AppendLine(".WriteRawBytes(global::System.ReadOnlySpan<byte>.Empty);");
    }

    private static void EmitArrayCodecWrite(
        StringBuilder sb,
        string statementIndent,
        string writerLocal,
        string parameterName,
        CodecEmitter codec,
        ImmutableArray<string> parameterNames)
    {
        string itemLocal = UniqueLocalName(parameterNames, "__opcItem", writerLocal, parameterName);
        sb.Append(statementIndent).Append(writerLocal).Append(".WriteUInt32((uint)(").Append(parameterName).AppendLine("?.Length ?? 0));");
        sb.Append(statementIndent).Append("if (").Append(parameterName).AppendLine(" != null)");
        sb.Append(statementIndent).AppendLine("{");
        sb.Append(statementIndent).Append("    foreach (var ").Append(itemLocal).Append(" in ").Append(parameterName).AppendLine(")");
        sb.Append(statementIndent).AppendLine("    {");
        sb.Append(statementIndent).Append("        ").Append(FormatWriteExpression(codec, writerLocal, itemLocal)).AppendLine(";");
        sb.Append(statementIndent).AppendLine("    }");
        sb.Append(statementIndent).AppendLine("}");
    }

    private static void EmitCodecReadReturn(
        StringBuilder sb,
        string indent,
        string readerLocal,
        MethodModel method,
        string responsePayloadLocal,
        string responseSpanLocal)
    {
        string statementIndent = indent + "            ";
        if (TryGetCodec(method.TaskResultMarshallingType!, method.DeclaringNamespace, out var codec))
        {
            if (codec.IsArray)
            {
                EmitArrayCodecReadReturn(
                    sb,
                    statementIndent,
                    readerLocal,
                    codec,
                    method.ParameterNames,
                    responsePayloadLocal,
                    responseSpanLocal);
                return;
            }

            sb.Append(statementIndent).Append("return ").Append(FormatReadExpression(codec, readerLocal)).AppendLine(";");
            return;
        }

        sb.Append(statementIndent).AppendLine("return default!;");
    }

    private static void EmitArrayCodecReadReturn(
        StringBuilder sb,
        string statementIndent,
        string readerLocal,
        CodecEmitter codec,
        ImmutableArray<string> parameterNames,
        string responsePayloadLocal,
        string responseSpanLocal)
    {
        string countLocal = UniqueLocalName(parameterNames, "__opcCount", readerLocal, responsePayloadLocal, responseSpanLocal);
        string arrayLocal = UniqueLocalName(parameterNames, "__opcArray", readerLocal, responsePayloadLocal, responseSpanLocal, countLocal);
        string indexLocal = UniqueLocalName(parameterNames, "__opcIndex", readerLocal, responsePayloadLocal, responseSpanLocal, countLocal, arrayLocal);

        sb.Append(statementIndent).Append("var ").Append(countLocal).Append(" = (int)").Append(readerLocal).AppendLine(".ReadUInt32();");
        sb.Append(statementIndent).Append("var ").Append(arrayLocal).Append(" = new ").Append(codec.ArrayElementType!).Append('[').Append(countLocal).AppendLine("];");
        sb.Append(statementIndent).Append("for (int ").Append(indexLocal).Append(" = 0; ").Append(indexLocal).Append(" < ").Append(countLocal).Append("; ").Append(indexLocal).AppendLine("++)");
        sb.Append(statementIndent).AppendLine("{");
        sb.Append(statementIndent).Append("    ").Append(arrayLocal).Append('[').Append(indexLocal).Append("] = ").Append(FormatReadExpression(codec, readerLocal)).AppendLine(";");
        sb.Append(statementIndent).AppendLine("}");
        sb.Append(statementIndent).Append("return ").Append(arrayLocal).AppendLine(";");
    }

    private static bool TryGetCodec(string typeName, string? declaringNamespace, out CodecEmitter codec)
    {
        if (TryGetArrayElementTypeName(typeName, out string elementTypeName) &&
            !TryGetArrayElementTypeName(elementTypeName, out _) &&
            TryGetCodec(elementTypeName, declaringNamespace, out var elementCodec) &&
            !elementCodec.IsArray)
        {
            codec = CodecEmitter.Array(elementTypeName, elementCodec);
            return true;
        }

        if (string.Equals(typeName, "global::OpcClassic.OpcServerStatus", System.StringComparison.Ordinal) &&
            IsAeNamespace(declaringNamespace))
        {
            codec = AeServerStatusCodec;
            return true;
        }

        return Codecs.TryGetValue(typeName, out codec);
    }

    private static bool TryGetArrayElementTypeName(string typeName, out string elementTypeName)
    {
        if (typeName.EndsWith("[]", System.StringComparison.Ordinal))
        {
            elementTypeName = typeName.Substring(0, typeName.Length - 2);
            return true;
        }

        elementTypeName = string.Empty;
        return false;
    }

    private static CodecEmitter StaticCodec(string codecClassName) =>
        new CodecEmitter(codecClassName + ".Write(ref {Writer}, {Param})", codecClassName + ".Read(ref {Reader})");

    private static string FormatWriteExpression(CodecEmitter codec, string writerLocal, string parameterName) =>
        codec.WriteExpression.Replace("{Writer}", writerLocal).Replace("{Param}", parameterName);

    private static string FormatReadExpression(CodecEmitter codec, string readerLocal) =>
        codec.ReadExpression.Replace("{Reader}", readerLocal);

    private static bool IsAeNamespace(string? declaringNamespace) =>
        string.Equals(declaringNamespace, "OpcClassic.Ae", System.StringComparison.Ordinal) ||
        (declaringNamespace is not null && declaringNamespace.StartsWith("OpcClassic.Ae.", System.StringComparison.Ordinal));

    private static string ParameterList(ImmutableArray<IParameterSymbol> parameters)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < parameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            IParameterSymbol parameter = parameters[i];
            if (parameter.IsParams)
            {
                sb.Append("params ");
            }

            sb.Append(parameter.RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => string.Empty,
            });

            sb.Append(parameter.Type.ToDisplayString(TypeDisplayFormat)).Append(' ').Append(EscapeIdentifier(parameter.Name));

            if (parameter.HasExplicitDefaultValue)
            {
                sb.Append(" = ").Append(FormatDefaultValue(parameter));
            }
        }

        return sb.ToString();
    }

    private static string TypeParameterList(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.Append('<');
        for (int i = 0; i < typeParameters.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(typeParameters[i].Name);
        }

        sb.Append('>');
        return sb.ToString();
    }

    private static string ConstraintClauses(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        if (typeParameters.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var typeParameter in typeParameters)
        {
            string constraints = Constraints(typeParameter);
            if (constraints.Length > 0)
            {
                sb.Append(" where ").Append(typeParameter.Name).Append(" : ").Append(constraints);
            }
        }

        return sb.ToString();
    }

    private static string Constraints(ITypeParameterSymbol typeParameter)
    {
        var constraints = new List<string>();
        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("unmanaged");
        }
        else if (typeParameter.HasValueTypeConstraint)
        {
            constraints.Add("struct");
        }
        else if (typeParameter.HasReferenceTypeConstraint)
        {
            constraints.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
        }
        else if (typeParameter.HasNotNullConstraint)
        {
            constraints.Add("notnull");
        }

        foreach (var constraintType in typeParameter.ConstraintTypes)
        {
            constraints.Add(constraintType.ToDisplayString(TypeDisplayFormat));
        }

        if (typeParameter.HasConstructorConstraint && !typeParameter.HasValueTypeConstraint && !typeParameter.HasUnmanagedTypeConstraint)
        {
            constraints.Add("new()");
        }

        return string.Join(", ", constraints);
    }

    private static string FormatDefaultValue(IParameterSymbol parameter)
    {
        object? value = parameter.ExplicitDefaultValue;
        if (value is null)
        {
            return parameter.Type.IsValueType && parameter.NullableAnnotation != NullableAnnotation.Annotated ? "default" : "null";
        }

        if (parameter.Type.TypeKind == TypeKind.Enum)
        {
            return "(" + parameter.Type.ToDisplayString(TypeDisplayFormat) + ")" +
                System.Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
        }

        return value switch
        {
            string text => SymbolDisplay.FormatLiteral(text, quote: true),
            char ch => SymbolDisplay.FormatLiteral(ch, quote: true),
            bool flag => flag ? "true" : "false",
            sbyte number => number.ToString(CultureInfo.InvariantCulture),
            byte number => number.ToString(CultureInfo.InvariantCulture),
            short number => number.ToString(CultureInfo.InvariantCulture),
            ushort number => number.ToString(CultureInfo.InvariantCulture),
            int number => number.ToString(CultureInfo.InvariantCulture),
            uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number => number.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            _ => "default",
        };
    }

    private static TaskReturnKind ClassifyTaskReturn(
        ITypeSymbol returnType,
        out string? taskResultType,
        out string? taskResultMarshallingType)
    {
        taskResultType = null;
        taskResultMarshallingType = null;
        if (returnType is not INamedTypeSymbol namedType ||
            !string.Equals(namedType.Name, "Task", System.StringComparison.Ordinal) ||
            !string.Equals(namedType.ContainingNamespace.ToDisplayString(), "System.Threading.Tasks", System.StringComparison.Ordinal))
        {
            return TaskReturnKind.Unsupported;
        }

        if (namedType.Arity == 0)
        {
            return TaskReturnKind.Task;
        }

        if (namedType.Arity == 1)
        {
            taskResultType = namedType.TypeArguments[0].ToDisplayString(TypeDisplayFormat);
            taskResultMarshallingType = namedType.TypeArguments[0].ToDisplayString(CodecTypeDisplayFormat);
            return TaskReturnKind.TaskOfT;
        }

        return TaskReturnKind.Unsupported;
    }

    private static bool HasOpcInterfaceAttribute(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (string.Equals(fullName, OpcInterfaceAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool HasOpcMethodAttribute(IMethodSymbol method)
    {
        foreach (var attr in method.GetAttributes())
        {
            string? fullName = attr.AttributeClass?.ToDisplayString(TypeDisplayFormat)?.Replace("global::", string.Empty);
            if (string.Equals(fullName, OpcMethodAttributeFullName, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string UniqueLocalName(ImmutableArray<string> parameterNames, string preferredName, params string[] additionalNames)
    {
        string candidate = preferredName;
        int suffix = 0;
        while (NameMatches(parameterNames, candidate) || NameMatches(additionalNames, candidate))
        {
            suffix++;
            candidate = preferredName + suffix.ToString(CultureInfo.InvariantCulture);
        }

        return candidate;
    }

    private static bool NameMatches(IEnumerable<string> names, string candidate)
    {
        foreach (var name in names)
        {
            if (string.Equals(name, candidate, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string AccessibilityKeyword(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.NotApplicable => "internal",
        _ => "internal",
    };

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    private enum TaskReturnKind
    {
        Unsupported,
        Task,
        TaskOfT,
    }

    private readonly struct CodecEmitter
    {
        public CodecEmitter(string writeExpression, string readExpression)
            : this(writeExpression, readExpression, arrayElementType: null)
        {
        }

        private CodecEmitter(string writeExpression, string readExpression, string? arrayElementType)
        {
            WriteExpression = writeExpression;
            ReadExpression = readExpression;
            ArrayElementType = arrayElementType;
        }

        public string WriteExpression { get; }
        public string ReadExpression { get; }
        public string? ArrayElementType { get; }
        public bool IsArray => ArrayElementType is not null;

        public static CodecEmitter Array(string elementTypeName, CodecEmitter elementCodec) =>
            new(elementCodec.WriteExpression, elementCodec.ReadExpression, elementTypeName);
    }

    private sealed class ParameterModel
    {
        public ParameterModel(string name, string marshallingType, bool isCancellationToken)
        {
            Name = name;
            MarshallingType = marshallingType;
            IsCancellationToken = isCancellationToken;
        }

        public string Name { get; }
        public string MarshallingType { get; }
        public bool IsCancellationToken { get; }
    }

    private sealed class MethodModel
    {
        public MethodModel(
            string name,
            string returnType,
            string typeParameterList,
            string parameterList,
            string constraintClauses,
            ImmutableArray<string> outParameters,
            ImmutableArray<string> parameterNames,
            ImmutableArray<ParameterModel> parameters,
            bool hasOpcMethodAttribute,
            bool hasUnsupportedRefOutParameter,
            TaskReturnKind taskReturnKind,
            string? taskResultType,
            string? taskResultMarshallingType,
            string? unsupportedMarshallingType,
            string? cancellationTokenParameterName,
            string? declaringNamespace,
            Location location)
        {
            Name = name;
            ReturnType = returnType;
            TypeParameterList = typeParameterList;
            ParameterList = parameterList;
            ConstraintClauses = constraintClauses;
            OutParameters = outParameters;
            ParameterNames = parameterNames;
            Parameters = parameters;
            HasOpcMethodAttribute = hasOpcMethodAttribute;
            HasUnsupportedRefOutParameter = hasUnsupportedRefOutParameter;
            TaskReturnKind = taskReturnKind;
            TaskResultType = taskResultType;
            TaskResultMarshallingType = taskResultMarshallingType;
            UnsupportedMarshallingType = unsupportedMarshallingType;
            IsFullyMarshallable = taskReturnKind != TaskReturnKind.Unsupported && unsupportedMarshallingType is null;
            CancellationTokenParameterName = cancellationTokenParameterName;
            DeclaringNamespace = declaringNamespace;
            Location = location;
        }

        public string Name { get; }
        public string ReturnType { get; }
        public string TypeParameterList { get; }
        public string ParameterList { get; }
        public string ConstraintClauses { get; }
        public ImmutableArray<string> OutParameters { get; }
        public ImmutableArray<string> ParameterNames { get; }
        public ImmutableArray<ParameterModel> Parameters { get; }
        public bool HasOpcMethodAttribute { get; }
        public bool HasUnsupportedRefOutParameter { get; }
        public TaskReturnKind TaskReturnKind { get; }
        public string? TaskResultType { get; }
        public string? TaskResultMarshallingType { get; }
        public string? UnsupportedMarshallingType { get; }
        public bool IsFullyMarshallable { get; }
        public string? CancellationTokenParameterName { get; }
        public string? DeclaringNamespace { get; }
        public Location Location { get; }
    }

    private sealed class InterfaceModel
    {
        public InterfaceModel(string fullyQualifiedName, string? @namespace, string name, Accessibility accessibility, string typeParameterList, string typeParameterConstraints, bool isPartial, bool hasOpcInterfaceAttribute, Location location, ImmutableArray<MethodModel> methods)
        {
            FullyQualifiedName = fullyQualifiedName;
            Namespace = @namespace;
            Name = name;
            Accessibility = accessibility;
            TypeParameterList = typeParameterList;
            TypeParameterConstraints = typeParameterConstraints;
            IsPartial = isPartial;
            HasOpcInterfaceAttribute = hasOpcInterfaceAttribute;
            Location = location;
            Methods = methods;
        }

        public string FullyQualifiedName { get; }
        public string? Namespace { get; }
        public string Name { get; }
        public Accessibility Accessibility { get; }
        public string TypeParameterList { get; }
        public string TypeParameterConstraints { get; }
        public bool IsPartial { get; }
        public bool HasOpcInterfaceAttribute { get; }
        public Location Location { get; }
        public ImmutableArray<MethodModel> Methods { get; }
    }
}
