<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>TUnit tests for Opc.Classic.Cpx.</Description>
    <RootNamespace>Opc.Classic.Cpx.Tests</RootNamespace>
    <AssemblyName>Opc.Classic.Cpx.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Opc.Classic.Tests.Fuzz\Opc.Classic.Tests.Fuzz.csproj" />
    <ProjectReference Include="..\..\src\Opc.Classic.Cpx\Opc.Classic.Cpx.csproj" />
    <ProjectReference Include="..\..\src\Opc.Classic.Da\Opc.Classic.Da.csproj" />
  </ItemGroup>

</Project>
